import Link from "next/link";

import { requirePermission } from "@/lib/auth";
import { createDefectAction, createIncidentAction, createReleaseAction } from "@/lib/actions/operations";
import { getOperationalSummary } from "@/lib/operations";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, PageHeader, Select, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow, Textarea } from "@/components/ui";

export const dynamic = "force-dynamic";
const tone = (status: string) => status === "HEALTHY" ? "success" : status === "DOWN" ? "danger" : status === "UNKNOWN" ? "default" : "warning";

export default async function OperationsPage() {
  await requirePermission("operations.view");
  const summary = await getOperationalSummary();
  return <div className="space-y-6">
    <PageHeader eyebrow="Administration / Operations" title="Pilot readiness" description="Internal health, early-life support, incidents, defects, releases, and feedback. This is not a public SLA or external monitoring console." actions={<Link href="/feedback"><Button variant="outline">Submit feedback</Button></Link>} />
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Launch gate:</strong> Phase 18 remains not ready. UAT approval, emulator validation, backup restore evidence, production provider configuration, external alerts, and deployment authorization are still pending.</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Dependencies", summary.health.filter((item) => item.derivedStatus === "HEALTHY").length, "of " + summary.health.length + " healthy"], ["Open incidents", summary.incidents.length, "active"], ["Open defects", summary.defects.length, "active"], ["Feedback", summary.feedback.length, "recent records"], ["Release blockers", summary.releases.length, "in progress or blocked"]].map(([label, value, note]) => <Card key={String(label)}><CardContent><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="text-xs text-slate-500">{note}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>Dependency health</CardTitle><CardDescription>Health checks are server-side records. The public `/api/health` endpoint remains liveness-only.</CardDescription></CardHeader><CardContent><Table><TableHead><TableRow><TableHeadCell>Dependency</TableHeadCell><TableHeadCell>Status</TableHeadCell><TableHeadCell>Latency</TableHeadCell><TableHeadCell>Owner / runbook</TableHeadCell></TableRow></TableHead><TableBody>{summary.health.length ? summary.health.map((item) => <TableRow key={item.id}><TableCell>{item.dependency}</TableCell><TableCell><Badge tone={tone(item.derivedStatus)}>{item.derivedStatus}</Badge></TableCell><TableCell>{item.latencyMs ?? 0} ms</TableCell><TableCell>{item.owner || "Unassigned"}{item.runbookPath ? <div className="text-xs text-slate-500">{item.runbookPath}</div> : null}</TableCell></TableRow>) : <TableRow><TableCell colSpan={4}>No internal health checks recorded yet.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Open incidents</CardTitle></CardHeader><CardContent>{summary.incidents.length ? <div className="space-y-3">{summary.incidents.map((item) => <div key={item.id} className="rounded-xl border border-sourcehub-border p-3"><div className="flex justify-between gap-3"><strong>{item.title}</strong><Badge tone="danger">{item.severity}</Badge></div><p className="mt-1 text-sm text-slate-600">{item.summary}</p></div>)}</div> : <p className="text-sm text-slate-600">No open incidents.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Defect queue</CardTitle></CardHeader><CardContent>{summary.defects.length ? <div className="space-y-3">{summary.defects.map((item) => <div key={item.id} className="rounded-xl border border-sourcehub-border p-3"><div className="flex justify-between gap-3"><strong>{item.title}</strong><Badge tone={item.priority === "P0" || item.priority === "P1" ? "danger" : "warning"}>{item.priority}</Badge></div><p className="mt-1 text-sm text-slate-600">{item.actual}</p></div>)}</div> : <p className="text-sm text-slate-600">No open defects.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Operational controls</CardTitle><CardDescription>Only users with operations management permission can create records. External notification remains a manual launch control.</CardDescription></CardHeader><CardContent><div className="grid gap-6 xl:grid-cols-3"><form action={createIncidentAction} className="space-y-3"><h3 className="font-semibold">Record incident</h3><Input name="title" required placeholder="Short incident title" /><Select name="severity"><option>SEV-1</option><option>SEV-2</option><option>SEV-3</option><option>SEV-4</option></Select><Input name="affectedModules" placeholder="Modules, comma separated" /><Textarea name="summary" required minLength={10} placeholder="Impact, timeline, and current status" /><Button type="submit" size="sm">Create incident</Button></form><form action={createDefectAction} className="space-y-3"><h3 className="font-semibold">Record defect</h3><Input name="title" required placeholder="Defect title" /><div className="grid grid-cols-2 gap-3"><Select name="priority"><option>P0</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></Select><Select name="environment"><option>PILOT</option><option>DEVELOPMENT</option><option>STAGING</option><option>PRODUCTION</option></Select></div><Textarea name="reproduction" required minLength={10} placeholder="Reproduction steps" /><div className="grid grid-cols-2 gap-3"><Input name="expected" required placeholder="Expected" /><Input name="actual" required placeholder="Actual" /></div><Button type="submit" size="sm">Create defect</Button></form><form action={createReleaseAction} className="space-y-3"><h3 className="font-semibold">Track release</h3><Input name="version" required placeholder="Version or release ID" /><Select name="releaseType"><option>PATCH</option><option>MINOR</option><option>MAJOR</option><option>HOTFIX</option><option>PILOT</option><option>BETA</option><option>STAGED</option></Select><Textarea name="summary" required minLength={10} placeholder="Scope, validation, and rollback notes" /><Button type="submit" size="sm">Track release</Button></form></div></CardContent></Card>
  </div>;
}
