import { Link } from "expo-router";
import { FlatList, Pressable, RefreshControl, Text, View } from "react-native";

import { EmptyState, StatusBadge } from "@mobile/components/ui";
import { useAuth } from "@mobile/core/auth-context";
import { roleMode } from "@mobile/core/mobile-core";
import { colors, styles } from "@mobile/theme";

export default function HomeScreen() { const { user, bootstrap, offline, refresh } = useAuth(); const mode = roleMode(user); const tickets = bootstrap?.tickets ?? []; const tasks = bootstrap?.tasks ?? []; const critical = tickets.filter((ticket) => ["URGENT", "CRITICAL"].includes(String(ticket.priority))).length; return <FlatList data={tickets.slice(0, 5)} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={false} onRefresh={refresh} tintColor={colors.blue} />} ListHeaderComponent={<View style={{ gap: 16 }}><View style={styles.header}><Text style={styles.eyebrow}>{offline ? "Offline cache" : `${mode} workspace`}</Text><Text style={styles.title}>Good to see you, {user?.firstName ?? "there"}.</Text><Text style={styles.subtitle}>A focused view of your authorised SourceHub work. Server actions remain authoritative.</Text></View>{offline ? <View style={[styles.card, { backgroundColor: "#FFF8E7" }]}><StatusBadge label="Offline" tone="warning" /><Text style={styles.subtitle}>You can review cached records and create drafts. Pending actions will be labelled until the server confirms them.</Text></View> : null}<View style={{ flexDirection: "row", gap: 10 }}><Metric label={mode === "client" ? "Open tickets" : "Visible tickets"} value={tickets.length} /><Metric label={mode === "technician" ? "Critical" : "Tasks"} value={mode === "technician" ? critical : tasks.length} /></View><View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>Quick actions</Text><Link href="/scan" asChild><Pressable accessibilityRole="button" style={styles.secondaryButton}><Text style={styles.secondaryText}>Scan asset</Text></Pressable></Link></View><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 10 }}><Link href="/ai" asChild><Pressable style={styles.secondaryButton}><Text style={styles.secondaryText}>Ask AI</Text></Pressable></Link>{mode !== "employee" ? <Link href="/(tabs)/tickets" asChild><Pressable style={styles.secondaryButton}><Text style={styles.secondaryText}>My tickets</Text></Pressable></Link> : null}</View></View><Text style={styles.cardTitle}>Recent work</Text></View>} ListEmptyComponent={<EmptyState title="No cached work yet" description="Refresh when online to load records you are authorised to see." />} renderItem={({ item }) => <Link href={`/tickets/${item.id}`} asChild><Pressable style={styles.card}><View style={styles.row}><Text style={styles.cardTitle} numberOfLines={1}>{item.subject ?? item.reference ?? "Ticket"}</Text><StatusBadge label={String(item.status ?? "OPEN")} /></View><Text style={styles.subtitle} numberOfLines={2}>{item.description ?? "No description"}</Text></Pressable></Link>} />; }
function Metric({ label, value }: { label: string; value: number }) { return <View style={[styles.card, { flex: 1 }]}><Text style={styles.subtitle}>{label}</Text><Text style={{ color: colors.ink, fontSize: 26, fontWeight: "800" }}>{value}</Text></View>; }
