import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { createKnowledgeArticleAction } from "@/lib/actions/knowledge";
import { env } from "@/lib/env";
import { Button, Card, CardContent, Input, PageHeader, Select, Textarea } from "@/components/ui";

export default async function NewKnowledgePage() {
  const actor = await requirePermission("knowledge.articles.create");
  return <div className="space-y-6"><PageHeader eyebrow="Knowledge operations" title="New article" description="Draft content is sanitised and persisted in Firestore before it can enter review." actions={<Link href="/knowledge" className="text-sm text-sourcehub-primary">Back to knowledge</Link>} /><Card><CardContent><form action={createKnowledgeArticleAction} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="ownerId" value={actor.id} /><label className="text-sm font-medium md:col-span-2">Title<Input name="title" required maxLength={180} placeholder="How to resolve..." /></label><label className="text-sm font-medium">Slug<Input name="slug" placeholder="Optional stable URL slug" /></label><label className="text-sm font-medium">Article type<Select name="articleType" defaultValue="GUIDE">{["GUIDE", "TROUBLESHOOTING", "FAQ", "POLICY", "PROCEDURE", "SOP", "CHECKLIST", "REFERENCE", "CLIENT_DOCUMENTATION", "KNOWN_ISSUE", "RELEASE_NOTE", "TEMPLATE"].map((item) => <option key={item}>{item}</option>)}</Select></label><label className="text-sm font-medium md:col-span-2">Summary<Textarea name="summary" className="min-h-20" maxLength={600} /></label><label className="text-sm font-medium">Area<Select name="area" defaultValue="INTERNAL"><option>INTERNAL</option><option>CLIENT</option><option>PUBLIC</option></Select></label><label className="text-sm font-medium">Visibility<Select name="visibility" defaultValue="INTERNAL"><option>INTERNAL</option><option>CLIENT</option><option>PUBLIC</option></Select></label><label className="text-sm font-medium">Client ID<Input name="clientId" placeholder="Required for client-only content" /></label><label className="text-sm font-medium">Tags<Input name="tags" placeholder="microsoft, security, onboarding" /></label><label className="text-sm font-medium md:col-span-2">Content HTML / structured editor input<Textarea name="contentHtml" required className="min-h-72 font-mono text-xs" placeholder="<h2>Resolution</h2><p>Write the approved guidance here.</p>" /><span className="mt-1 block text-xs font-normal text-slate-500">HTML is sanitised on the server. Never paste passwords, API keys, private keys or tokens.</span></label><div className="flex gap-3 md:col-span-2"><Button type="submit">Save draft</Button><Link href="/knowledge" className="inline-flex h-10 items-center rounded-xl border border-sourcehub-border px-4 text-sm">Cancel</Link></div></form></CardContent></Card><p className="text-xs text-slate-500">Maximum article content: {env.KNOWLEDGE_ARTICLE_MAX_MB} MB.</p></div>;
}
