import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { getReportingHome, getSharedReports } from "@/lib/reporting";
import { archiveReportAction, duplicateReportAction, shareReportAction, toggleReportFavouriteAction } from "@/lib/actions/reporting";
import { Badge, Button, Card, CardContent, EmptyState, PageHeader, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow } from "@/components/ui";

export default async function SavedReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const actor = await requirePermission("reports.view");
  const [home, shared] = await Promise.all([getReportingHome(), getSharedReports(actor.id)]);
  const saved = [...home.saved, ...shared.filter((item: any) => !home.saved.some((owned: any) => owned.id === item.id))];
  const query = await searchParams;
  const selectedId = String(query.report ?? "");
  const selected: any = saved.find((item: any) => item.id === selectedId);

  return <div className="space-y-6">
    <PageHeader eyebrow="Reporting library" title="Saved reports" description="Personal and explicitly shared configurations. Access is checked again when a report is opened or exported." />
    <Card><CardContent className="p-0">{saved.length ? <Table><TableHead><TableRow><TableHeadCell>Name</TableHeadCell><TableHeadCell>Area</TableHeadCell><TableHeadCell>Sharing</TableHeadCell><TableHeadCell>Actions</TableHeadCell></TableRow></TableHead><TableBody>{saved.filter((item: any) => !item.archivedAt).map((report: any) => <TableRow key={report.id}><TableCell><Link href={`/reports/saved?report=${report.id}`} className="font-semibold text-sourcehub-primary hover:underline">{report.name}</Link>{report.favourite ? <Badge tone="info" className="ml-2">Favourite</Badge> : null}</TableCell><TableCell>{report.area}</TableCell><TableCell>{report.sharedUserIds?.length ? `${report.sharedUserIds.length} user(s)` : "Private"}</TableCell><TableCell><div className="flex flex-wrap gap-2">{report.ownerId === actor.id ? <><form action={toggleReportFavouriteAction}><input type="hidden" name="reportId" value={report.id} /><Button type="submit" size="sm" variant="outline">{report.favourite ? "Unfavourite" : "Favourite"}</Button></form><form action={duplicateReportAction}><input type="hidden" name="reportId" value={report.id} /><Button type="submit" size="sm" variant="outline">Duplicate</Button></form><form action={archiveReportAction}><input type="hidden" name="reportId" value={report.id} /><Button type="submit" size="sm" variant="outline">Archive</Button></form></> : <Badge tone="outline">Shared</Badge>}</div></TableCell></TableRow>)}</TableBody></Table> : <EmptyState title="No saved reports" description="Open a dashboard and save its filters or create a custom report." />}</CardContent></Card>
    {selected ? <Card><CardContent><h2 className="text-lg font-semibold">{selected.name}</h2><p className="mt-2 text-sm text-slate-600">{selected.description}</p><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-slate-500">Area</dt><dd>{selected.area}</dd></div><div><dt className="text-slate-500">Chart</dt><dd>{selected.chartType}</dd></div><div><dt className="text-slate-500">Owner</dt><dd>{selected.ownerId === actor.id ? "You" : "Shared with you"}</dd></div></dl><div className="mt-4 flex gap-2"><Link href={`/reports/${selected.area}?${new URLSearchParams(JSON.parse(selected.filtersJson || "{}")).toString()}`} className="inline-flex h-10 items-center rounded-xl bg-sourcehub-primary px-4 text-sm font-medium text-white">Open report</Link><Link href="/reports/schedules" className="inline-flex h-10 items-center rounded-xl border border-sourcehub-border px-4 text-sm">Schedule</Link></div>{selected.ownerId === actor.id ? <form action={shareReportAction} className="mt-6 space-y-3 border-t border-sourcehub-border pt-5"><input type="hidden" name="reportId" value={selected.id} /><div><label htmlFor="sharedUserIds" className="text-sm font-medium">Share with internal users</label><input id="sharedUserIds" name="sharedUserIds" placeholder="User IDs, comma separated" className="mt-1 block h-10 w-full rounded-xl border border-sourcehub-border px-3 text-sm" /><p className="mt-1 text-xs text-slate-500">Only active users in this workspace can be added.</p></div><Button type="submit" size="sm">Update sharing</Button></form> : null}</CardContent></Card> : null}
  </div>;
}
