"use client";

import { useEffect, useState } from "react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Input } from "@/components/ui";

type Tenant = { id: string; name: string; lifecycleState: string; subscriptionState: string | null; onboardingState: string | null };
type Readiness = { environmentEnabled: boolean; billingEnabled: boolean; readiness: { enabled: boolean; checklistComplete: boolean; checklist: Record<string, boolean>; notes: string } };

export function CommercialConsole() {
  const [readiness, setReadiness] = useState<Readiness | null>(null);
  const [tenants, setTenants] = useState<Tenant[]>([]);
  const [tenantName, setTenantName] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  async function refresh() { const [readinessResponse, operationsResponse] = await Promise.all([fetch("/api/commercial/readiness"), fetch("/api/commercial/operations")]); if (readinessResponse.ok) setReadiness(await readinessResponse.json()); if (operationsResponse.ok) setTenants((await operationsResponse.json()).tenants); }
  useEffect(() => { void refresh(); }, []);
  async function createTenant() { setLoading(true); setMessage(null); try { const response = await fetch("/api/commercial/tenants", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: tenantName, idempotencyKey: crypto.randomUUID() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage(result.created ? "Tenant provisioning queued safely." : "This provisioning request was already processed."); setTenantName(""); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Tenant provisioning failed."); } finally { setLoading(false); } }
  return <div className="space-y-6">{message ? <div role="status" className="rounded-2xl border border-sourcehub-border bg-white px-4 py-3 text-sm">{message}</div> : null}<div className="grid gap-4 md:grid-cols-4"><Metric label="Environment gate" value={readiness?.environmentEnabled ? "Enabled" : "Disabled"} tone={readiness?.environmentEnabled ? "warning" : "success"} /><Metric label="Readiness checklist" value={readiness?.readiness.checklistComplete ? "Complete" : "Incomplete"} tone={readiness?.readiness.checklistComplete ? "success" : "warning"} /><Metric label="Billing" value={readiness?.billingEnabled ? "Configured" : "Sandbox off"} tone={readiness?.billingEnabled ? "warning" : "success"} /><Metric label="Commercial tenants" value={tenants.length} /></div><Card><CardHeader><CardTitle>Commercial activation gate</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-600">Commercial mode is intentionally disabled by default. Environment configuration and every internal readiness control must be approved before a tenant can be activated.</p><div className="grid gap-2 md:grid-cols-2">{Object.entries(readiness?.readiness.checklist ?? {}).map(([key, value]) => <div className="flex items-center justify-between rounded-xl border border-sourcehub-border px-3 py-2 text-sm" key={key}><span>{key.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}</span><Badge tone={value ? "success" : "warning"}>{value ? "Reviewed" : "Required"}</Badge></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Provisioning sandbox</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 md:flex-row"><Input aria-label="Tenant name" placeholder="Customer organization name" value={tenantName} onChange={(event) => setTenantName(event.target.value)} /><Button loading={loading} disabled={!tenantName.trim()} onClick={() => void createTenant()}>Provision tenant</Button></CardContent></Card><Card><CardHeader><CardTitle>Tenant directory</CardTitle></CardHeader><CardContent>{tenants.length ? <div className="divide-y divide-sourcehub-border">{tenants.map((tenant) => <div className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm" key={tenant.id}><div><p className="font-semibold">{tenant.name}</p><p className="text-xs text-slate-500">{tenant.id}</p></div><div className="flex gap-2"><Badge>{tenant.lifecycleState}</Badge><Badge tone={tenant.onboardingState === "READY" ? "success" : "warning"}>{tenant.onboardingState ?? "Provisioning"}</Badge></div></div>)}</div> : <p className="text-sm text-slate-500">No commercial tenants are provisioned yet.</p>}</CardContent></Card></div>;
}

function Metric({ label, value, tone = "default" }: { label: string; value: string | number; tone?: "default" | "success" | "warning" }) { return <Card><CardContent><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-sourcehub-text">{value}</p><Badge tone={tone === "success" ? "success" : tone === "warning" ? "warning" : "outline"}>{tone === "warning" ? "Review" : tone === "success" ? "Safe" : "Recorded"}</Badge></CardContent></Card>; }
