import Link from "next/link";
import { Download, Laptop, Plus, Search } from "lucide-react";

import { requirePermission } from "@/lib/auth";
import { createNetworkSavedViewAction } from "@/lib/actions/network";
import { buttonClassName } from "@/lib/button";
import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { endpointComplianceLabels, endpointHealthLabels } from "@/lib/network";
import { Badge, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, PageHeader, Select, StatCard, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow } from "@/components/ui";
import { formatDateTime } from "@/lib/utils";

const healthTone: Record<string, "success" | "warning" | "danger" | "info"> = { HEALTHY: "success", AT_RISK: "warning", CRITICAL: "danger", OFFLINE: "danger", UNKNOWN: "info" };

export default async function EndpointsPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePermission("endpoints.view");
  const query = (await searchParams) ?? {};
  const search = String(query.search ?? "").trim();
  const clientId = String(query.clientId ?? "");
  const siteId = String(query.siteId ?? "");
  const healthState = String(query.healthState ?? "");
  const complianceState = String(query.complianceState ?? "");
  const checkInState = String(query.checkInState ?? "");
  const cursor = String(query.cursor ?? "");
  const flag = (key: string, value: string) => String(query[key] ?? "") === value;
  const where = {
    workspaceId: env.DEFAULT_WORKSPACE_ID,
    ...(clientId ? { clientId } : {}), ...(siteId ? { siteId } : {}), ...(healthState ? { healthState } : {}), ...(complianceState ? { complianceState } : {}), ...(checkInState ? { checkInState } : {}),
    ...(flag("antivirus", "disabled") ? { antivirusEnabled: false } : {}), ...(flag("firewall", "disabled") ? { firewallEnabled: false } : {}), ...(flag("bitLocker", "disabled") ? { bitLockerEnabled: false } : {}), ...(String(query.diskState ?? "") ? { diskState: String(query.diskState) } : {}),
    ...(search ? { searchTokens: { arrayContainsAny: search.toLowerCase().split(/[^a-z0-9@._:-]+/g).filter((item) => item.length >= 2).slice(0, 10) } } : {}),
  };
  const [clients, sites, endpoints, total, savedViews] = await Promise.all([
    prisma.client.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, status: { not: "FORMER" } }, orderBy: { name: "asc" } }),
    prisma.clientSite.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID }, orderBy: { name: "asc" } }),
    prisma.endpoint.findMany({ where, orderBy: [{ updatedAt: "desc" }], ...(cursor ? { cursor: { id: cursor } } : {}), take: 26 }),
    prisma.endpoint.count({ where }),
    prisma.networkSavedView.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID }, orderBy: [{ createdAt: "desc" }], take: 20 }),
  ]);
  const rows = endpoints.slice(0, 25);
  const nextCursor = endpoints.length > 25 ? rows[rows.length - 1]?.id : null;
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) if (typeof value === "string" && value && key !== "cursor") params.set(key, value);
  const nextHref = nextCursor ? `/network/endpoints?${params.toString()}&cursor=${nextCursor}` : null;
  return <div className="space-y-8">
    <PageHeader eyebrow="Network Management" title="Endpoint inventory" description="Search enrolled Windows endpoints by identity, scope, posture, and check-in state." actions={<div className="flex gap-3"><a href="/api/network/endpoints/export" className={buttonClassName({ variant: "outline" })}><Download className="mr-2 h-4 w-4" />Export CSV</a><Link href="/network/enrolments" className={buttonClassName({ variant: "primary" })}><Plus className="mr-2 h-4 w-4" />Enrol endpoint</Link></div>} />
    <div className="grid gap-4 md:grid-cols-3"><StatCard label="Filtered endpoints" value={total.toLocaleString()} hint="Server-side filtered inventory" icon={<Laptop className="h-5 w-5" />} /><StatCard label="Current page" value={rows.length.toLocaleString()} hint="Maximum 25 records" icon={<Search className="h-5 w-5" />} /><StatCard label="Saved views" value={savedViews.length.toLocaleString()} hint="Personal technician views" /></div>
    <Card><CardHeader><CardTitle>Inventory filters</CardTitle></CardHeader><CardContent><form method="get" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="xl:col-span-2"><label className="text-sm font-medium">Search</label><Input name="search" defaultValue={search} placeholder="Computer, serial, user, IP, MAC, asset tag" /></div><div><label className="text-sm font-medium">Client</label><Select name="clientId" defaultValue={clientId}><option value="">All clients</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></div><div><label className="text-sm font-medium">Site</label><Select name="siteId" defaultValue={siteId}><option value="">All sites</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</Select></div><div><label className="text-sm font-medium">Health</label><Select name="healthState" defaultValue={healthState}><option value="">All health states</option>{Object.entries(endpointHealthLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div><div><label className="text-sm font-medium">Compliance</label><Select name="complianceState" defaultValue={complianceState}><option value="">All compliance states</option>{Object.entries(endpointComplianceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div><div><label className="text-sm font-medium">Check-in</label><Select name="checkInState" defaultValue={checkInState}><option value="">All check-in states</option><option value="ONLINE">Online</option><option value="OFFLINE">Offline</option><option value="NEVER_CHECKED_IN">Never checked in</option><option value="REVOKED">Revoked</option></Select></div><div className="flex items-end gap-2"><button type="submit" className={buttonClassName({ variant: "secondary" })}>Apply</button><Link href="/network/endpoints" className={buttonClassName({ variant: "ghost" })}>Reset</Link></div><div className="flex flex-wrap items-center gap-4 text-sm text-slate-600 md:col-span-2 xl:col-span-4"><label><input type="checkbox" name="antivirus" value="disabled" defaultChecked={flag("antivirus", "disabled")} /> Antivirus disabled</label><label><input type="checkbox" name="firewall" value="disabled" defaultChecked={flag("firewall", "disabled")} /> Firewall disabled</label><label><input type="checkbox" name="bitLocker" value="disabled" defaultChecked={flag("bitLocker", "disabled")} /> BitLocker disabled</label><label><input type="checkbox" name="diskState" value="WARNING" defaultChecked={String(query.diskState ?? "") === "WARNING"} /> Low disk space</label></div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Saved views</CardTitle></CardHeader><CardContent className="space-y-4"><form action={createNetworkSavedViewAction} className="flex flex-col gap-3 sm:flex-row sm:items-end"><input type="hidden" name="filters" value={params.toString()} /><div className="flex-1"><label className="text-sm font-medium">Save current filters</label><Input name="name" placeholder="e.g. Critical endpoints" required maxLength={120} /></div><button className={buttonClassName({ variant: "secondary" })}>Save view</button></form>{savedViews.length > 0 ? <div className="flex flex-wrap gap-2">{savedViews.map((view) => <Link key={view.id} href={`/network/endpoints${view.filters ? `?${view.filters}` : ""}`} className="rounded-full border border-sourcehub-border px-3 py-2 text-sm text-slate-600 hover:border-sourcehub-primary hover:text-sourcehub-primary">{view.name}</Link>)}</div> : <p className="text-sm text-slate-500">No saved views yet. Save a useful operational filter for quick access.</p>}</CardContent></Card>
    <Card><CardContent className="p-0">{rows.length === 0 ? <div className="p-6"><EmptyState title="No endpoints found" description="Create an enrolment token and run the Source IT Services Windows audit to register an endpoint." action={<Link href="/network/enrolments" className={buttonClassName({ variant: "primary" })}>Create enrolment token</Link>} /></div> : <Table><TableHead><TableRow><TableHeadCell>Endpoint</TableHeadCell><TableHeadCell>Client / site</TableHeadCell><TableHeadCell>Health</TableHeadCell><TableHeadCell>Security</TableHeadCell><TableHeadCell>Check-in</TableHeadCell><TableHeadCell>Last audit</TableHeadCell></TableRow></TableHead><TableBody>{rows.map((endpoint) => <TableRow key={endpoint.id}><TableCell><Link href={`/network/endpoints/${endpoint.id}`} className="font-semibold text-sourcehub-primary hover:text-sourcehub-secondary">{endpoint.computerName ?? "Unnamed endpoint"}</Link><p className="mt-1 text-xs text-slate-500">{endpoint.manufacturer ?? "Unknown manufacturer"} {endpoint.model ?? ""} · {endpoint.serialNumber ?? "No serial"}</p><p className="mt-1 text-xs text-slate-500">Asset: {endpoint.assetId ?? "Unlinked"}</p></TableCell><TableCell><p>{clients.find((client) => client.id === endpoint.clientId)?.name ?? "Unknown client"}</p><p className="text-xs text-slate-500">{sites.find((site) => site.id === endpoint.siteId)?.name ?? "Unknown site"}</p></TableCell><TableCell><Badge tone={healthTone[endpoint.healthState] ?? "info"}>{endpointHealthLabels[endpoint.healthState as keyof typeof endpointHealthLabels] ?? endpoint.healthState}</Badge><p className="mt-1 text-xs text-slate-500">{endpointComplianceLabels[endpoint.complianceState as keyof typeof endpointComplianceLabels] ?? endpoint.complianceState}</p></TableCell><TableCell><p className={endpoint.antivirusEnabled === false || endpoint.firewallEnabled === false ? "font-medium text-red-700" : "text-slate-600"}>{endpoint.antivirusEnabled === false ? "AV off" : "AV verified"} · {endpoint.firewallEnabled === false ? "Firewall off" : "Firewall verified"}</p><p className="text-xs text-slate-500">{endpoint.bitLockerEnabled === false ? "Encryption off" : "Encryption verified"}</p></TableCell><TableCell><Badge tone={endpoint.checkInState === "ONLINE" ? "success" : endpoint.checkInState === "OFFLINE" ? "danger" : "warning"}>{endpoint.checkInState}</Badge><p className="mt-1 text-xs text-slate-500">{formatDateTime(endpoint.lastCheckIn)}</p></TableCell><TableCell>{formatDateTime(endpoint.lastSuccessfulCheck)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
    <div className="flex items-center justify-between text-sm text-slate-500"><span>Cursor-based results, 25 per page</span>{nextHref ? <Link href={nextHref} className={buttonClassName({ variant: "outline" })}>Next page</Link> : <span>End of results</span>}</div>
  </div>;
}
