import { requirePermission } from "@/lib/auth";
import { firestoreAdmin } from "@/lib/db";
import { collectionNames } from "@/lib/collections";
import { env } from "@/lib/env";
import { saveAiSettingsAction } from "@/lib/actions/ai";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, PageHeader } from "@/components/ui";

export default async function AiAdministrationPage() {
  await requirePermission("ai.settings.manage");
  const setting = await firestoreAdmin.collection(collectionNames.aiSettings).doc(env.DEFAULT_WORKSPACE_ID).get();
  const data = setting.data() ?? {};
  return <div className="space-y-6"><PageHeader eyebrow="Administration" title="AI controls" description="Provider credentials remain server-side. This page controls workspace-level feature state, limits and retention without displaying secrets." actions={<Badge tone={env.AI_PROVIDER === "dev" ? "warning" : "success"}>{env.AI_PROVIDER === "dev" ? "Development adapter" : "HTTP provider"}</Badge>} /><Card><CardHeader><CardTitle>Provider status</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm md:grid-cols-3"><div><p className="text-slate-500">Provider</p><p className="font-semibold">{env.AI_PROVIDER}</p></div><div><p className="text-slate-500">Model identifier</p><p className="font-semibold">{env.AI_MODEL}</p></div><div><p className="text-slate-500">Credential status</p><p className="font-semibold">{env.AI_PROVIDER === "http" ? (env.AI_PROVIDER_API_KEY ? "Configured server-side" : "Missing server-side key") : "Development-only adapter"}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Workspace controls</CardTitle></CardHeader><CardContent><form action={saveAiSettingsAction} className="grid gap-4 md:grid-cols-2"><label className="text-sm">Enabled<select name="enabled" defaultValue={String(data.enabled ?? env.AI_ENABLED)} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3"><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="text-sm">Emergency disable<select name="emergencyDisabled" defaultValue={String(data.emergencyDisabled ?? env.AI_EMERGENCY_DISABLED)} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3"><option value="false">Not disabled</option><option value="true">Disabled</option></select></label><label className="text-sm md:col-span-2">Allowed modules<input name="allowedModules" defaultValue={(data.allowedModules ?? env.AI_ALLOWED_MODULES.split(",")).join(",")} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3" /></label><label className="text-sm">Daily request limit<input name="dailyRequestLimit" type="number" defaultValue={data.dailyRequestLimit ?? env.AI_DAILY_REQUEST_LIMIT} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3" /></label><label className="text-sm">Monthly request limit<input name="monthlyRequestLimit" type="number" defaultValue={data.monthlyRequestLimit ?? env.AI_MONTHLY_REQUEST_LIMIT} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3" /></label><label className="text-sm">Retention days<input name="retentionDays" type="number" defaultValue={data.retentionDays ?? env.AI_RETENTION_DAYS} className="mt-1 h-11 w-full rounded-xl border border-sourcehub-border px-3" /></label><div className="md:col-span-2"><Button type="submit">Save AI controls</Button></div></form></CardContent></Card></div>;
}
