import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { formatMinorUnits } from "@/lib/money";
import { invoiceStatusLabels, financeStatusTone } from "@/lib/finance-utils";
import { changeInvoiceStatusAction, submitInvoiceApprovalAction } from "@/lib/actions/finance";
import { Badge, Button, Card, CardContent, PageHeader } from "@/components/ui";
export const dynamic = "force-dynamic";
export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) { const actor = await requirePermission("invoices.view"); const { id } = await params; const invoice: any = await prisma.invoice.findUnique({ where: { id } }); if (!invoice || invoice.workspaceId !== env.DEFAULT_WORKSPACE_ID) notFound(); const balance = Math.max(0, Number(invoice.totalMinorUnits) - Number(invoice.amountPaidMinorUnits ?? 0)); return <div className="space-y-6"><PageHeader eyebrow="Invoice" title={invoice.invoiceNumber} description={invoice.clientNameSnapshot} actions={<Link href="/finance/invoices" className="text-sm text-sourcehub-primary">Back to invoices</Link>} /><div className="flex flex-wrap items-center gap-3"><Badge tone={financeStatusTone(invoice.status)}>{invoiceStatusLabels[invoice.status] ?? invoice.status}</Badge>{invoice.status === "DRAFT" && actor.permissions.includes("invoices.create") ? <form action={submitInvoiceApprovalAction}><input type="hidden" name="id" value={id} /><Button type="submit">Submit for approval</Button></form> : null}{invoice.status === "PENDING_APPROVAL" && actor.permissions.includes("invoices.approve") ? <form action={changeInvoiceStatusAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value="APPROVED" /><Button type="submit">Approve</Button></form> : null}{invoice.status === "APPROVED" && actor.permissions.includes("invoices.send") ? <form action={changeInvoiceStatusAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value="SENT" /><Button type="submit">Issue invoice</Button></form> : null}</div><Card><CardContent><div className="grid gap-4 md:grid-cols-4"><div><p className="text-xs uppercase text-slate-500">Invoice date</p><p className="font-medium">{new Date(invoice.invoiceDate).toLocaleDateString("en-ZA")}</p></div><div><p className="text-xs uppercase text-slate-500">Due date</p><p className="font-medium">{new Date(invoice.dueDate).toLocaleDateString("en-ZA")}</p></div><div><p className="text-xs uppercase text-slate-500">Total</p><p className="font-medium">{formatMinorUnits(Number(invoice.totalMinorUnits), invoice.currency)}</p></div><div><p className="text-xs uppercase text-slate-500">Balance</p><p className="text-xl font-semibold">{formatMinorUnits(balance, invoice.currency)}</p></div></div><div className="mt-6 divide-y border-y">{invoice.lines.map((line: any) => <div key={line.sortOrder} className="flex justify-between gap-4 py-3 text-sm"><span>{line.description} <span className="text-slate-500">x {line.quantity}</span></span><span className="font-medium">{formatMinorUnits(Number(line.lineTotalMinorUnits), invoice.currency)}</span></div>)}</div></CardContent></Card></div>; }
