"use client";

import { useActionState } from "react";

import { createEndpointEnrollmentAction, type EnrolmentActionState } from "@/lib/actions/network";
import { buttonClassName } from "@/lib/button";
import { Input, Select, Textarea } from "@/components/ui";

const initialState: EnrolmentActionState = {};

export function NetworkEnrolmentForm({ clients, sites, assets, environments }: { clients: Array<{ id: string; name: string }>; sites: Array<{ id: string; name: string; clientId: string }>; assets: Array<{ id: string; assetTag: string; name: string; clientId?: string | null; siteId?: string | null }>; environments: Array<{ id: string; name: string; clientId: string; siteId: string }> }) {
  const [state, formAction, pending] = useActionState(createEndpointEnrollmentAction, initialState);
  return <form action={formAction} className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><div><label className="text-sm font-medium">Client *</label><Select name="clientId" required><option value="">Choose a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></div><div><label className="text-sm font-medium">Site *</label><Select name="siteId" required><option value="">Choose a site</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</Select></div><div><label className="text-sm font-medium">Link to asset</label><Select name="assetId"><option value="">Link later after audit matching</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.assetTag} · {asset.name}</option>)}</Select></div><div><label className="text-sm font-medium">Network environment</label><Select name="networkEnvironmentId"><option value="">Not linked</option>{environments.map((environment) => <option key={environment.id} value={environment.id}>{environment.name}</option>)}</Select></div><div><label className="text-sm font-medium">Expiry in minutes</label><Input name="expiresInMinutes" type="number" min="5" max="1440" defaultValue="60" required /></div><div><label className="text-sm font-medium">Maximum uses</label><Input name="maxUses" type="number" min="1" max="100" defaultValue="1" required /></div><div className="md:col-span-2"><label className="text-sm font-medium">Technician note</label><Textarea name="notes" placeholder="Optional enrolment context" /></div></div>{state.error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{state.error}</div> : null}{state.token ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">Copy this token now</p><p className="mt-1 text-xs text-emerald-800">It is shown once and is not stored in readable form.</p><code className="mt-3 block break-all rounded-xl bg-white p-3 text-sm text-slate-800">{state.token}</code><p className="mt-2 text-xs text-emerald-800">Expires {state.expiresAt}</p></div> : null}<button disabled={pending} className={buttonClassName({ variant: "primary" })}>{pending ? "Creating token…" : "Create enrolment token"}</button></form>;
}
