import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui";

export function ReportBarChart({ title, rows, emptyLabel = "No grouped data for this period." }: { title: string; rows: Array<{ label: string; value: number }>; emptyLabel?: string }) {
  const max = Math.max(...rows.map((row) => row.value), 1);
  return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{rows.length ? <div className="space-y-3" role="img" aria-label={title}>{rows.map((row) => <div key={row.label} className="grid grid-cols-[minmax(100px,1fr)_3fr_auto] items-center gap-3 text-sm"><span className="truncate text-slate-600">{row.label}</span><div className="h-3 rounded-full bg-sourcehub-muted"><div className="h-3 rounded-full bg-sourcehub-primary" style={{ width: `${Math.max((row.value / max) * 100, 3)}%` }} /></div><span className="font-semibold tabular-nums">{row.value.toLocaleString("en-ZA")}</span></div>)}</div> : <p className="text-sm text-slate-500">{emptyLabel}</p>}</CardContent></Card>;
}

export function ReportTrendChart({ title, points }: { title: string; points: Array<{ label: string; value: number }> }) {
  const width = 640; const height = 220; const pad = 28; const max = Math.max(...points.map((point) => point.value), 1); const path = points.map((point, index) => { const x = points.length <= 1 ? width / 2 : pad + (index / (points.length - 1)) * (width - pad * 2); const y = height - pad - (point.value / max) * (height - pad * 2); return `${index === 0 ? "M" : "L"}${x.toFixed(1)},${y.toFixed(1)}`; }).join(" ");
  return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{points.length > 1 ? <div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-56 min-w-[520px] w-full" role="img" aria-label={title}><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} stroke="#dbe3ef" /><line x1={pad} x2={pad} y1={pad} y2={height - pad} stroke="#dbe3ef" /><path d={path} fill="none" stroke="#0f46b0" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />{points.map((point, index) => { const x = points.length <= 1 ? width / 2 : pad + (index / (points.length - 1)) * (width - pad * 2); const y = height - pad - (point.value / max) * (height - pad * 2); return <circle key={`${point.label}-${index}`} cx={x} cy={y} r="4" fill="#0bbceb"><title>{`${point.label}: ${point.value}`}</title></circle>; })}</svg><div className="flex justify-between text-xs text-slate-500"><span>{points[0]?.label}</span><span>{points.at(-1)?.label}</span></div></div> : <p className="text-sm text-slate-500">No trend data for this period.</p>}</CardContent></Card>;
}
