import "server-only";

import { z } from "zod";
import { collectionNames } from "@/lib/collections";
import { firestoreAdmin } from "@/lib/db";
import { env } from "@/lib/env";
import { hasPermission, type CurrentUser } from "@/lib/permissions";
import { canViewReportArea, getReport } from "@/lib/reporting";
import { redactRecord } from "@/lib/ai-redaction";
import { reportAreas, type ReportArea } from "@/lib/reporting-utils";

export type AiSource = { id: string; type: string; title: string; href: string; excerpt: string };
export type AiToolResult = { data: unknown; sources: AiSource[]; redacted: boolean; suspicious: boolean };
type AiTool = { name: string; description: string; module: string; requiredPermission: string; input: z.ZodTypeAny; execute: (actor: CurrentUser, input: any) => Promise<AiToolResult> };

const querySchema = z.object({ query: z.string().trim().max(300).default(""), overdue: z.boolean().default(false) });
const reportSchema = z.object({ area: z.enum(reportAreas), preset: z.string().trim().max(30).default("this-month") });

function source(type: string, id: string, title: string, href: string, record: Record<string, unknown>): AiSource { return { id, type, title, href, excerpt: JSON.stringify(redactRecord(record)).slice(0, 500) }; }
function matches(record: Record<string, any>, query: string) { if (!query) return true; const haystack = [record.title, record.name, record.subject, record.referenceNumber, record.assetTag, record.serialNumber, record.description, record.status, record.priority].join(" ").toLowerCase(); return query.toLowerCase().split(/\s+/).filter(Boolean).every((term) => haystack.includes(term)); }
function recordDate(value: any) { if (!value) return null; if (value?.toDate) return value.toDate() as Date; const date = new Date(value); return Number.isFinite(date.getTime()) ? date : null; }
function isOverdue(record: Record<string, any>) { const due = recordDate(record.dueDate ?? record.slaDueAt); return Boolean(due && due.getTime() < Date.now()); }
async function workspaceRecords(collection: string, limit = 100): Promise<Array<Record<string, any>>> { return (await firestoreAdmin.collection(collection).where("workspaceId", "==", env.DEFAULT_WORKSPACE_ID).limit(limit).get()).docs.map((document) => ({ id: document.id, ...document.data() })); }
function safeTicket(record: Record<string, any>) { return { id: record.id, referenceNumber: record.referenceNumber, title: record.title ?? record.subject, status: record.status, priority: record.priority, clientId: record.clientId, createdAt: record.createdAt, resolvedAt: record.resolvedAt, dueDate: record.dueDate ?? record.slaDueAt, description: record.description }; }

const tools: AiTool[] = [
  { name: "search_tickets", description: "Search authorised service-desk tickets, including overdue work.", module: "tickets", requiredPermission: "tickets.view", input: querySchema, execute: async (_actor, input) => { const records = await workspaceRecords(collectionNames.tickets, 120); const filtered = records.filter((record) => matches(record, input.query) && (!input.overdue || (!['RESOLVED', 'CLOSED'].includes(String(record.status)) && isOverdue(record)))).slice(0, 20); return { data: filtered.map((record) => redactRecord(safeTicket(record))), sources: filtered.map((record) => source("ticket", record.id, record.title ?? record.referenceNumber ?? "Ticket", `/tickets/${record.id}`, safeTicket(record))), redacted: true, suspicious: filtered.some((record) => /ignore previous|system prompt|reveal secret/i.test(String(record.description ?? ""))) }; } },
  { name: "search_clients", description: "Search authorised client records without confidential margins or notes.", module: "clients", requiredPermission: "clients.view", input: querySchema, execute: async (_actor, input) => { const records = (await workspaceRecords(collectionNames.clients, 120)).filter((record) => matches(record, input.query)).slice(0, 20); const safe = records.map((record) => ({ id: record.id, name: record.name, status: record.status, healthState: record.healthState, accountManagerId: record.accountManagerId, createdAt: record.createdAt, updatedAt: record.updatedAt })); return { data: safe.map((record) => redactRecord(record)), sources: safe.map((record) => source("client", record.id, String(record.name ?? "Client"), `/clients/${record.id}`, record)), redacted: true, suspicious: false }; } },
  { name: "search_assets", description: "Search authorised asset inventory and health summaries.", module: "assets", requiredPermission: "assets.view", input: querySchema, execute: async (_actor, input) => { const records = (await workspaceRecords(collectionNames.assets, 120)).filter((record) => matches(record, input.query)).slice(0, 20); const safe = records.map((record) => ({ id: record.id, assetTag: record.assetTag, name: record.name, status: record.status, healthState: record.healthState, clientId: record.clientId, siteId: record.siteId, assetTypeId: record.assetTypeId, warrantyId: record.warrantyId })); return { data: safe.map((record) => redactRecord(record)), sources: safe.map((record) => source("asset", record.id, String(record.name ?? record.assetTag ?? "Asset"), `/assets/${record.id}`, record)), redacted: true, suspicious: false }; } },
  { name: "search_endpoints", description: "Search endpoint compliance and health summaries without credentials or raw audit payloads.", module: "networks", requiredPermission: "endpoints.view", input: querySchema, execute: async (_actor, input) => { const records = (await workspaceRecords(collectionNames.endpoints, 120)).filter((record) => matches(record, input.query)).slice(0, 20); const safe = records.map((record) => ({ id: record.id, computerName: record.computerName, manufacturer: record.manufacturer, model: record.model, healthState: record.healthState, complianceState: record.complianceState, checkInState: record.checkInState, antivirusEnabled: record.antivirusEnabled, firewallEnabled: record.firewallEnabled, bitLockerEnabled: record.bitLockerEnabled, secureBootEnabled: record.secureBootEnabled, clientId: record.clientId, siteId: record.siteId })); return { data: safe.map((record) => redactRecord(record)), sources: safe.map((record) => source("endpoint", record.id, String(record.computerName ?? "Endpoint"), `/network/endpoints/${record.id}`, record)), redacted: true, suspicious: false }; } },
  { name: "search_projects", description: "Search authorised project status, health, milestones and delivery summaries.", module: "projects", requiredPermission: "projects.view", input: querySchema, execute: async (_actor, input) => { const records = (await workspaceRecords(collectionNames.projects, 120)).filter((record) => matches(record, input.query)).slice(0, 20); const safe = records.map((record) => ({ id: record.id, name: record.name, status: record.status, healthState: record.healthState, progressPercent: record.progressPercent, clientId: record.clientId, dueDate: record.dueDate, updatedAt: record.updatedAt })); return { data: safe.map((record) => redactRecord(record)), sources: safe.map((record) => source("project", record.id, String(record.name ?? "Project"), `/projects/${record.id}`, record)), redacted: true, suspicious: false }; } },
  { name: "search_knowledge", description: "Search authorised internal Knowledge Base article summaries and excerpts.", module: "knowledge", requiredPermission: "knowledge.internal.view", input: querySchema, execute: async (_actor, input) => { const records = (await workspaceRecords(collectionNames.knowledgeArticles, 160)).filter((record) => record.status !== "ARCHIVED" && matches(record, input.query)).slice(0, 12); const safe = records.map((record) => ({ id: record.id, title: record.title, summary: record.summary, contentText: String(record.contentText ?? "").slice(0, 900), status: record.status, visibility: record.visibility, articleType: record.articleType, clientId: record.clientId, updatedAt: record.updatedAt })); return { data: safe.map((record) => redactRecord(record)), sources: safe.map((record) => source("knowledge", record.id, String(record.title ?? "Knowledge article"), `/knowledge/${record.id}`, record)), redacted: true, suspicious: safe.some((record) => /ignore previous|system prompt|reveal secret/i.test(String(record.contentText ?? ""))) }; } },
  { name: "read_report", description: "Run an approved server-side report and return KPI values and definitions.", module: "reports", requiredPermission: "reports.view", input: reportSchema, execute: async (actor, input) => { if (!canViewReportArea(actor, input.area as ReportArea)) throw new Error("The user does not have permission for that report area."); const report = await getReport(input.area as ReportArea, { preset: input.preset }); const data = { area: report.area, label: report.label, freshness: report.freshness, generatedAt: report.generatedAt, aggregationLastCompleted: report.aggregationLastCompleted, metrics: report.metrics.map((metric) => ({ key: metric.key, label: metric.label, value: metric.value, previousValue: metric.previousValue, change: metric.change, unit: metric.unit, definitionKey: metric.definitionKey })), notes: report.notes }; return { data: redactRecord(data), sources: report.metrics.filter((metric) => metric.href).slice(0, 12).map((metric) => ({ id: metric.key, type: "report", title: metric.label, href: metric.href!, excerpt: `${metric.label}: ${metric.value ?? "No data"}` })), redacted: true, suspicious: false }; } },
  { name: "read_kpi_definitions", description: "Read the approved definitions for SourceHub KPIs.", module: "reports", requiredPermission: "reports.view", input: z.object({ query: z.string().trim().max(100).default("") }), execute: async (_actor, input) => { const definitions: Array<Record<string, any>> = (await firestoreAdmin.collection(collectionNames.kpiDefinitions).where("workspaceId", "==", env.DEFAULT_WORKSPACE_ID).limit(100).get()).docs.map((document) => ({ id: document.id, ...document.data() })); const filtered = definitions.filter((record) => !input.query || JSON.stringify(record).toLowerCase().includes(input.query.toLowerCase())).slice(0, 20); return { data: filtered.map((record) => redactRecord(record)), sources: filtered.map((record) => ({ id: String(record.id), type: "kpi", title: String(record.name ?? record.key ?? "KPI definition"), href: "/reports/kpis", excerpt: String(record.calculation ?? record.description ?? "") })), redacted: true, suspicious: false }; } },
];

export const aiToolRegistry = Object.fromEntries(tools.map((tool) => [tool.name, { name: tool.name, description: tool.description, module: tool.module, requiredPermission: tool.requiredPermission, maxResults: 20 }])) as Record<string, Omit<AiTool, "input" | "execute">>;

export async function executeAiTool(name: string, actor: CurrentUser, input: unknown) {
  const tool = tools.find((candidate) => candidate.name === name);
  if (!tool) throw new Error("That AI operation is not allowlisted.");
  if (!hasPermission(actor, tool.requiredPermission) && !hasPermission(actor, "reports.manage")) throw new Error(`Missing permission ${tool.requiredPermission}.`);
  if (!env.AI_ALLOWED_MODULES.split(",").map((item) => item.trim()).includes(tool.module)) throw new Error(`The ${tool.module} AI feature is disabled.`);
  const parsed = tool.input.parse(input);
  return tool.execute(actor, parsed);
}
