export const collectionNames = {
  workspaces: "workspaces",
  users: "users",
  roles: "roles",
  permissions: "permissions",
  userRoles: "userRoles",
  rolePermissions: "rolePermissions",
  sessions: "sessions",
  auditLogs: "auditLogs",
  notifications: "notifications",
  settings: "settings",
  employees: "employees",
  departments: "departments",
  teams: "teams",
  jobTitles: "jobTitles",
  employeeContracts: "employeeContracts",
  employeeDocuments: "employeeDocuments",
  employeeEmergencyContacts: "employeeEmergencyContacts",
  employeeQualifications: "employeeQualifications",
  employeeTraining: "employeeTraining",
  onboardingTemplates: "onboardingTemplates",
  onboardingWorkflows: "onboardingWorkflows",
  onboardingTasks: "onboardingTasks",
  offboardingTemplates: "offboardingTemplates",
  offboardingWorkflows: "offboardingWorkflows",
  offboardingTasks: "offboardingTasks",
  employeeNotes: "employeeNotes",
  employeeActivities: "employeeActivities",
  employeeStatusHistory: "employeeStatusHistory",
  employeeManagerHistory: "employeeManagerHistory",
  employeeUniqueness: "employeeUniqueness",
  attendanceProfiles: "attendanceProfiles",
  workLocations: "workLocations",
  workSchedules: "workSchedules",
  attendanceAssignments: "attendanceAssignments",
  attendanceEvents: "attendanceEvents",
  attendanceSessions: "attendanceSessions",
  attendanceBreaks: "attendanceBreaks",
  attendanceExceptions: "attendanceExceptions",
  attendanceApprovals: "attendanceApprovals",
  attendanceIdempotency: "attendanceIdempotency",
  attendanceLocks: "attendanceLocks",
  timesheets: "timesheets",
  overtimeRequests: "overtimeRequests",
  tickets: "tickets",
  ticketCategories: "ticketCategories",
  ticketSequences: "ticketSequences",
  ticketComments: "ticketComments",
  ticketAttachments: "ticketAttachments",
  ticketHistory: "ticketHistory",
  slaPolicies: "slaPolicies",
  slaEvents: "slaEvents",
  escalations: "escalations",
  escalationExecutions: "escalationExecutions",
  automationRules: "automationRules",
  automationExecutions: "automationExecutions",
  emailMessages: "emailMessages",
  emailAttachments: "emailAttachments",
  emailRetries: "emailRetries",
  assets: "assets",
  assetTypes: "assetTypes",
  assetAssignments: "assetAssignments",
  assetEvents: "assetEvents",
  assetSoftware: "assetSoftware",
  softwareCatalog: "softwareCatalog",
  softwareLicences: "softwareLicences",
  licenceAssignments: "licenceAssignments",
  assetMaintenance: "assetMaintenance",
  assetWarranties: "assetWarranties",
  assetFiles: "assetFiles",
  assetImports: "assetImports",
  assetTagCounters: "assetTagCounters",
  assetHealthSnapshots: "assetHealthSnapshots",
  networkEnvironments: "networkEnvironments",
  networkDevices: "networkDevices",
  endpoints: "endpoints",
  endpointEnrollments: "endpointEnrollments",
  endpointCredentials: "endpointCredentials",
  endpointAudits: "endpointAudits",
  endpointSnapshots: "endpointSnapshots",
  endpointChanges: "endpointChanges",
  networkAlerts: "networkAlerts",
  networkAlertEvents: "networkAlertEvents",
  monitoringPolicies: "monitoringPolicies",
  auditIngestionLogs: "auditIngestionLogs",
  endpointCommands: "endpointCommands",
  endpointCommandResults: "endpointCommandResults",
  endpointRateLimits: "endpointRateLimits",
  endpointNonces: "endpointNonces",
  networkSavedViews: "networkSavedViews",
  networkRetentionRuns: "networkRetentionRuns",
  clients: "clients",
  clientContacts: "clientContacts",
  clientSites: "clientSites",
  contracts: "contracts",
  supportAgreements: "supportAgreements",
  billingProfiles: "billingProfiles",
  clientNotes: "clientNotes",
  clientFiles: "clientFiles",
  portalInvitations: "portalInvitations",
  portalAccounts: "portalAccounts",
  businessHours: "businessHours",
  publicHolidays: "publicHolidays",
  technicianQueues: "technicianQueues",
  projects: "projects",
  projectUniqueness: "projectUniqueness",
  projectStatusHistory: "projectStatusHistory",
  projectMembers: "projectMembers",
  projectTasks: "projectTasks",
  projectTaskUniqueness: "projectTaskUniqueness",
  projectTaskStatusHistory: "projectTaskStatusHistory",
  projectTaskDependencies: "projectTaskDependencies",
  projectMilestones: "projectMilestones",
  projectTimeEntries: "projectTimeEntries",
  projectTimerLocks: "projectTimerLocks",
  projectComments: "projectComments",
  projectCommentEdits: "projectCommentEdits",
  projectFiles: "projectFiles",
  projectRisks: "projectRisks",
  projectActivities: "projectActivities",
  projectHealthSnapshots: "projectHealthSnapshots",
  projectTemplates: "projectTemplates",
  projectTemplateTasks: "projectTemplateTasks",
  projectSavedViews: "projectSavedViews",
  projectTicketLinks: "projectTicketLinks",
  projectAssetLinks: "projectAssetLinks",
  projectAutomationExecutions: "projectAutomationExecutions",
  financeSettings: "financeSettings",
  clientBillingProfiles: "clientBillingProfiles",
  quotes: "quotes",
  quoteUniqueness: "quoteUniqueness",
  quoteRevisions: "quoteRevisions",
  invoices: "invoices",
  invoiceUniqueness: "invoiceUniqueness",
  recurringInvoiceTemplates: "recurringInvoiceTemplates",
  recurringInvoiceRuns: "recurringInvoiceRuns",
  creditNotes: "creditNotes",
  creditNoteUniqueness: "creditNoteUniqueness",
  payments: "payments",
  paymentUniqueness: "paymentUniqueness",
  paymentAllocations: "paymentAllocations",
  expenses: "expenses",
  expenseUniqueness: "expenseUniqueness",
  suppliers: "suppliers",
  supplierUniqueness: "supplierUniqueness",
  purchaseOrders: "purchaseOrders",
  purchaseOrderUniqueness: "purchaseOrderUniqueness",
  purchaseReceipts: "purchaseReceipts",
  budgets: "budgets",
  budgetRevisions: "budgetRevisions",
  financialApprovals: "financialApprovals",
  financialDocuments: "financialDocuments",
  financialActivities: "financialActivities",
  financialExports: "financialExports",
  financialNumberCounters: "financialNumberCounters",
} as const;

export type CollectionName = (typeof collectionNames)[keyof typeof collectionNames];

export function workspaceCollectionPath(workspaceId: string, collection: string) {
  return `workspaces/${workspaceId}/${collection}`;
}

export function workspaceClientPath(workspaceId: string, clientId: string) {
  return `workspaces/${workspaceId}/clients/${clientId}`;
}

export function clientFileStoragePath(workspaceId: string, clientId: string, fileName: string) {
  return `${workspaceClientPath(workspaceId, clientId)}/files/${fileName}`;
}

export function ticketFileStoragePath(workspaceId: string, ticketReference: string, fileName: string) {
  return `workspaces/${workspaceId}/tickets/${ticketReference}/files/${fileName}`;
}
