import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("SourceHub"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1).default("demo-api-key"),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1).default("sourcehub.firebaseapp.com"),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1).default("sourcehub-dev"),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1).default("sourcehub-dev.appspot.com"),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1).default("000000000000"),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1).default("1:000000000000:web:sourcehubdev"),
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: z.string().optional().default(""),
  SOURCEHUB_FIREBASE_SERVICE_ACCOUNT_PATH: z.string().min(1).default("firebase-service-account.json"),
  FIREBASE_SERVICE_ACCOUNT_PATH: z.string().min(1).default("firebase-service-account.json"),
  DEFAULT_WORKSPACE_ID: z.string().min(1).default("source-it-services"),
  DEFAULT_WORKSPACE_NAME: z.string().min(1).default("Source IT Services"),
  DEFAULT_COMPANY_NAME: z.string().min(1).default("Source IT Services"),
  DEFAULT_TRADING_NAME: z.string().min(1).default("SourceHub"),
  DEFAULT_SUPPORT_EMAIL: z.string().email().default("support@sourceitservices.co.za"),
  EMAIL_SUPPORT_ADDRESS: z.string().email().default("support@sourceitservices.co.za"),
  DEFAULT_CONTACT_NUMBER: z.string().min(1).default("+27 11 000 0000"),
  DEFAULT_WEBSITE: z.string().url().default("https://sourceitservices.co.za"),
  DEFAULT_TIMEZONE: z.string().min(1).default("Africa/Johannesburg"),
  DEFAULT_COUNTRY: z.string().min(1).default("South Africa"),
  DEFAULT_DATE_FORMAT: z.string().min(1).default("dd MMM yyyy"),
  DEFAULT_BUSINESS_START_TIME: z.string().min(4).default("08:00"),
  DEFAULT_BUSINESS_END_TIME: z.string().min(4).default("17:00"),
  DEFAULT_WORKING_DAYS: z.string().min(1).default("mon,tue,wed,thu,fri"),
  DEFAULT_TICKET_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(25),
  DEFAULT_CLIENT_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(50),
  DEFAULT_EMAIL_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(25),
  MAILBOX_PROVIDER: z.enum(["dev", "imap"]).default("dev"),
  MAILBOX_IMAP_HOST: z.string().optional().default(""),
  MAILBOX_IMAP_PORT: z.coerce.number().int().min(1).default(993),
  MAILBOX_USERNAME: z.string().optional().default(""),
  MAILBOX_PASSWORD: z.string().optional().default(""),
  MAILBOX_SECURE: z.coerce.boolean().default(true),
  MAILBOX_POLL_INTERVAL_MINUTES: z.coerce.number().int().min(1).default(5),
  PORTAL_INVITATION_EXPIRY_DAYS: z.coerce.number().int().min(1).default(14),
  FIREBASE_AUTH_EMULATOR_HOST: z.string().optional().default(""),
  FIRESTORE_EMULATOR_HOST: z.string().optional().default(""),
  FIREBASE_STORAGE_EMULATOR_HOST: z.string().optional().default(""),
  FIREBASE_FUNCTIONS_EMULATOR_HOST: z.string().optional().default(""),
  ENDPOINT_CREDENTIAL_PEPPER: z.string().min(16).default("sourcehub-development-endpoint-pepper"),
  ENDPOINT_RATE_LIMIT_PER_MINUTE: z.coerce.number().int().min(1).max(120).default(12),
  NETWORK_AUDIT_RETENTION_DAYS: z.coerce.number().int().min(7).max(3650).default(90),
  NETWORK_INGESTION_LOG_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  EMPLOYEE_DOCUMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(15),
  EMPLOYEE_CONTRACT_EXPIRY_DAYS: z.coerce.number().int().min(1).max(365).default(60),
  EMPLOYEE_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(2555),
  ATTENDANCE_LOCATION_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  ATTENDANCE_EVENT_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(2555),
  FINANCE_DEFAULT_CURRENCY: z.string().length(3).default("ZAR"),
  FINANCE_DEFAULT_VAT_RATE_BPS: z.coerce.number().int().min(0).max(10000).default(1500),
  FINANCE_DEFAULT_PAYMENT_TERMS_DAYS: z.coerce.number().int().min(0).max(365).default(30),
  FINANCE_QUOTE_VALIDITY_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  FINANCE_DOCUMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_ARTICLE_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_PUBLIC_FEEDBACK_PER_MINUTE: z.coerce.number().int().min(1).max(30).default(5),
  KNOWLEDGE_ANALYTICS_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(365),
  KNOWLEDGE_REVIEW_REMINDER_DAYS: z.coerce.number().int().min(1).max(365).default(14),
  KNOWLEDGE_PUBLIC_ARTICLES_ENABLED: z.coerce.boolean().default(true),
  REPORTING_AGGREGATION_INTERVAL_MINUTES: z.coerce.number().int().min(5).max(1440).default(60),
  REPORTING_EXPORT_MAX_ROWS: z.coerce.number().int().min(100).max(100000).default(10000),
  REPORTING_EXPORT_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  REPORTING_STALE_AFTER_MINUTES: z.coerce.number().int().min(5).max(10080).default(180),
  REPORTING_SCHEDULE_MAX_RECIPIENTS: z.coerce.number().int().min(1).max(50).default(20),
  AI_ENABLED: z.coerce.boolean().default(true),
  AI_EMERGENCY_DISABLED: z.coerce.boolean().default(false),
  AI_PROVIDER: z.enum(["dev", "http"]).default("dev"),
  AI_PROVIDER_URL: z.union([z.literal(""), z.string().url()]).default(""),
  AI_PROVIDER_API_KEY: z.string().optional().default(""),
  AI_MODEL: z.string().min(1).default("development-adapter-v1"),
  AI_ALLOWED_MODULES: z.string().default("tickets,clients,assets,networks,employees,attendance,projects,finance,knowledge,reports"),
  AI_MAX_PROMPT_CHARS: z.coerce.number().int().min(1000).max(100000).default(24000),
  AI_MAX_OUTPUT_TOKENS: z.coerce.number().int().min(64).max(16000).default(1200),
  AI_MAX_TOOL_CALLS: z.coerce.number().int().min(1).max(10).default(3),
  AI_DAILY_REQUEST_LIMIT: z.coerce.number().int().min(1).max(10000).default(100),
  AI_MONTHLY_REQUEST_LIMIT: z.coerce.number().int().min(1).max(100000).default(2000),
  AI_RETENTION_DAYS: z.coerce.number().int().min(1).max(3650).default(90),
  AI_REQUEST_TIMEOUT_MS: z.coerce.number().int().min(1000).max(120000).default(30000),
  AUTOMATION_ENABLED: z.coerce.boolean().default(true),
  AUTOMATION_EMERGENCY_DISABLED: z.coerce.boolean().default(false),
  AUTOMATION_MAX_STEPS: z.coerce.number().int().min(1).max(100).default(40),
  AUTOMATION_MAX_CONDITION_DEPTH: z.coerce.number().int().min(1).max(10).default(4),
  AUTOMATION_MAX_RETRIES: z.coerce.number().int().min(0).max(10).default(3),
  AUTOMATION_MAX_EXECUTION_MINUTES: z.coerce.number().int().min(1).max(1440).default(30),
  AUTOMATION_MAX_CHILD_DEPTH: z.coerce.number().int().min(0).max(10).default(3),
  AUTOMATION_IDEMPOTENCY_RETENTION_DAYS: z.coerce.number().int().min(1).max(3650).default(30),
  AUTOMATION_EXECUTION_RETENTION_DAYS: z.coerce.number().int().min(7).max(3650).default(90),
  AUTOMATION_WEBHOOK_TIMEOUT_MS: z.coerce.number().int().min(1000).max(30000).default(10000),
  AUTOMATION_WEBHOOK_MAX_RECIPIENTS: z.coerce.number().int().min(1).max(100).default(20),
  MOBILE_ENABLED: z.coerce.boolean().default(true),
  MOBILE_EMERGENCY_DISABLED: z.coerce.boolean().default(false),
  MOBILE_CURRENT_VERSION: z.string().min(1).default("1.0.0"),
  MOBILE_MIN_SUPPORTED_VERSION: z.string().min(1).default("1.0.0"),
  MOBILE_RECOMMENDED_VERSION: z.string().min(1).default("1.0.0"),
  MOBILE_SESSION_DAYS: z.coerce.number().int().min(1).max(90).default(30),
  MOBILE_SYNC_MAX_OPERATIONS: z.coerce.number().int().min(1).max(50).default(25),
  MOBILE_CACHE_RETENTION_DAYS: z.coerce.number().int().min(1).max(90).default(14),
  MOBILE_LOCATION_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  MOBILE_REQUIRE_APP_CHECK: z.coerce.boolean().default(false),
  ENTERPRISE_ENABLED: z.coerce.boolean().default(true),
  ENTERPRISE_FIREBASE_IDP_ENABLED: z.coerce.boolean().default(false),
  ENTERPRISE_ALLOW_AUTO_PROVISIONING: z.coerce.boolean().default(false),
  ENTERPRISE_DEFAULT_ROLE: z.string().min(1).default("Employee"),
  ENTERPRISE_API_KEY_PEPPER: z.string().min(16).default("sourcehub-development-api-key-pepper"),
  ENTERPRISE_API_RATE_LIMIT_PER_MINUTE: z.coerce.number().int().min(1).max(10000).default(120),
  ENTERPRISE_API_MAX_PAGE_SIZE: z.coerce.number().int().min(1).max(200).default(50),
  ENTERPRISE_WEBHOOK_TIMEOUT_MS: z.coerce.number().int().min(1000).max(30000).default(10000),
  ENTERPRISE_WEBHOOK_SECRET_REF: z.string().optional().default(""),
  ENTERPRISE_WEBHOOK_DEV_SECRET: z.string().optional().default(""),
  ENTERPRISE_MFA_ENFORCEMENT_MODE: z.enum(["DISABLED", "IDP_ASSURANCE", "FIREBASE_MFA"]).default("DISABLED"),
  ENTERPRISE_SESSION_DAYS: z.coerce.number().int().min(1).max(30).default(7),
  ENTERPRISE_BACKUP_STATUS: z.enum(["NOT_CONFIGURED", "CONFIGURED", "FAILED"]).default("NOT_CONFIGURED"),
  ENTERPRISE_BACKUP_PROJECT: z.string().optional().default(""),
  ENTERPRISE_BACKUP_BUCKET: z.string().optional().default(""),
  ENTERPRISE_FUNCTIONS_REGION: z.string().min(1).default("europe-west1"),
  COMMERCIAL_SAAS_ENABLED: z.coerce.boolean().default(false),
  COMMERCIAL_READINESS_REQUIRED: z.coerce.boolean().default(true),
  COMMERCIAL_BILLING_ENABLED: z.coerce.boolean().default(false),
  COMMERCIAL_BILLING_PROVIDER: z.enum(["disabled", "sandbox", "stripe"]).default("disabled"),
  COMMERCIAL_BILLING_WEBHOOK_SECRET: z.string().optional().default(""),
  COMMERCIAL_DEFAULT_PLAN_KEY: z.string().min(1).default("internal-sandbox"),
  COMMERCIAL_TRIAL_DAYS: z.coerce.number().int().min(0).max(365).default(30),
  COMMERCIAL_USAGE_EVENT_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(400),
  COMMERCIAL_TENANT_DELETION_RECOVERY_DAYS: z.coerce.number().int().min(7).max(3650).default(30),
  COMMERCIAL_MAX_IMPORT_MB: z.coerce.number().int().min(1).max(500).default(50),
  COMMERCIAL_MAX_EXPORT_DAYS: z.coerce.number().int().min(1).max(30).default(7),
  COMMERCIAL_SUPPORT_SESSION_MINUTES: z.coerce.number().int().min(5).max(120).default(30),
  COMMERCIAL_CUSTOM_DOMAINS_ENABLED: z.coerce.boolean().default(false),
  COMMERCIAL_INTEGRATION_SANDBOX_ENABLED: z.coerce.boolean().default(true),
  OPERATIONS_ENABLED: z.coerce.boolean().default(true),
  OPERATIONS_EARLY_LIFE_HOURS: z.coerce.number().int().min(1).max(168).default(24),
  OPERATIONS_EARLY_LIFE_DAYS: z.coerce.number().int().min(1).max(30).default(7),
  OPERATIONS_STABILISATION_DAYS: z.coerce.number().int().min(7).max(180).default(30),
  OPERATIONS_ANALYTICS_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(180),
  OPERATIONS_HEALTH_STALE_MINUTES: z.coerce.number().int().min(5).max(1440).default(15),
  OPERATIONS_ALERT_COOLDOWN_MINUTES: z.coerce.number().int().min(1).max(1440).default(30),
  OPERATIONS_ERROR_RATE_WARNING_BPS: z.coerce.number().int().min(1).max(10000).default(500),
  OPERATIONS_ERROR_RATE_CRITICAL_BPS: z.coerce.number().int().min(1).max(10000).default(1000),
  DEV_ADMIN_EMAIL: z.string().email().default("admin@sourcehub.local"),
  DEV_ADMIN_PASSWORD: z.string().min(12).default("SourceHub123!"),
  DEV_ADMIN_FIRST_NAME: z.string().min(1).default("Dev"),
  DEV_ADMIN_LAST_NAME: z.string().min(1).default("Administrator"),
  DEV_ADMIN_EMPLOYEE_NUMBER: z.string().min(1).default("SH-0001"),
  DEV_ADMIN_JOB_TITLE: z.string().min(1).default("Platform Administrator"),
  DEV_ADMIN_DEPARTMENT: z.string().min(1).default("IT Operations"),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  throw new Error(
    `Invalid environment variables:\n${parsed.error.issues
      .map((issue) => `- ${issue.path.join(".")}: ${issue.message}`)
      .join("\n")}`,
  );
}

export const env = parsed.data;
