import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("SourceHub"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1).default("demo-api-key"),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1).default("sourcehub.firebaseapp.com"),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1).default("sourcehub-dev"),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1).default("sourcehub-dev.appspot.com"),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1).default("000000000000"),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1).default("1:000000000000:web:sourcehubdev"),
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: z.string().optional().default(""),
  SOURCEHUB_FIREBASE_SERVICE_ACCOUNT_PATH: z.string().min(1).default("firebase-service-account.json"),
  FIREBASE_SERVICE_ACCOUNT_PATH: z.string().min(1).default("firebase-service-account.json"),
  DEFAULT_WORKSPACE_ID: z.string().min(1).default("source-it-services"),
  DEFAULT_WORKSPACE_NAME: z.string().min(1).default("Source IT Services"),
  DEFAULT_COMPANY_NAME: z.string().min(1).default("Source IT Services"),
  DEFAULT_TRADING_NAME: z.string().min(1).default("SourceHub"),
  DEFAULT_SUPPORT_EMAIL: z.string().email().default("support@sourceitservices.co.za"),
  EMAIL_SUPPORT_ADDRESS: z.string().email().default("support@sourceitservices.co.za"),
  DEFAULT_CONTACT_NUMBER: z.string().min(1).default("+27 11 000 0000"),
  DEFAULT_WEBSITE: z.string().url().default("https://sourceitservices.co.za"),
  DEFAULT_TIMEZONE: z.string().min(1).default("Africa/Johannesburg"),
  DEFAULT_COUNTRY: z.string().min(1).default("South Africa"),
  DEFAULT_DATE_FORMAT: z.string().min(1).default("dd MMM yyyy"),
  DEFAULT_BUSINESS_START_TIME: z.string().min(4).default("08:00"),
  DEFAULT_BUSINESS_END_TIME: z.string().min(4).default("17:00"),
  DEFAULT_WORKING_DAYS: z.string().min(1).default("mon,tue,wed,thu,fri"),
  DEFAULT_TICKET_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(25),
  DEFAULT_CLIENT_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(50),
  DEFAULT_EMAIL_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).default(25),
  MAILBOX_PROVIDER: z.enum(["dev", "imap"]).default("dev"),
  MAILBOX_IMAP_HOST: z.string().optional().default(""),
  MAILBOX_IMAP_PORT: z.coerce.number().int().min(1).default(993),
  MAILBOX_USERNAME: z.string().optional().default(""),
  MAILBOX_PASSWORD: z.string().optional().default(""),
  MAILBOX_SECURE: z.coerce.boolean().default(true),
  MAILBOX_POLL_INTERVAL_MINUTES: z.coerce.number().int().min(1).default(5),
  PORTAL_INVITATION_EXPIRY_DAYS: z.coerce.number().int().min(1).default(14),
  FIREBASE_AUTH_EMULATOR_HOST: z.string().optional().default(""),
  FIRESTORE_EMULATOR_HOST: z.string().optional().default(""),
  FIREBASE_STORAGE_EMULATOR_HOST: z.string().optional().default(""),
  FIREBASE_FUNCTIONS_EMULATOR_HOST: z.string().optional().default(""),
  ENDPOINT_CREDENTIAL_PEPPER: z.string().min(16).default("sourcehub-development-endpoint-pepper"),
  ENDPOINT_RATE_LIMIT_PER_MINUTE: z.coerce.number().int().min(1).max(120).default(12),
  NETWORK_AUDIT_RETENTION_DAYS: z.coerce.number().int().min(7).max(3650).default(90),
  NETWORK_INGESTION_LOG_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  EMPLOYEE_DOCUMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(15),
  EMPLOYEE_CONTRACT_EXPIRY_DAYS: z.coerce.number().int().min(1).max(365).default(60),
  EMPLOYEE_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(2555),
  ATTENDANCE_LOCATION_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  ATTENDANCE_EVENT_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(2555),
  FINANCE_DEFAULT_CURRENCY: z.string().length(3).default("ZAR"),
  FINANCE_DEFAULT_VAT_RATE_BPS: z.coerce.number().int().min(0).max(10000).default(1500),
  FINANCE_DEFAULT_PAYMENT_TERMS_DAYS: z.coerce.number().int().min(0).max(365).default(30),
  FINANCE_QUOTE_VALIDITY_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  FINANCE_DOCUMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_ARTICLE_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_ATTACHMENT_MAX_MB: z.coerce.number().int().min(1).max(50).default(25),
  KNOWLEDGE_PUBLIC_FEEDBACK_PER_MINUTE: z.coerce.number().int().min(1).max(30).default(5),
  KNOWLEDGE_ANALYTICS_RETENTION_DAYS: z.coerce.number().int().min(30).max(3650).default(365),
  KNOWLEDGE_REVIEW_REMINDER_DAYS: z.coerce.number().int().min(1).max(365).default(14),
  KNOWLEDGE_PUBLIC_ARTICLES_ENABLED: z.coerce.boolean().default(true),
  DEV_ADMIN_EMAIL: z.string().email().default("admin@sourcehub.local"),
  DEV_ADMIN_PASSWORD: z.string().min(12).default("SourceHub123!"),
  DEV_ADMIN_FIRST_NAME: z.string().min(1).default("Dev"),
  DEV_ADMIN_LAST_NAME: z.string().min(1).default("Administrator"),
  DEV_ADMIN_EMPLOYEE_NUMBER: z.string().min(1).default("SH-0001"),
  DEV_ADMIN_JOB_TITLE: z.string().min(1).default("Platform Administrator"),
  DEV_ADMIN_DEPARTMENT: z.string().min(1).default("IT Operations"),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  throw new Error(
    `Invalid environment variables:\n${parsed.error.issues
      .map((issue) => `- ${issue.path.join(".")}: ${issue.message}`)
      .join("\n")}`,
  );
}

export const env = parsed.data;
