import {
  LayoutDashboard,
  Tickets,
  BriefcaseBusiness,
  Boxes,
  Network,
  Clock3,
  Users,
  BarChart3,
  ShieldAlert,
  Settings2,
  Gauge,
  Workflow,
  Mail,
  FolderKanban,
  ReceiptText,
  BookOpenText,
  Sparkles,
} from "lucide-react";

export const navigationItems = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, permission: "dashboard.view" },
  { label: "Tickets", href: "/tickets", icon: Tickets, permission: "tickets.view" },
  { label: "Service Desk", href: "/service-desk", icon: Gauge, permission: "technicians.view" },
  { label: "Clients", href: "/clients", icon: BriefcaseBusiness, permission: "clients.view" },
  { label: "Assets", href: "/assets", icon: Boxes, permission: "assets.view" },
  { label: "Network", href: "/network", icon: Network, permission: "networks.view" },
  { label: "Time & Attendance", href: "/attendance", icon: Clock3, permission: "attendance.view" },
  { label: "Employees", href: "/employees", icon: Users, permission: "employees.view" },
  { label: "Projects", href: "/projects", icon: FolderKanban, permission: "projects.view" },
  { label: "Finance", href: "/finance", icon: ReceiptText, permission: "finance.dashboard.view" },
  { label: "Knowledge Base", href: "/knowledge", icon: BookOpenText, permission: "knowledge.internal.view" },
  { label: "Administration", href: "/administration/users", icon: Users, permission: "users.view" },
  { label: "SLA Policies", href: "/administration/sla-policies", icon: Workflow, permission: "slaPolicies.view" },
  { label: "Automations", href: "/administration/automations", icon: Workflow, permission: "automation.view" },
  { label: "Email", href: "/administration/email", icon: Mail, permission: "email.view" },
  { label: "Reports", href: "/reports", icon: BarChart3, permission: "reports.view" },
  { label: "SourceHub AI", href: "/ai", icon: Sparkles, permission: "ai.use" },
  { label: "AI Administration", href: "/administration/ai", icon: ShieldAlert, permission: "ai.settings.manage" },
  { label: "Administration", href: "/administration/users", icon: ShieldAlert, permission: "users.view" },
  { label: "Settings", href: "/settings", icon: Settings2, permission: "settings.view" },
] as const;

export const comingSoonSections = new Set(["Reports"]);
