export type PermissionCatalogEntry = {
  key: string;
  name: string;
  group: string;
  description: string;
};

export function permissionName(key: string) {
  return key
    .split(".")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function entry(key: string, group: string, description: string): PermissionCatalogEntry {
  return {
    key,
    name: permissionName(key),
    group,
    description,
  };
}

export const permissionCatalog: PermissionCatalogEntry[] = [
  entry("dashboard.view", "dashboard", "View operational dashboard"),
  entry("users.view", "identity", "View employees and administrators"),
  entry("users.create", "identity", "Create user accounts"),
  entry("users.edit", "identity", "Update user accounts and passwords"),
  entry("roles.view", "identity", "View roles and permissions"),
  entry("roles.manage", "identity", "Create and maintain roles"),
  entry("audit.view", "governance", "View audit logs"),
  entry("settings.view", "governance", "View company settings"),
  entry("settings.manage", "governance", "Edit company settings"),
  entry("tickets.view", "service-desk", "View all tickets"),
  entry("tickets.create", "service-desk", "Create tickets"),
  entry("tickets.edit", "service-desk", "Edit tickets"),
  entry("tickets.assign", "service-desk", "Assign tickets"),
  entry("tickets.comment", "service-desk", "Add ticket replies and notes"),
  entry("tickets.attach", "service-desk", "Upload ticket attachments"),
  entry("tickets.note", "service-desk", "Add internal ticket notes"),
  entry("tickets.reply", "service-desk", "Add public ticket replies"),
  entry("tickets.update", "service-desk", "Update core ticket fields"),
  entry("slaPolicies.view", "service-desk", "View SLA policies"),
  entry("slaPolicies.manage", "service-desk", "Create and manage SLA policies"),
  entry("escalations.view", "service-desk", "View escalation history"),
  entry("escalations.manage", "service-desk", "Configure escalation rules"),
  entry("automation.view", "service-desk", "View automation runs"),
  entry("automation.manage", "service-desk", "Manage automations"),
  entry("automations.view", "automation", "View automation workflows and executions"),
  entry("automations.create", "automation", "Create automation workflow drafts"),
  entry("automations.update", "automation", "Edit automation workflow drafts"),
  entry("automations.review", "automation", "Review workflow definitions and tests"),
  entry("automations.publish", "automation", "Publish immutable workflow versions"),
  entry("automations.activate", "automation", "Activate published workflows"),
  entry("automations.pause", "automation", "Pause active workflows"),
  entry("automations.archive", "automation", "Archive automation workflows"),
  entry("automations.execute", "automation", "Execute trusted automation actions"),
  entry("automations.cancel", "automation", "Cancel automation executions"),
  entry("automations.retry", "automation", "Retry failed automation executions"),
  entry("automations.approve", "automation", "Approve automation actions"),
  entry("automations.templates.manage", "automation", "Manage automation templates"),
  entry("automations.webhooks.manage", "automation", "Manage outbound webhook configurations"),
  entry("automations.monitor.view", "automation", "View automation monitoring metrics"),
  entry("automations.audit.view", "automation", "View automation execution audit history"),
  entry("automations.high_risk.approve", "automation", "Approve high-risk automation actions"),
  entry("email.view", "service-desk", "View email processing status"),
  entry("email.manage", "service-desk", "Configure email integration"),
  entry("technicians.view", "service-desk", "View technician workspace"),
  entry("technicians.manage", "service-desk", "Manage technician queues"),
  entry("assets.view", "assets", "View assets"),
  entry("assets.create", "assets", "Create assets"),
  entry("assets.update", "assets", "Update assets"),
  entry("assets.assign", "assets", "Assign assets"),
  entry("assets.transfer", "assets", "Transfer assets"),
  entry("assets.archive", "assets", "Archive assets"),
  entry("assets.retire", "assets", "Retire assets"),
  entry("assets.dispose", "assets", "Dispose assets"),
  entry("assets.import", "assets", "Import assets"),
  entry("assets.export", "assets", "Export assets"),
  entry("assetTypes.manage", "assets", "Manage asset type configuration"),
  entry("asset_files.manage", "assets", "Manage asset files"),
  entry("asset_maintenance.manage", "assets", "Manage maintenance records"),
  entry("asset_software.manage", "assets", "Manage software inventory"),
  entry("asset_licences.view", "assets", "View software licences"),
  entry("asset_licences.manage", "assets", "Manage software licences"),
  entry("asset_financials.view", "assets", "View asset financials"),
  entry("asset_security.view", "assets", "View asset security details"),
  entry("asset_audit.view", "assets", "View asset audit history"),
  entry("networks.view", "networks", "View network environments and operational summaries"),
  entry("networks.create", "networks", "Create network environments"),
  entry("networks.update", "networks", "Update network environments"),
  entry("networks.archive", "networks", "Archive and restore network environments"),
  entry("network_devices.manage", "networks", "Create and maintain network devices"),
  entry("endpoints.view", "networks", "View endpoint inventory and health"),
  entry("endpoints.enrol", "networks", "Create endpoint enrolment tokens"),
  entry("endpoints.revoke", "networks", "Revoke endpoint credentials"),
  entry("endpoints.audit", "networks", "Request and review endpoint audits"),
  entry("endpoint_security.view", "networks", "View endpoint security posture"),
  entry("endpoint_software.view", "networks", "View endpoint software inventory"),
  entry("endpoint_raw_audits.view", "networks", "View protected raw audit metadata"),
  entry("monitoring_policies.manage", "networks", "Create and manage monitoring policies"),
  entry("network_alerts.view", "networks", "View network and endpoint alerts"),
  entry("network_alerts.manage", "networks", "Assign, acknowledge, and resolve alerts"),
  entry("network_alerts.suppress", "networks", "Suppress network alerts with a reason"),
  entry("network_reports.export", "networks", "Export network and endpoint reports"),
  entry("network_credentials.manage", "networks", "Manage protected endpoint credentials"),
  entry("clients.view", "crm", "View clients"),
  entry("clients.create", "crm", "Create clients"),
  entry("clients.update", "crm", "Update clients"),
  entry("clients.archive", "crm", "Archive and restore clients"),
  entry("contacts.manage", "crm", "Manage contacts"),
  entry("sites.manage", "crm", "Manage client sites"),
  entry("contracts.view", "crm", "View contracts"),
  entry("contracts.manage", "crm", "Create and manage contracts"),
  entry("support_agreements.manage", "crm", "Manage support agreements"),
  entry("billing.view", "crm", "View billing profiles"),
  entry("billing.manage", "crm", "Manage billing profiles"),
  entry("client_files.manage", "crm", "Upload and manage client files"),
  entry("portal_access.manage", "crm", "Invite and manage portal access"),
  entry("workspaces.manage", "platform", "Manage workspaces and scoping"),
  entry("attendance.view", "attendance", "View attendance records"),
  entry("attendance.clock", "attendance", "Clock in, clock out, and manage breaks"),
  entry("attendance.manage", "attendance", "Manage attendance configuration"),
  entry("attendance.approve", "attendance", "Approve attendance exceptions and overtime"),
  entry("attendance.reports", "attendance", "View attendance reports"),
  entry("attendance.sensitive_view", "attendance", "View restricted attendance verification details"),
  entry("attendance.profiles.manage", "attendance", "Manage attendance profiles"),
  entry("attendance.locations.manage", "attendance", "Manage work locations"),
  entry("attendance.schedules.manage", "attendance", "Manage work schedules"),
  entry("attendance.exceptions.manage", "attendance", "Manage attendance exceptions"),
  entry("employees.view", "employees", "View the employee directory"),
  entry("employees.create", "employees", "Create employee records"),
  entry("employees.update", "employees", "Update employee records"),
  entry("employees.archive", "employees", "Archive and restore employee records"),
  entry("employees.sensitive_view", "employees", "View restricted employee information"),
  entry("employees.identity_view", "employees", "View protected identity references"),
  entry("employees.compensation_view", "employees", "View compensation summaries"),
  entry("employee_contracts.view", "employees", "View employee contracts"),
  entry("employee_contracts.manage", "employees", "Manage employee contracts"),
  entry("employee_documents.view", "employees", "View employee documents"),
  entry("employee_documents.manage", "employees", "Manage employee documents"),
  entry("employee_emergency_contacts.view", "employees", "View emergency contacts"),
  entry("employee_emergency_contacts.manage", "employees", "Manage emergency contacts"),
  entry("employee_qualifications.manage", "employees", "Manage qualifications and certifications"),
  entry("employee_training.manage", "employees", "Manage employee training"),
  entry("departments.manage", "employees", "Manage departments"),
  entry("teams.manage", "employees", "Manage teams"),
  entry("job_titles.manage", "employees", "Manage job titles"),
  entry("onboarding.manage", "employees", "Manage onboarding workflows"),
  entry("offboarding.manage", "employees", "Manage offboarding workflows"),
  entry("employee_accounts.manage", "employees", "Manage employee account links"),
  entry("employee_notes.view", "employees", "View employee notes"),
  entry("employee_notes.manage", "employees", "Manage employee notes"),
  entry("employee_audit.view", "employees", "View employee activity history"),
  entry("projects.view", "projects", "View projects and work management"),
  entry("projects.create", "projects", "Create projects"),
  entry("projects.update", "projects", "Update project records"),
  entry("projects.approve", "projects", "Approve projects"),
  entry("projects.archive", "projects", "Archive and restore projects"),
  entry("projects.complete", "projects", "Complete projects"),
  entry("project_tasks.view", "projects", "View project tasks"),
  entry("project_tasks.manage", "projects", "Create and manage project tasks"),
  entry("project_members.manage", "projects", "Manage project members"),
  entry("project_time.view", "projects", "View project time entries"),
  entry("project_time.log", "projects", "Log project time"),
  entry("project_time.approve", "projects", "Approve or reject project time"),
  entry("project_files.manage", "projects", "Manage project files"),
  entry("project_risks.manage", "projects", "Manage project risks and issues"),
  entry("project_templates.manage", "projects", "Manage project templates"),
  entry("project_financials.view", "projects", "View restricted project financial fields"),
  entry("project_reports.export", "projects", "Export project reports"),
  entry("client_projects.view", "projects", "View explicitly shared client projects"),
  entry("client_projects.manage_visibility", "projects", "Manage client project visibility"),
  entry("finance.dashboard.view", "finance", "View the finance dashboard"),
  entry("finance.settings.manage", "finance", "Manage finance settings and billing profiles"),
  entry("finance.reports.view", "finance", "View finance reports"),
  entry("finance.exports.create", "finance", "Export finance data"),
  entry("quotes.view", "finance", "View quotes"),
  entry("quotes.create", "finance", "Create quotes"),
  entry("quotes.update", "finance", "Update draft quotes"),
  entry("quotes.approve", "finance", "Approve quotes"),
  entry("quotes.send", "finance", "Send quotes"),
  entry("invoices.view", "finance", "View invoices"),
  entry("invoices.create", "finance", "Create invoices"),
  entry("invoices.approve", "finance", "Approve invoices"),
  entry("invoices.send", "finance", "Issue and send invoices"),
  entry("credit_notes.create", "finance", "Create credit notes"),
  entry("credit_notes.approve", "finance", "Approve credit notes"),
  entry("payments.view", "finance", "View payments"),
  entry("payments.record", "finance", "Record payments"),
  entry("payments.allocate", "finance", "Allocate payments"),
  entry("payments.reverse", "finance", "Reverse payments"),
  entry("expenses.create", "finance", "Create expenses"),
  entry("expenses.view", "finance", "View expenses"),
  entry("expenses.approve", "finance", "Approve expenses"),
  entry("suppliers.view", "finance", "View suppliers"),
  entry("suppliers.manage", "finance", "Manage suppliers"),
  entry("purchase_orders.create", "finance", "Create purchase orders"),
  entry("purchase_orders.approve", "finance", "Approve purchase orders"),
  entry("purchase_orders.receive", "finance", "Receive purchase orders"),
  entry("budgets.view", "finance", "View budgets"),
  entry("budgets.manage", "finance", "Manage budgets"),
  entry("financial_documents.view", "finance", "View private finance documents"),
  entry("financial_documents.manage", "finance", "Manage private finance documents"),
  entry("financial_audit.view", "finance", "View finance audit history"),
  entry("payroll_exports.manage", "finance", "Prepare payroll exports"),
  entry("knowledge.internal.view", "knowledge", "View internal knowledge articles"),
  entry("knowledge.client.view", "knowledge", "View client knowledge articles"),
  entry("knowledge.public.view", "knowledge", "View the public knowledge portal"),
  entry("knowledge.public.manage", "knowledge", "Manage public knowledge publishing"),
  entry("knowledge.articles.create", "knowledge", "Create knowledge articles"),
  entry("knowledge.articles.update", "knowledge", "Update knowledge article drafts"),
  entry("knowledge.articles.review", "knowledge", "Review knowledge articles"),
  entry("knowledge.articles.approve", "knowledge", "Approve knowledge articles"),
  entry("knowledge.articles.publish", "knowledge", "Publish knowledge articles"),
  entry("knowledge.articles.archive", "knowledge", "Archive knowledge articles"),
  entry("knowledge.categories.manage", "knowledge", "Manage knowledge categories"),
  entry("knowledge.tags.manage", "knowledge", "Manage knowledge tags"),
  entry("knowledge.files.manage", "knowledge", "Manage private knowledge attachments"),
  entry("knowledge.feedback.manage", "knowledge", "Manage knowledge feedback"),
  entry("knowledge.analytics.view", "knowledge", "View knowledge analytics"),
  entry("knowledge.policies.manage", "knowledge", "Manage knowledge policies"),
  entry("knowledge.acknowledgements.view", "knowledge", "View policy acknowledgements"),
  entry("knowledge.exports.create", "knowledge", "Export knowledge content"),
  entry("knowledge.audit.view", "knowledge", "View knowledge audit history"),
  entry("knowledge.credential_references.view", "knowledge", "View credential references"),
  entry("knowledge.search.analytics", "knowledge", "View knowledge search analytics"),
  entry("knowledge.import.manage", "knowledge", "Import knowledge content"),
  entry("knowledge.relations.manage", "knowledge", "Manage article relationships"),
  entry("ai.use", "ai", "Use the SourceHub AI assistant"),
  entry("ai.tickets.use", "ai", "Use AI with authorised tickets"),
  entry("ai.clients.use", "ai", "Use AI with authorised clients"),
  entry("ai.assets.use", "ai", "Use AI with authorised assets"),
  entry("ai.networks.use", "ai", "Use AI with authorised networks"),
  entry("ai.employees.use", "ai", "Use AI with authorised employee summaries"),
  entry("ai.attendance.use", "ai", "Use AI with authorised attendance summaries"),
  entry("ai.projects.use", "ai", "Use AI with authorised projects"),
  entry("ai.finance.use", "ai", "Use AI with approved finance summaries"),
  entry("ai.knowledge.use", "ai", "Use AI with authorised knowledge content"),
  entry("ai.reports.use", "ai", "Use AI with approved reports and KPIs"),
  entry("ai.actions.propose", "ai", "Propose safe AI actions for review"),
  entry("ai.actions.confirm", "ai", "Confirm safe AI action proposals"),
  entry("ai.settings.manage", "ai", "Manage AI settings and feature policies"),
  entry("ai.usage.view", "ai", "View AI usage and cost summaries"),
  entry("ai.feedback.review", "ai", "Review AI quality feedback"),
  entry("ai.audit.view", "ai", "View AI audit events"),
  entry("reports.view", "reporting", "View reporting home and authorised reports"),
  entry("reports.executive.view", "reporting", "View executive reporting"),
  entry("reports.service_desk.view", "reporting", "View service desk reporting"),
  entry("reports.clients.view", "reporting", "View client reporting"),
  entry("reports.assets.view", "reporting", "View asset reporting"),
  entry("reports.networks.view", "reporting", "View network reporting"),
  entry("reports.employees.view", "reporting", "View employee reporting"),
  entry("reports.attendance.view", "reporting", "View attendance reporting"),
  entry("reports.projects.view", "reporting", "View project reporting"),
  entry("reports.finance.view", "reporting", "View operational finance reporting"),
  entry("reports.knowledge.view", "reporting", "View knowledge reporting"),
  entry("reports.security.view", "reporting", "View restricted security reporting"),
  entry("reports.audit.view", "reporting", "View reporting audit activity"),
  entry("reports.custom.create", "reporting", "Create controlled custom reports"),
  entry("reports.share", "reporting", "Share authorised reports"),
  entry("reports.schedule", "reporting", "Schedule authorised reports"),
  entry("reports.export", "reporting", "Export authorised reports"),
  entry("reports.manage", "reporting", "Manage reporting definitions and jobs"),
  entry("reports.kpis.manage", "reporting", "Manage KPI definitions"),
  entry("reports.sensitive_fields.view", "reporting", "View sensitive reporting fields"),
];

export const permissionGroups = Array.from(new Set(permissionCatalog.map((item) => item.group)));
