import "server-only";

import { randomUUID } from "node:crypto";
import { collectionNames } from "@/lib/collections";
import { firestoreAdmin } from "@/lib/db";
import { env } from "@/lib/env";
import { currentUser } from "@/lib/auth";
import { hasPermission, type CurrentUser } from "@/lib/permissions";
import { freshnessState, kpiDefinitions, percentage, percentageChange, periodKey, reportAreaLabels, reportAreas, resolveReportDateRange, type ReportArea, type ReportDateRange } from "@/lib/reporting-utils";
import { reportingFilterSchema } from "@/lib/validators-reporting";

export const reportingWorkspaceId = env.DEFAULT_WORKSPACE_ID;

export type ReportMetric = { key: string; label: string; value: number | null; previousValue?: number | null; change?: number | null; unit?: string; definitionKey?: string; source?: string[]; href?: string; tone?: "success" | "warning" | "danger" | "info" | "outline" };
export type ReportRow = { label: string; value: number; href?: string; meta?: string };
export type ReportResult = { area: ReportArea; label: string; range: ReportDateRange; metrics: ReportMetric[]; rows: ReportRow[]; trend: Array<{ label: string; value: number }>; generatedAt: Date; dataLastUpdated: Date | null; aggregationLastCompleted: Date | null; freshness: "CURRENT" | "STALE"; calculationVersions: number[]; notes: string[] };

const permissionByArea: Record<ReportArea, string> = {
  executive: "reports.executive.view", "service-desk": "reports.service_desk.view", clients: "reports.clients.view", assets: "reports.assets.view", networks: "reports.networks.view", employees: "reports.employees.view", attendance: "reports.attendance.view", projects: "reports.projects.view", finance: "reports.finance.view", knowledge: "reports.knowledge.view", security: "reports.security.view",
};

export function reportPermission(area: ReportArea) { return permissionByArea[area]; }
export function canViewReportArea(actor: CurrentUser | null | undefined, area: ReportArea) { return Boolean(actor && (hasPermission(actor, permissionByArea[area]) || hasPermission(actor, "reports.manage"))); }

function dateValue(value: unknown): any { if (!value) return null; if (value instanceof Date) return value; if (typeof value === "object" && value !== null && "toDate" in value && typeof (value as any).toDate === "function") return (value as any).toDate() as Date; const date = new Date(String(value)); return Number.isFinite(date.getTime()) ? date : null; }
function addWhere(query: any, field: string, operator: FirebaseFirestore.WhereFilterOp, value: unknown) { return query.where(field, operator, value); }

async function countRecords(collection: string, clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = []) {
  let query: any = firestoreAdmin.collection(collection);
  for (const [field, operator, value] of clauses) query = addWhere(query, field, operator, value);
  try { return Number((await query.count().get()).data().count ?? 0); } catch { return (await query.limit(10000).get()).size; }
}

async function readRecords(collection: string, clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = [], limit = 10000) {
  let query: any = firestoreAdmin.collection(collection);
  for (const [field, operator, value] of clauses) query = addWhere(query, field, operator, value);
  return (await query.limit(limit).get()).docs.map((document: any) => ({ id: document.id, ...document.data() }));
}

async function groupRecords(collection: string, field: string, clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = [], limit = 10000) {
  const records = await readRecords(collection, clauses, limit); const groups = new Map<string, number>();
  for (const record of records) { const key = String(record[field] ?? "Unassigned"); groups.set(key, (groups.get(key) ?? 0) + 1); }
  return Array.from(groups.entries()).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([label, value]) => ({ label, value }));
}

async function latestUpdated(collections: string[], clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = []) {
  const values = await Promise.all(collections.map((collection) => readRecords(collection, [["workspaceId", "==", reportingWorkspaceId], ...clauses], 250)));
  const dates = values.flat().map((record) => dateValue(record.updatedAt ?? record.createdAt)).filter((date): date is Date => Boolean(date));
  return dates.sort((a, b) => b.getTime() - a.getTime())[0] ?? null;
}

async function latestSnapshot(area: ReportArea) {
  try { const snapshot = await firestoreAdmin.collection(collectionNames.reportingSnapshots).where("workspaceId", "==", reportingWorkspaceId).where("area", "==", area).orderBy("generatedAt", "desc").limit(1).get(); return snapshot.empty ? null : dateValue(snapshot.docs[0].data().generatedAt); } catch { return null; }
}

function clausesForPeriod(range: ReportDateRange, dateField = "createdAt", clientId?: string) {
  const clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = [["workspaceId", "==", reportingWorkspaceId], [dateField, ">=", range.start], [dateField, "<", range.end]];
  if (clientId) clauses.push(["clientId", "==", clientId]);
  return clauses;
}

async function periodCount(collection: string, range: ReportDateRange, dateField = "createdAt", clientId?: string) { return countRecords(collection, clausesForPeriod(range, dateField, clientId)); }
async function currentCount(collection: string, clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = []) { return countRecords(collection, [["workspaceId", "==", reportingWorkspaceId], ...clauses]); }
async function periodCountScoped(collection: string, range: ReportDateRange, dateField = "createdAt", clientId?: string) { return periodCount(collection, range, dateField, clientId); }
function metric(key: string, label: string, value: number | null, previousValue: number | null, unit = "number", href?: string, definitionKey?: string): ReportMetric { return { key, label, value, previousValue, change: value == null || previousValue == null ? null : percentageChange(value, previousValue), unit, href, definitionKey }; }

export function parseReportingFilters(params: Record<string, string | string[] | undefined>) {
  const get = (key: string) => { const value = params[key]; return Array.isArray(value) ? value[0] : value; };
  const parsed = reportingFilterSchema.safeParse({ preset: get("preset") || "this-month", start: get("start") || "", end: get("end") || "", clientId: get("clientId") || "", siteId: get("siteId") || "", departmentId: get("departmentId") || "", status: get("status") || "", priority: get("priority") || "", comparison: get("comparison") !== "false" });
  const input = parsed.success ? parsed.data : reportingFilterSchema.parse({});
  return { ...input, range: resolveReportDateRange(input.preset, input.start || undefined, input.end || undefined, new Date(), env.DEFAULT_TIMEZONE) };
}

async function serviceDeskReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> {
  const scope: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = [["workspaceId", "==", reportingWorkspaceId]]; if (filters.clientId) scope.push(["clientId", "==", filters.clientId]); if (filters.status) scope.push(["status", "==", filters.status]); if (filters.priority) scope.push(["priority", "==", filters.priority]);
  const [open, critical, created, previousCreated, resolved, previousResolved, breached, groups, updated] = await Promise.all([
    currentCount("tickets", [...scope.slice(1), ["status", "not-in", ["RESOLVED", "CLOSED"]]]), currentCount("tickets", [...scope.slice(1), ["priority", "==", "URGENT"]]), periodCountScoped("tickets", filters.range, "createdAt", filters.clientId), periodCountScoped("tickets", { ...filters.range, start: filters.range.comparisonStart, end: filters.range.comparisonEnd }, "createdAt", filters.clientId), periodCountScoped("tickets", filters.range, "resolvedAt", filters.clientId), periodCountScoped("tickets", { ...filters.range, start: filters.range.comparisonStart, end: filters.range.comparisonEnd }, "resolvedAt", filters.clientId), currentCount("tickets", [...scope.slice(1), ["slaBreached", "==", true]]), groupRecords("tickets", "status", scope), latestUpdated(["tickets"]),
  ]);
  const trendRecords = await readRecords("tickets", clausesForPeriod(filters.range)); const days = new Map<string, number>(); for (const record of trendRecords) { const date = dateValue(record.createdAt); if (date) { const key = periodKey(date); days.set(key, (days.get(key) ?? 0) + 1); } }
  return { metrics: [metric("open", "Open tickets", open, null, "number", "/tickets", "tickets.open"), metric("critical", "Critical tickets", critical, null, "number", "/tickets?priority=URGENT"), metric("created", "Tickets created", created, previousCreated, "number", "/tickets"), metric("resolved", "Tickets resolved", resolved, previousResolved, "number", "/tickets?status=RESOLVED"), metric("sla-breaches", "SLA breaches", breached, null, "number", "/tickets?breached=true")], rows: groups.map((row) => ({ ...row, href: `/tickets?status=${encodeURIComponent(row.label)}` })), trend: Array.from(days.entries()).sort().map(([label, value]) => ({ label, value })), dataLastUpdated: updated, notes: ["Ticket time metrics are not inferred here because the current ticket model does not expose a single consistent business-hours or paused-SLA duration field.", "Created and resolved counts use the selected date range and calendar timestamps."] };
}

async function clientsReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> {
  const [active, onboarding, former, created, previousCreated, groups, updated, expiring] = await Promise.all([currentCount("clients", [["status", "==", "ACTIVE"]]), currentCount("clients", [["status", "==", "ONBOARDING"]]), currentCount("clients", [["status", "==", "FORMER"]]), periodCountScoped("clients", filters.range), periodCountScoped("clients", { ...filters.range, start: filters.range.comparisonStart, end: filters.range.comparisonEnd }), groupRecords("clients", "status", [["workspaceId", "==", reportingWorkspaceId]]), latestUpdated(["clients"]), currentCount("contracts", [["endDate", "<=", new Date(Date.now() + 60 * 86400000)], ["status", "not-in", ["ENDED", "CANCELLED"]]])]); return { metrics: [metric("active", "Active clients", active, null, "number", "/clients"), metric("onboarding", "Clients onboarding", onboarding, null, "number", "/clients?status=ONBOARDING"), metric("expiring-contracts", "Contracts expiring", expiring, null, "number", "/clients"), metric("new", "New clients", created, previousCreated, "number", "/clients/new")], rows: groups.map((row) => ({ ...row, href: `/clients?status=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Client health is shown from the authoritative client status and existing CRM health rules; no undisclosed composite score is created."] };
}

async function assetsReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const scope: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = filters.clientId ? [["clientId", "==", filters.clientId]] : []; const [managed, healthy, atRisk, repair, unassigned, expiring, groups, updated] = await Promise.all([currentCount("assets", scope), currentCount("assets", [...scope, ["healthState", "==", "HEALTHY"]]), currentCount("assets", [...scope, ["healthState", "in", ["AT_RISK", "CRITICAL"]]]), currentCount("assets", [...scope, ["status", "==", "UNDER_REPAIR"]]), currentCount("assets", [...scope, ["assignedUserId", "==", null]]), currentCount("assetWarranties", filters.clientId ? [["clientId", "==", filters.clientId], ["expiryDate", "<=", new Date(Date.now() + 60 * 86400000)]] : [["expiryDate", "<=", new Date(Date.now() + 60 * 86400000)]]), groupRecords("assets", "status", [["workspaceId", "==", reportingWorkspaceId], ...scope]), latestUpdated(["assets"])]); return { metrics: [metric("managed", "Managed assets", managed, null, "number", "/assets"), metric("healthy", "Healthy assets", healthy, null, "number", "/assets?healthState=HEALTHY"), metric("at-risk", "At-risk assets", atRisk, null, "number", "/assets?healthState=AT_RISK"), metric("repair", "Assets under repair", repair, null, "number", "/assets?status=UNDER_REPAIR"), metric("unassigned", "Unassigned assets", unassigned, null, "number", "/assets"), metric("warranty", "Warranties expiring", expiring, null, "number", "/assets")], rows: groups.map((row) => ({ ...row, href: `/assets?status=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Purchase values, licence details and security fields are excluded unless a separate sensitive reporting permission is added."] }; }

async function networksReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const scope: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = filters.clientId ? [["clientId", "==", filters.clientId]] : []; const [managed, online, offline, compliant, criticalAlerts, lowDisk, groups, updated] = await Promise.all([currentCount("endpoints", scope), currentCount("endpoints", [...scope, ["checkInState", "==", "ONLINE"]]), currentCount("endpoints", [...scope, ["checkInState", "==", "OFFLINE"]]), currentCount("endpoints", [...scope, ["complianceState", "==", "COMPLIANT"]]), currentCount("networkAlerts", [["status", "==", "OPEN"], ["severity", "==", "CRITICAL"]]), currentCount("endpoints", [...scope, ["diskState", "==", "WARNING"]]), groupRecords("endpoints", "healthState", [["workspaceId", "==", reportingWorkspaceId], ...scope]), latestUpdated(["endpoints", "networkAlerts"])]); return { metrics: [metric("managed", "Managed endpoints", managed, null, "number", "/network/endpoints"), metric("online", "Online endpoints", online, null, "number", "/network/endpoints?checkInState=ONLINE"), metric("offline", "Offline endpoints", offline, null, "number", "/network/endpoints?checkInState=OFFLINE"), metric("compliance", "Endpoint compliance", percentage(compliant, managed), null, "percent", "/network/endpoints", "endpoints.compliance"), metric("critical-alerts", "Critical alerts", criticalAlerts, null, "number", "/network/alerts"), metric("low-disk", "Low-disk devices", lowDisk, null, "number", "/network/endpoints")], rows: groups.map((row) => ({ ...row, href: `/network/endpoints?healthState=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Raw endpoint audits and private network details are not included in report payloads."] }; }

async function employeesReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const scope: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = filters.departmentId ? [["departmentId", "==", filters.departmentId]] : []; const [active, onboarding, offboarding, contractExpiry, trainingDue, qualificationExpiry, groups, updated] = await Promise.all([currentCount("employees", [...scope, ["status", "==", "ACTIVE"]]), currentCount("employees", [...scope, ["lifecycleState", "==", "ONBOARDING"]]), currentCount("employees", [...scope, ["lifecycleState", "==", "OFFBOARDING"]]), currentCount("employeeContracts", [["endDate", "<=", new Date(Date.now() + 60 * 86400000)]]), currentCount("employeeTraining", [["expiryDate", "<=", new Date(Date.now() + 60 * 86400000)]]), currentCount("employeeQualifications", [["expiryDate", "<=", new Date(Date.now() + 60 * 86400000)]]), groupRecords("employees", "departmentId", [["workspaceId", "==", reportingWorkspaceId], ...scope]), latestUpdated(["employees", "employeeContracts", "employeeTraining", "employeeQualifications"])]); return { metrics: [metric("active", "Active employees", active, null, "number", "/employees"), metric("onboarding", "Employees onboarding", onboarding, null, "number", "/employees/onboarding"), metric("offboarding", "Employees offboarding", offboarding, null, "number", "/employees/offboarding"), metric("contract-expiry", "Contract expiries", contractExpiry, null, "number", "/employees"), metric("training-due", "Training due", trainingDue, null, "number", "/employees"), metric("qualification-expiry", "Qualification expiries", qualificationExpiry, null, "number", "/employees")], rows: groups.map((row) => ({ ...row, href: `/employees?departmentId=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Employee identities, contact details, compensation, emergency contacts, contracts and confidential notes are excluded from ordinary reports.", "No productivity ranking or PulseOne telemetry is used."] }; }

async function attendanceReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const [events, exceptions, approvals, overtime, groups, updated] = await Promise.all([periodCountScoped("attendanceEvents", filters.range), currentCount("attendanceExceptions", [["status", "==", "OPEN"]]), currentCount("attendanceApprovals", [["status", "==", "PENDING"]]), currentCount("overtimeRequests", [["status", "==", "PENDING"]]), groupRecords("attendanceEvents", "eventType", clausesForPeriod(filters.range)), latestUpdated(["attendanceEvents", "attendanceExceptions", "attendanceApprovals"])]); return { metrics: [metric("events", "Clock events", events, null, "number", "/attendance"), metric("exceptions", "Open exceptions", exceptions, null, "number", "/attendance"), metric("approvals", "Pending approvals", approvals, null, "number", "/attendance"), metric("overtime", "Pending overtime", overtime, null, "number", "/attendance/reports")], rows: groups.map((row) => ({ ...row, href: "/attendance/reports" })), trend: [], dataLastUpdated: updated, notes: ["Attendance reporting remains separate from project time and excludes idle tracking, applications, websites, screenshots, keystrokes and productivity scoring."] }; }

async function projectsReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const scope: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = filters.clientId ? [["clientId", "==", filters.clientId]] : []; const [active, atRisk, overdueTasks, blockedTasks, missedMilestones, hours, billableHours, groups, updated] = await Promise.all([currentCount("projects", [...scope, ["status", "in", ["ACTIVE", "APPROVED", "ON_HOLD"]]]), currentCount("projects", [...scope, ["healthState", "in", ["AT_RISK", "CRITICAL"]]]), currentCount("projectTasks", [["status", "not-in", ["COMPLETED", "CANCELLED"]], ["dueDate", "<", new Date()]]), currentCount("projectTasks", [["status", "==", "BLOCKED"]]), currentCount("projectMilestones", [["status", "==", "MISSED"]]), sumField("projectTimeEntries", "durationMinutes", [["workspaceId", "==", reportingWorkspaceId], ...scope]), sumField("projectTimeEntries", "durationMinutes", [["workspaceId", "==", reportingWorkspaceId], ...scope, ["billable", "==", true]]), groupRecords("projects", "status", [["workspaceId", "==", reportingWorkspaceId], ...scope]), latestUpdated(["projects", "projectTasks", "projectMilestones", "projectTimeEntries"])]); return { metrics: [metric("active", "Active projects", active, null, "number", "/projects"), metric("at-risk", "At-risk projects", atRisk, null, "number", "/projects"), metric("overdue", "Overdue tasks", overdueTasks, null, "number", "/projects"), metric("blocked", "Blocked tasks", blockedTasks, null, "number", "/projects"), metric("missed", "Missed milestones", missedMilestones, null, "number", "/projects"), metric("hours", "Recorded project hours", hours / 60, null, "number", "/projects"), metric("billable-hours", "Billable project hours", billableHours / 60, null, "number", "/projects")], rows: groups.map((row) => ({ ...row, href: `/projects?status=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Project time uses recorded durationMinutes. Attendance events are not included.", "Internal costs, margins and restricted financial fields are omitted from client-visible analytics."] }; }

async function financeReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const invoices = await readRecords("invoices", [["workspaceId", "==", reportingWorkspaceId]], env.REPORTING_EXPORT_MAX_ROWS); const activeInvoices = invoices.filter((invoice) => !["DRAFT", "VOID", "CANCELLED"].includes(String(invoice.status))); const outstanding = activeInvoices.reduce((sum, invoice) => sum + Number(invoice.totalMinorUnits ?? 0) - Number(invoice.amountPaidMinorUnits ?? 0), 0); const overdue = activeInvoices.filter((invoice) => dateValue(invoice.dueDate)?.getTime() < Date.now() && Number(invoice.totalMinorUnits ?? 0) > Number(invoice.amountPaidMinorUnits ?? 0)); const payments = await sumField("payments", "amountMinorUnits", [["workspaceId", "==", reportingWorkspaceId], ...clausesForPeriod(filters.range).filter(([field]) => field === "createdAt")]); const [quotes, quoteAccepted, expensesPending, purchaseApprovals, groups, updated] = await Promise.all([currentCount("quotes", [["status", "==", "DRAFT"]]), currentCount("quotes", [["status", "in", ["ACCEPTED", "APPROVED"]]]), currentCount("expenses", [["status", "==", "PENDING_APPROVAL"]]), currentCount("purchaseOrders", [["status", "==", "PENDING_APPROVAL"]]), groupRecords("invoices", "status", [["workspaceId", "==", reportingWorkspaceId]]), latestUpdated(["invoices", "payments", "quotes", "expenses", "purchaseOrders"])]); return { metrics: [metric("outstanding", "Outstanding invoices", outstanding, null, "minor currency units", "/finance/invoices", "finance.outstanding_invoices"), metric("overdue", "Overdue invoices", overdue.length, null, "number", "/finance/invoices"), metric("payments", "Payments received", payments, null, "minor currency units", "/finance/payments"), metric("quotes", "Quotes to approve", quotes, null, "number", "/finance/quotes"), metric("accepted", "Accepted quotes", quoteAccepted, null, "number", "/finance/quotes"), metric("expenses", "Pending expenses", expensesPending, null, "number", "/finance/expenses"), metric("purchase-orders", "Purchase orders awaiting approval", purchaseApprovals, null, "number", "/finance/purchase-orders")], rows: groups.map((row) => ({ ...row, href: `/finance/invoices?status=${encodeURIComponent(row.label)}` })), trend: [], dataLastUpdated: updated, notes: ["Amounts use Phase 10 integer minor-unit fields and authoritative amountPaidMinorUnits.", "This is operational finance reporting, not a certified financial statement, accounting, SARS or tax report."] }; }

async function knowledgeReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const [published, drafts, review, expired, feedback, helpful, noResults, acknowledgements, brokenLinks, groups, updated] = await Promise.all([currentCount("knowledgeArticles", [["status", "==", "PUBLISHED"]]), currentCount("knowledgeArticles", [["status", "==", "DRAFT"]]), currentCount("knowledgeArticles", [["status", "==", "IN_REVIEW"]]), currentCount("knowledgeArticles", [["status", "==", "EXPIRED"]]), periodCountScoped("knowledgeFeedback", filters.range), periodCountScoped("knowledgeFeedback", filters.range, "createdAt"), currentCount("knowledgeSearchEvents", [["noResult", "==", true]]), currentCount("policyAcknowledgements", [["status", "==", "OUTSTANDING"]]), currentCount("knowledgeLinkChecks", [["status", "in", ["BROKEN", "UNREACHABLE"]]]), groupRecords("knowledgeArticles", "status", [["workspaceId", "==", reportingWorkspaceId]]), latestUpdated(["knowledgeArticles", "knowledgeFeedback", "knowledgeSearchEvents"])]); const feedbackRecords = await readRecords("knowledgeFeedback", clausesForPeriod(filters.range)); const positive = feedbackRecords.filter((record) => record.type === "HELPFUL").length; const negative = feedbackRecords.filter((record) => record.type === "NOT_HELPFUL").length; return { metrics: [metric("published", "Published articles", published, null, "number", "/knowledge"), metric("drafts", "Draft articles", drafts, null, "number", "/knowledge"), metric("review", "Awaiting review", review, null, "number", "/knowledge"), metric("expired", "Expired articles", expired, null, "number", "/knowledge"), metric("helpfulness", "Article helpfulness", percentage(positive, positive + negative), null, "percent", "/knowledge/analytics", "knowledge.helpfulness"), metric("no-results", "Searches with no results", noResults, null, "number", "/knowledge/analytics"), metric("acknowledgements", "Outstanding acknowledgements", acknowledgements, null, "number", "/knowledge/policies"), metric("broken-links", "Broken links", brokenLinks, null, "number", "/knowledge/analytics")], rows: groups.map((row) => ({ ...row, href: "/knowledge" })), trend: [], dataLastUpdated: updated, notes: ["Feedback aggregates exclude individual browsing history and do not expose user-level reading behaviour."] }; }

async function securityReport(filters: ReturnType<typeof parseReportingFilters>): Promise<Pick<ReportResult, "metrics" | "rows" | "trend" | "dataLastUpdated" | "notes">> { const [audit, exports, roleChanges, endpointEnrolments, groups, updated] = await Promise.all([periodCountScoped("auditLogs", filters.range), periodCountScoped("financialExports", filters.range), periodCountScoped("auditLogs", filters.range), periodCountScoped("endpointEnrollments", filters.range), groupRecords("auditLogs", "action", clausesForPeriod(filters.range), 10000), latestUpdated(["auditLogs", "financialExports", "endpointEnrollments"])]); return { metrics: [metric("audit", "Audit activity", audit, null, "number", "/administration/audit-logs"), metric("exports", "Export activity", exports, null, "number", "/administration/audit-logs"), metric("role-changes", "Role and permission activity", roleChanges, null, "number", "/administration/audit-logs"), metric("enrolments", "Endpoint enrolments", endpointEnrolments, null, "number", "/network/enrolments")], rows: groups.map((row) => ({ ...row, href: "/administration/audit-logs" })), trend: [], dataLastUpdated: updated, notes: ["Authentication tokens, credentials and secret values are never included.", "Security reporting requires the restricted reports.security.view permission."] }; }

async function sumField(collection: string, field: string, clauses: Array<[string, FirebaseFirestore.WhereFilterOp, unknown]> = []) { const records = await readRecords(collection, clauses, env.REPORTING_EXPORT_MAX_ROWS); return records.reduce((sum, record) => sum + Number(record[field] ?? 0), 0); }

async function buildAreaReport(area: ReportArea, filters: ReturnType<typeof parseReportingFilters>) {
  if (area === "service-desk") return serviceDeskReport(filters); if (area === "clients") return clientsReport(filters); if (area === "assets") return assetsReport(filters); if (area === "networks") return networksReport(filters); if (area === "employees") return employeesReport(filters); if (area === "attendance") return attendanceReport(filters); if (area === "projects") return projectsReport(filters); if (area === "finance") return financeReport(filters); if (area === "knowledge") return knowledgeReport(filters); if (area === "security") return securityReport(filters); const reports = await Promise.all(reportAreas.filter((item) => item !== "executive").map((item) => buildAreaReport(item, filters))); return { metrics: reports.flatMap((report) => report.metrics).slice(0, 16), rows: reports.flatMap((report) => report.rows).slice(0, 16), trend: [], dataLastUpdated: reports.map((report) => report.dataLastUpdated).filter((date): date is Date => Boolean(date)).sort((a, b) => b.getTime() - a.getTime())[0] ?? null, notes: ["Executive reporting displays independent operational KPIs. It intentionally does not combine them into a misleading overall score."] }; }

export async function getReport(area: ReportArea, rawFilters: Record<string, string | string[] | undefined> = {}) {
  const actor = await currentUser(); if (!canViewReportArea(actor, area)) throw new Error("You do not have permission to view this report."); const filters = parseReportingFilters(rawFilters); const generatedAt = new Date(); const report = await buildAreaReport(area, filters); const snapshotAt = await latestSnapshot(area); const calculationVersions = kpiDefinitions.filter((definition) => definition.requiredPermission === permissionByArea[area] || area === "executive").map((definition) => definition.version); return { area, label: reportAreaLabels[area], range: filters.range, ...report, generatedAt, aggregationLastCompleted: snapshotAt, freshness: freshnessState(snapshotAt, env.REPORTING_STALE_AFTER_MINUTES), calculationVersions: calculationVersions.length ? calculationVersions : [1] } satisfies ReportResult;
}

export async function getReportingHome() { const actor = await currentUser(); if (!actor || !hasPermission(actor, "reports.view")) throw new Error("You do not have permission to view reports."); const [saved, schedules, executions, exports, definitions, kpis] = await Promise.all([firestoreAdmin.collection(collectionNames.savedReports).where("workspaceId", "==", reportingWorkspaceId).where("ownerId", "==", actor.id).limit(50).get(), firestoreAdmin.collection(collectionNames.reportSchedules).where("workspaceId", "==", reportingWorkspaceId).where("ownerId", "==", actor.id).limit(50).get(), firestoreAdmin.collection(collectionNames.reportExecutions).where("workspaceId", "==", reportingWorkspaceId).where("ownerId", "==", actor.id).limit(50).get(), firestoreAdmin.collection(collectionNames.reportExports).where("workspaceId", "==", reportingWorkspaceId).where("requestedBy", "==", actor.id).limit(50).get(), firestoreAdmin.collection(collectionNames.reportDefinitions).where("workspaceId", "==", reportingWorkspaceId).where("active", "==", true).limit(100).get(), firestoreAdmin.collection(collectionNames.kpiDefinitions).where("workspaceId", "==", reportingWorkspaceId).limit(100).get()]); return { saved: saved.docs.map((doc) => ({ id: doc.id, ...doc.data() })), schedules: schedules.docs.map((doc) => ({ id: doc.id, ...doc.data() })), executions: executions.docs.map((doc) => ({ id: doc.id, ...doc.data() })), exports: exports.docs.map((doc) => ({ id: doc.id, ...doc.data() })), definitions: definitions.docs.map((doc) => ({ id: doc.id, ...doc.data() })), kpis: kpis.empty ? kpiDefinitions : kpis.docs.map((doc) => ({ id: doc.id, ...doc.data() })) }; }
export async function getSharedReports(actorId: string) { const snapshot = await firestoreAdmin.collection(collectionNames.savedReports).where("workspaceId", "==", reportingWorkspaceId).where("sharedUserIds", "array-contains", actorId).limit(50).get(); return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })); }

export async function requireReportingPermission(permission: string) { const actor = await currentUser(); if (!actor || !hasPermission(actor, permission)) throw new Error("You do not have permission to perform this reporting action."); return actor; }
export function reportAreaList() { return reportAreas.map((area) => ({ area, label: reportAreaLabels[area], permission: permissionByArea[area] })); }
export function controlledDatasetFields(dataset: string) { const fields: Record<string, string[]> = { tickets: ["status", "priority", "categoryId", "clientId", "createdAt", "resolvedAt"], clients: ["status", "createdAt", "updatedAt"], assets: ["status", "healthState", "clientId", "siteId", "createdAt", "updatedAt"], endpoints: ["healthState", "complianceState", "checkInState", "clientId", "siteId", "windowsVersion"], employees: ["status", "departmentId", "employmentType", "createdAt"], attendance: ["eventType", "status", "workMode", "serverTimestamp"], projects: ["status", "healthState", "clientId", "createdAt"], finance: ["status", "clientId", "dueDate", "invoiceDate"], knowledge: ["status", "visibility", "articleType", "createdAt"], security: ["action", "entityType", "createdAt"] }; return fields[dataset] ?? []; }
export function controlledDatasetMetrics(dataset: string) { const metrics: Record<string, string[]> = { tickets: ["count", "open", "critical"], clients: ["count", "active", "onboarding"], assets: ["count", "healthy", "atRisk"], endpoints: ["count", "online", "offline", "compliance"], employees: ["count", "active"], attendance: ["events", "exceptions"], projects: ["count", "active", "atRisk"], finance: ["outstandingMinorUnits", "overdueCount"], knowledge: ["published", "review", "helpfulness"], security: ["auditEvents", "exportEvents"] }; return metrics[dataset] ?? []; }
export const reportId = () => randomUUID();
