"use server";

import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { collectionNames } from "@/lib/collections";
import { firestoreAdmin } from "@/lib/db";
import { currentUser } from "@/lib/auth";
import { hasPermission } from "@/lib/permissions";
import { aiWorkspaceId, aiPromptVersion, createAiConversation, requireAiAccess, runAiRequest } from "@/lib/ai";
import { redactText } from "@/lib/ai-redaction";
import { aiFeedbackSchema, aiMessageSchema, aiProposalSchema, aiSettingsSchema } from "@/lib/validators-ai";
import { env } from "@/lib/env";

function value(formData: FormData, key: string) { return String(formData.get(key) ?? "").trim(); }
function fail(message: string, conversationId?: string): never { redirect(`/ai?error=${encodeURIComponent(message)}${conversationId ? `&conversation=${encodeURIComponent(conversationId)}` : ""}`); }
async function actor() { const user = await currentUser(); if (!user) redirect("/login"); return user; }
async function ownedConversation(userId: string, id: string) { const document = await firestoreAdmin.collection(collectionNames.aiConversations).doc(id).get(); if (!document.exists || document.data()?.workspaceId !== aiWorkspaceId || document.data()?.userId !== userId) throw new Error("Conversation not found."); return document; }

export async function sendAiMessageAction(formData: FormData) {
  const user = await actor();
  const raw = aiMessageSchema.safeParse({ conversationId: value(formData, "conversationId"), prompt: value(formData, "prompt"), contextModule: value(formData, "contextModule") || undefined, contextType: value(formData, "contextType") || undefined, contextId: value(formData, "contextId") || undefined });
  if (!raw.success) fail(raw.error.issues[0]?.message ?? "Please enter a valid AI request.");
  const input = raw.data;
  try {
    await requireAiAccess(user, input.contextModule);
    const conversationId = input.conversationId || await createAiConversation(user, { module: input.contextModule, type: input.contextType, id: input.contextId });
    const conversation = await ownedConversation(user.id, conversationId);
    const now = new Date();
    const userMessageId = randomUUID();
    await firestoreAdmin.collection(collectionNames.aiMessages).doc(userMessageId).set({ id: userMessageId, workspaceId: aiWorkspaceId, conversationId, userId: user.id, role: "USER", content: redactText(input.prompt).slice(0, env.AI_MAX_PROMPT_CHARS), createdAt: now, updatedAt: now });
    const result = await runAiRequest(user, input.prompt, { module: input.contextModule ?? conversation.data()?.contextModule ?? undefined, type: input.contextType ?? conversation.data()?.contextType ?? undefined, id: input.contextId ?? conversation.data()?.contextRecordId ?? undefined });
    const assistantId = randomUUID();
    await firestoreAdmin.collection(collectionNames.aiMessages).doc(assistantId).set({ id: assistantId, workspaceId: aiWorkspaceId, conversationId, userId: user.id, role: "ASSISTANT", content: result.text.slice(0, 50000), provider: result.provider, modelIdentifier: result.modelIdentifier, promptVersion: aiPromptVersion, sourceRefs: result.sources, toolCalls: result.toolCalls, redacted: result.redacted, suspicious: result.suspicious, usage: result.usage, createdAt: new Date(), updatedAt: new Date() });
    if (result.proposal && hasPermission(user, "ai.actions.propose")) { const proposalId = randomUUID(); await firestoreAdmin.collection(collectionNames.aiActionProposals).doc(proposalId).set({ id: proposalId, workspaceId: aiWorkspaceId, userId: user.id, conversationId, messageId: assistantId, actionType: result.proposal.type, title: result.proposal.title, payload: result.proposal.payload, status: "PROPOSED", requiresConfirmation: true, createdAt: new Date(), updatedAt: new Date(), expiresAt: new Date(Date.now() + 7 * 86400000) }); }
    await conversation.ref.set({ title: conversation.data()?.title === "New AI conversation" ? input.prompt.slice(0, 80) : conversation.data()?.title, updatedAt: new Date() }, { merge: true });
    revalidatePath("/ai");
    redirect(`/ai?conversation=${encodeURIComponent(conversationId)}`);
  } catch (error: any) { if (String(error?.digest ?? "").startsWith("NEXT_REDIRECT")) throw error; fail(error?.message ?? "The AI request could not be completed.", input.conversationId || undefined); }
}

export async function startAiConversationAction(formData: FormData) { const user = await actor(); try { const id = await createAiConversation(user, { module: value(formData, "contextModule") || undefined, type: value(formData, "contextType") || undefined, id: value(formData, "contextId") || undefined }); redirect(`/ai?conversation=${encodeURIComponent(id)}`); } catch (error: any) { if (String(error?.digest ?? "").startsWith("NEXT_REDIRECT")) throw error; fail(error?.message ?? "Unable to start an AI conversation."); } }

export async function submitAiFeedbackAction(formData: FormData) { const user = await actor(); const input = aiFeedbackSchema.parse({ messageId: value(formData, "messageId"), rating: value(formData, "rating"), comment: value(formData, "comment") }); const message = await firestoreAdmin.collection(collectionNames.aiMessages).doc(input.messageId).get(); if (!message.exists) fail("Message not found."); await ownedConversation(user.id, String(message.data()?.conversationId)); const id = randomUUID(); await firestoreAdmin.collection(collectionNames.aiFeedback).doc(id).set({ id, workspaceId: aiWorkspaceId, userId: user.id, conversationId: message.data()?.conversationId, messageId: input.messageId, rating: input.rating, comment: redactText(input.comment ?? ""), createdAt: new Date() }); redirect(`/ai?conversation=${encodeURIComponent(String(message.data()?.conversationId))}`); }

export async function confirmAiActionAction(formData: FormData) { const user = await actor(); const input = aiProposalSchema.parse({ proposalId: value(formData, "proposalId") }); if (!hasPermission(user, "ai.actions.confirm")) fail("You do not have permission to confirm AI actions."); const proposal = await firestoreAdmin.collection(collectionNames.aiActionProposals).doc(input.proposalId).get(); if (!proposal.exists || proposal.data()?.workspaceId !== aiWorkspaceId || proposal.data()?.userId !== user.id) fail("AI proposal not found."); const data = proposal.data()!; if (data.status !== "PROPOSED" || data.expiresAt?.toDate?.() < new Date()) fail("This AI proposal is no longer available.", data.conversationId); const allowed = new Set(["DRAFT_TICKET_REPLY", "DRAFT_KNOWLEDGE_ARTICLE", "DRAFT_REPORT"]); if (!allowed.has(String(data.actionType))) fail("That AI action is not permitted.", data.conversationId); const executionId = randomUUID(); await firestoreAdmin.runTransaction(async (transaction) => { const fresh = await transaction.get(proposal.ref); if (!fresh.exists || fresh.data()?.status !== "PROPOSED") throw new Error("This AI proposal has already been confirmed."); transaction.update(proposal.ref, { status: "CONFIRMED", confirmedAt: new Date(), confirmedBy: user.id, updatedAt: new Date() }); transaction.create(firestoreAdmin.collection(collectionNames.aiActionExecutions).doc(executionId), { id: executionId, workspaceId: aiWorkspaceId, userId: user.id, conversationId: data.conversationId, proposalId: input.proposalId, actionType: data.actionType, payload: data.payload, status: "PREPARED", result: "Draft prepared for manual review. No external communication or authoritative record change was performed.", promptVersion: aiPromptVersion, createdAt: new Date(), updatedAt: new Date() }); transaction.create(firestoreAdmin.collection(collectionNames.aiAuditEvents).doc(executionId), { id: executionId, workspaceId: aiWorkspaceId, userId: user.id, feature: "actions", contextType: "conversation", contextRecordId: data.conversationId, requestReference: data.messageId, proposedAction: { type: data.actionType, proposalId: input.proposalId }, userConfirmation: true, finalResult: "PREPARED", provider: "sourcehub", modelIdentifier: "server-action", promptVersion: aiPromptVersion, status: "CONFIRMED", createdAt: new Date() }); }); redirect(`/ai?conversation=${encodeURIComponent(String(data.conversationId))}`); }

export async function archiveAiConversationAction(formData: FormData) { const user = await actor(); const id = value(formData, "conversationId"); await ownedConversation(user.id, id); await firestoreAdmin.collection(collectionNames.aiConversations).doc(id).set({ status: "ARCHIVED", archivedAt: new Date(), updatedAt: new Date() }, { merge: true }); revalidatePath("/ai"); redirect("/ai"); }
export async function deleteAiConversationAction(formData: FormData) { const user = await actor(); const id = value(formData, "conversationId"); await ownedConversation(user.id, id); const [messages, proposals] = await Promise.all([firestoreAdmin.collection(collectionNames.aiMessages).where("conversationId", "==", id).limit(400).get(), firestoreAdmin.collection(collectionNames.aiActionProposals).where("conversationId", "==", id).limit(100).get()]); const batch = firestoreAdmin.batch(); messages.docs.forEach((document) => batch.delete(document.ref)); proposals.docs.forEach((document) => batch.delete(document.ref)); batch.delete(firestoreAdmin.collection(collectionNames.aiConversations).doc(id)); await batch.commit(); revalidatePath("/ai"); redirect("/ai"); }

export async function saveAiSettingsAction(formData: FormData) { const user = await actor(); if (!hasPermission(user, "ai.settings.manage")) fail("You do not have permission to manage AI settings."); const input = aiSettingsSchema.parse({ enabled: formData.get("enabled") === "true", emergencyDisabled: formData.get("emergencyDisabled") === "true", allowedModules: value(formData, "allowedModules").split(",").map((item) => item.trim()).filter(Boolean), dailyRequestLimit: value(formData, "dailyRequestLimit"), monthlyRequestLimit: value(formData, "monthlyRequestLimit"), retentionDays: value(formData, "retentionDays") }); await firestoreAdmin.collection(collectionNames.aiSettings).doc(aiWorkspaceId).set({ id: aiWorkspaceId, workspaceId: aiWorkspaceId, ...input, updatedBy: user.id, updatedAt: new Date() }, { merge: true }); revalidatePath("/administration/ai"); redirect("/administration/ai?saved=1"); }
