"use server";

import { createHash, randomUUID } from "node:crypto";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { FieldValue } from "firebase-admin/firestore";

import { currentUser } from "@/lib/auth";
import { collectionNames } from "@/lib/collections";
import { firestoreAdmin, prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { logAudit } from "@/lib/audit";
import { calculateFinanceLines, defaultDueDate, documentHash, numberNextInTransaction } from "@/lib/finance";
import { buildFinancePdf } from "@/lib/finance-pdf";
import { parseDecimalToMinorUnits } from "@/lib/money";
import { savePrivateBinaryToStorage, buildFinanceStoragePath } from "@/lib/storage";
import { budgetSchema, clientBillingProfileSchema, expenseSchema, financeSettingsSchema, invoiceSchema, paymentAllocationSchema, paymentSchema, purchaseOrderSchema, quoteSchema, supplierSchema } from "@/lib/validators";

const workspaceId = env.DEFAULT_WORKSPACE_ID;
const value = (formData: FormData, name: string) => String(formData.get(name) ?? "");
const checked = (formData: FormData, name: string) => formData.get(name) === "true" || formData.get(name) === "on";
const ipAddress = () => headers().get("x-forwarded-for")?.split(",")[0]?.trim() ?? null;
function fail(path: string, message: string): never { redirect(`${path}?error=${encodeURIComponent(message)}`); }
async function actorFor(permission: string) { const actor = await currentUser(); if (!actor) redirect("/login"); if (!actor.permissions.includes(permission)) redirect("/access-denied"); return actor; }
function parseLines(formData: FormData) { try { return JSON.parse(value(formData, "linesJson")); } catch { return null; } }
async function clientFor(id: string, path: string) { const client = await prisma.client.findUnique({ where: { id } }); if (!client || client.workspaceId !== workspaceId) fail(path, "Selected client is not available."); return client; }
async function audit(actorId: string, action: string, entityType: string, entityId: string, newValues?: unknown) { await logAudit({ userId: actorId, action, entityType, entityId, newValues, ipAddress: ipAddress() }); }

export async function saveFinanceSettingsAction(formData: FormData) {
  const actor = await actorFor("finance.settings.manage");
  const parsed = financeSettingsSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/settings", parsed.error.issues[0]?.message ?? "Review finance settings.");
  const id = `${workspaceId}:default`; await prisma.financeSetting.upsert({ where: { id }, create: { id, workspaceId, ...parsed.data, createdBy: actor.id, updatedBy: actor.id }, update: { ...parsed.data, updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } });
  await audit(actor.id, "FINANCE_SETTINGS_UPDATED", "financeSetting", id); revalidatePath("/finance"); redirect("/finance/settings?saved=1");
}

export async function createQuoteAction(formData: FormData) {
  const actor = await actorFor("quotes.create"); const lines = parseLines(formData);
  const parsed = quoteSchema.safeParse({ ...Object.fromEntries(formData), purchaseOrderRequired: checked(formData, "purchaseOrderRequired"), lines });
  if (!parsed.success) fail("/finance/quotes/new", parsed.error.issues[0]?.message ?? "Review the quote.");
  const client = await clientFor(parsed.data.clientId, "/finance/quotes/new"); const calculated = calculateFinanceLines(parsed.data.lines as any, parsed.data.currency);
  const quoteId = randomUUID();
  await firestoreAdmin.runTransaction(async (transaction) => {
    const number = await numberNextInTransaction(transaction, "quote");
    transaction.create(firestoreAdmin.collection(collectionNames.quotes).doc(quoteId), { id: quoteId, workspaceId, quoteNumber: number, ...parsed.data, clientNameSnapshot: client.name, lines: calculated.lines, ...calculated.totals, status: "DRAFT", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), revision: 1 });
  });
  await audit(actor.id, "QUOTE_CREATED", "quote", quoteId, { quoteNumber: "server-assigned" }); revalidatePath("/finance/quotes"); redirect(`/finance/quotes/${quoteId}`);
}

export async function submitQuoteApprovalAction(formData: FormData) { const actor = await actorFor("quotes.update"); const id = value(formData, "id"); const quote = await prisma.quote.findUnique({ where: { id } }); if (!quote || quote.workspaceId !== workspaceId || quote.status !== "DRAFT") fail("/finance/quotes", "Only draft quotes can be submitted."); await prisma.quote.update({ where: { id }, data: { status: "PENDING_APPROVAL", updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "QUOTE_SUBMITTED", "quote", id); revalidatePath(`/finance/quotes/${id}`); redirect(`/finance/quotes/${id}`); }
export async function decideQuoteAction(formData: FormData) { const actor = await actorFor("quotes.approve"); const id = value(formData, "id"); const decision = value(formData, "decision"); const quote = await prisma.quote.findUnique({ where: { id } }); if (!quote || quote.workspaceId !== workspaceId || quote.status !== "PENDING_APPROVAL") fail("/finance/quotes", "Quote is not awaiting approval."); const status = decision === "approve" ? "APPROVED" : "DECLINED"; await prisma.quote.update({ where: { id }, data: { status, approvedBy: decision === "approve" ? actor.id : null, approvalReason: value(formData, "reason") || null, updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await prisma.financialApproval.create({ data: { id: randomUUID(), workspaceId, entityType: "quote", entityId: id, decision: status, reason: value(formData, "reason") || null, decidedBy: actor.id, createdAt: FieldValue.serverTimestamp() } }); await audit(actor.id, `QUOTE_${status}`, "quote", id); revalidatePath(`/finance/quotes/${id}`); redirect(`/finance/quotes/${id}`); }
export async function acceptQuoteAction(formData: FormData) { const actor = await actorFor("quotes.update"); const id = value(formData, "id"); const quote = await prisma.quote.findUnique({ where: { id } }); if (!quote || quote.workspaceId !== workspaceId || !["APPROVED", "SENT", "VIEWED"].includes(quote.status)) fail("/finance/quotes", "Quote cannot be accepted in its current state."); await prisma.quote.update({ where: { id }, data: { status: "ACCEPTED", acceptedBy: actor.id, acceptedAt: FieldValue.serverTimestamp(), acceptedSnapshotHash: documentHash(quote), updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "QUOTE_ACCEPTED", "quote", id); revalidatePath(`/finance/quotes/${id}`); redirect(`/finance/quotes/${id}`); }

export async function convertQuoteToInvoiceAction(formData: FormData) { const actor = await actorFor("invoices.create"); const quoteId = value(formData, "quoteId"); const quote = await prisma.quote.findUnique({ where: { id: quoteId } }); if (!quote || quote.workspaceId !== workspaceId || !["ACCEPTED", "APPROVED"].includes(quote.status)) fail("/finance/quotes", "Only approved or accepted quotes can be converted."); const invoiceId = randomUUID(); await firestoreAdmin.runTransaction(async (transaction) => { const number = await numberNextInTransaction(transaction, "invoice"); const invoiceRef = firestoreAdmin.collection(collectionNames.invoices).doc(invoiceId); transaction.create(invoiceRef, { id: invoiceId, workspaceId, invoiceNumber: number, clientId: quote.clientId, clientNameSnapshot: quote.clientNameSnapshot, quoteId, quoteNumber: quote.quoteNumber, invoiceDate: new Date(), dueDate: defaultDueDate(new Date()), currency: quote.currency, paymentTermsDays: env.FINANCE_DEFAULT_PAYMENT_TERMS_DAYS, lines: quote.lines, subtotalMinorUnits: quote.subtotalMinorUnits, discountMinorUnits: quote.discountMinorUnits, vatMinorUnits: quote.vatMinorUnits, totalMinorUnits: quote.totalMinorUnits, amountPaidMinorUnits: 0, status: "DRAFT", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); transaction.update(firestoreAdmin.collection(collectionNames.quotes).doc(quoteId), { status: "CONVERTED", convertedInvoiceId: invoiceId, updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() }); }); await audit(actor.id, "QUOTE_CONVERTED", "quote", quoteId, { invoiceId }); revalidatePath("/finance/invoices"); redirect(`/finance/invoices/${invoiceId}`); }

export async function createInvoiceAction(formData: FormData) { const actor = await actorFor("invoices.create"); const lines = parseLines(formData); const parsed = invoiceSchema.safeParse({ ...Object.fromEntries(formData), lines }); if (!parsed.success) fail("/finance/invoices", parsed.error.issues[0]?.message ?? "Review the invoice."); const client = await clientFor(parsed.data.clientId, "/finance/invoices"); const calculated = calculateFinanceLines(parsed.data.lines as any, parsed.data.currency); const invoiceId = randomUUID(); await firestoreAdmin.runTransaction(async (transaction) => { const number = await numberNextInTransaction(transaction, "invoice"); transaction.create(firestoreAdmin.collection(collectionNames.invoices).doc(invoiceId), { id: invoiceId, workspaceId, invoiceNumber: number, ...parsed.data, clientNameSnapshot: client.name, ...calculated.totals, lines: calculated.lines, amountPaidMinorUnits: 0, status: "DRAFT", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); }); await audit(actor.id, "INVOICE_CREATED", "invoice", invoiceId); revalidatePath("/finance/invoices"); redirect(`/finance/invoices/${invoiceId}`); }
export async function submitInvoiceApprovalAction(formData: FormData) { const actor = await actorFor("invoices.create"); const id = value(formData, "id"); const invoice = await prisma.invoice.findUnique({ where: { id } }); if (!invoice || invoice.workspaceId !== workspaceId || invoice.status !== "DRAFT") fail("/finance/invoices", "Only draft invoices can be submitted."); await prisma.invoice.update({ where: { id }, data: { status: "PENDING_APPROVAL", updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "INVOICE_SUBMITTED", "invoice", id); revalidatePath(`/finance/invoices/${id}`); redirect(`/finance/invoices/${id}`); }
export async function changeInvoiceStatusAction(formData: FormData) { const actor = await actorFor(value(formData, "status") === "SENT" ? "invoices.send" : "invoices.approve"); const id = value(formData, "id"); const next = value(formData, "status"); const invoice = await prisma.invoice.findUnique({ where: { id } }); if (!invoice || invoice.workspaceId !== workspaceId || (next === "APPROVED" && invoice.status !== "PENDING_APPROVAL") || (next === "SENT" && invoice.status !== "APPROVED")) fail("/finance/invoices", "Invoice cannot transition to that status."); let pdfDocumentId = invoice.pdfDocumentId ?? null; if (next === "SENT") { const pdf = buildFinancePdf({ title: "Tax Invoice", number: invoice.invoiceNumber, company: env.DEFAULT_COMPANY_NAME, client: invoice.clientNameSnapshot, currency: invoice.currency, lines: invoice.lines, totals: invoice, notes: invoice.clientNotes }); const storagePath = buildFinanceStoragePath(workspaceId, "invoices", id, `${invoice.invoiceNumber}.pdf`); const saved = await savePrivateBinaryToStorage({ storagePath, buffer: pdf, contentType: "application/pdf" }); pdfDocumentId = randomUUID(); await prisma.financialDocument.create({ data: { id: pdfDocumentId, workspaceId, entityType: "invoice", entityId: id, storagePath: saved.storagePath, contentType: "application/pdf", sizeBytes: pdf.length, sha256: createHash("sha256").update(pdf).digest("hex"), createdBy: actor.id, createdAt: FieldValue.serverTimestamp() } }); } await prisma.invoice.update({ where: { id }, data: { status: next, approvedBy: next === "APPROVED" ? actor.id : invoice.approvedBy, issuedBy: next === "SENT" ? actor.id : invoice.issuedBy, issuedAt: next === "SENT" ? FieldValue.serverTimestamp() : invoice.issuedAt, issuedHash: next === "SENT" ? documentHash(invoice) : invoice.issuedHash, pdfDocumentId, updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, `INVOICE_${next}`, "invoice", id); revalidatePath(`/finance/invoices/${id}`); redirect(`/finance/invoices/${id}`); }

export async function recordPaymentAction(formData: FormData) { const actor = await actorFor("payments.record"); const parsed = paymentSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/payments", parsed.error.issues[0]?.message ?? "Review payment."); await clientFor(parsed.data.clientId, "/finance/payments"); const paymentId = randomUUID(); const amountMinorUnits = parseDecimalToMinorUnits(parsed.data.amount, parsed.data.currency); await firestoreAdmin.runTransaction(async (transaction) => { const number = await numberNextInTransaction(transaction, "payment"); transaction.create(firestoreAdmin.collection(collectionNames.payments).doc(paymentId), { id: paymentId, workspaceId, paymentNumber: number, ...parsed.data, amountMinorUnits, status: "RECORDED", allocatedMinorUnits: 0, createdBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); }); await audit(actor.id, "PAYMENT_RECORDED", "payment", paymentId); revalidatePath("/finance/payments"); redirect("/finance/payments"); }
export async function allocatePaymentAction(formData: FormData) { const actor = await actorFor("payments.allocate"); const parsed = paymentAllocationSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/payments", parsed.error.issues[0]?.message ?? "Review allocation."); const amountMinorUnits = parseDecimalToMinorUnits(parsed.data.amount); await firestoreAdmin.runTransaction(async (transaction) => { const paymentRef = firestoreAdmin.collection(collectionNames.payments).doc(parsed.data.paymentId); const invoiceRef = firestoreAdmin.collection(collectionNames.invoices).doc(parsed.data.invoiceId); const [paymentSnapshot, invoiceSnapshot] = await Promise.all([transaction.get(paymentRef), transaction.get(invoiceRef)]); if (!paymentSnapshot.exists || !invoiceSnapshot.exists) throw new Error("PAYMENT_OR_INVOICE_NOT_FOUND"); const payment = paymentSnapshot.data() as any; const invoice = invoiceSnapshot.data() as any; const allocated = Number(payment.allocatedMinorUnits ?? 0); const invoiceAllocated = Number(invoice.amountPaidMinorUnits ?? 0); if (allocated + amountMinorUnits > Number(payment.amountMinorUnits) || invoiceAllocated + amountMinorUnits > Number(invoice.totalMinorUnits)) throw new Error("OVER_ALLOCATION"); const allocationId = randomUUID(); transaction.create(firestoreAdmin.collection(collectionNames.paymentAllocations).doc(allocationId), { id: allocationId, workspaceId, paymentId: parsed.data.paymentId, invoiceId: parsed.data.invoiceId, amountMinorUnits, allocatedBy: actor.id, createdAt: FieldValue.serverTimestamp() }); transaction.update(paymentRef, { allocatedMinorUnits: allocated + amountMinorUnits, status: allocated + amountMinorUnits === Number(payment.amountMinorUnits) ? "ALLOCATED" : "PARTIALLY_ALLOCATED", updatedAt: FieldValue.serverTimestamp() }); const invoicePaid = invoiceAllocated + amountMinorUnits; transaction.update(invoiceRef, { amountPaidMinorUnits: invoicePaid, status: invoicePaid >= Number(invoice.totalMinorUnits) ? "PAID" : "PARTIALLY_PAID", updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() }); }); await audit(actor.id, "PAYMENT_ALLOCATED", "payment", parsed.data.paymentId, { invoiceId: parsed.data.invoiceId, amountMinorUnits }); revalidatePath("/finance/payments"); revalidatePath(`/finance/invoices/${parsed.data.invoiceId}`); redirect("/finance/payments"); }

export async function createExpenseAction(formData: FormData) { const actor = await actorFor("expenses.create"); const parsed = expenseSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/expenses", parsed.error.issues[0]?.message ?? "Review expense."); const amountExcludingVatMinorUnits = parseDecimalToMinorUnits(parsed.data.amountExcludingVat, parsed.data.currency); const vatMinorUnits = Math.floor((amountExcludingVatMinorUnits * parsed.data.vatRateBps + 5000) / 10000); const id = randomUUID(); await prisma.expense.create({ data: { id, workspaceId, ...parsed.data, amountExcludingVatMinorUnits, vatMinorUnits, totalMinorUnits: amountExcludingVatMinorUnits + vatMinorUnits, status: "DRAFT", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "EXPENSE_CREATED", "expense", id); revalidatePath("/finance/expenses"); redirect("/finance/expenses"); }
export async function decideExpenseAction(formData: FormData) { const actor = await actorFor("expenses.approve"); const id = value(formData, "id"); const expense = await prisma.expense.findUnique({ where: { id } }); if (!expense || expense.workspaceId !== workspaceId || expense.status !== "PENDING_APPROVAL") fail("/finance/expenses", "Expense is not awaiting approval."); const employee = await prisma.employee.findUnique({ where: { id: expense.employeeId } }); if (employee?.userId === actor.id) fail("/finance/expenses", "Expenses cannot be self-approved."); const status = value(formData, "decision") === "approve" ? "APPROVED" : "REJECTED"; await prisma.expense.update({ where: { id }, data: { status, approvedBy: status === "APPROVED" ? actor.id : null, approvalReason: value(formData, "reason") || null, updatedBy: actor.id, updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, `EXPENSE_${status}`, "expense", id); revalidatePath("/finance/expenses"); redirect("/finance/expenses"); }

export async function createSupplierAction(formData: FormData) { const actor = await actorFor("suppliers.manage"); const parsed = supplierSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/suppliers", parsed.error.issues[0]?.message ?? "Review supplier."); const id = randomUUID(); await prisma.supplier.create({ data: { id, workspaceId, ...parsed.data, status: "ACTIVE", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "SUPPLIER_CREATED", "supplier", id); revalidatePath("/finance/suppliers"); redirect("/finance/suppliers"); }
export async function createBudgetAction(formData: FormData) { const actor = await actorFor("budgets.manage"); const parsed = budgetSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) fail("/finance/budgets", parsed.error.issues[0]?.message ?? "Review budget."); const id = randomUUID(); const approvedAmountMinorUnits = parseDecimalToMinorUnits(parsed.data.approvedAmount, parsed.data.currency); await prisma.budget.create({ data: { id, workspaceId, ...parsed.data, approvedAmountMinorUnits, committedMinorUnits: 0, actualMinorUnits: 0, status: "ACTIVE", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() } }); await audit(actor.id, "BUDGET_CREATED", "budget", id); revalidatePath("/finance/budgets"); redirect("/finance/budgets"); }
export async function createPurchaseOrderAction(formData: FormData) { const actor = await actorFor("purchase_orders.create"); const lines = parseLines(formData); const parsed = purchaseOrderSchema.safeParse({ ...Object.fromEntries(formData), lines }); if (!parsed.success) fail("/finance/purchase-orders", parsed.error.issues[0]?.message ?? "Review purchase order."); const calculated = calculateFinanceLines(parsed.data.lines as any, parsed.data.currency); const supplier = await prisma.supplier.findUnique({ where: { id: parsed.data.supplierId } }); if (!supplier || supplier.workspaceId !== workspaceId) fail("/finance/purchase-orders", "Selected supplier is not available."); const id = randomUUID(); await firestoreAdmin.runTransaction(async (transaction) => { const number = await numberNextInTransaction(transaction, "purchaseOrder"); transaction.create(firestoreAdmin.collection(collectionNames.purchaseOrders).doc(id), { id, workspaceId, purchaseOrderNumber: number, ...parsed.data, supplierNameSnapshot: supplier.name, ...calculated.totals, lines: calculated.lines, status: "DRAFT", createdBy: actor.id, updatedBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); }); await audit(actor.id, "PURCHASE_ORDER_CREATED", "purchaseOrder", id); revalidatePath("/finance/purchase-orders"); redirect("/finance/purchase-orders"); }
