"use server";

import { randomUUID } from "node:crypto";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { collectionNames } from "@/lib/collections";
import { firestoreAdmin } from "@/lib/db";
import { env } from "@/lib/env";
import { currentUser } from "@/lib/auth";
import { hasPermission } from "@/lib/permissions";
import { logAudit } from "@/lib/audit";
import { controlledDatasetFields, controlledDatasetMetrics, reportId, reportPermission, reportingWorkspaceId, requireReportingPermission } from "@/lib/reporting";
import { customReportSchema, reportAreaSchema, reportScheduleSchema, savedReportSchema } from "@/lib/validators-reporting";
import { resolveReportDateRange } from "@/lib/reporting-utils";

function value(formData: FormData, name: string) { return String(formData.get(name) ?? "").trim(); }
function checked(formData: FormData, name: string) { return formData.get(name) === "true" || formData.get(name) === "on"; }
function fail(path: string, message: string): never { redirect(`${path}?error=${encodeURIComponent(message)}`); }
function rethrowRedirect(error: any): void { if (String(error?.digest ?? "").startsWith("NEXT_REDIRECT")) throw error; }
async function ipAddress() { const requestHeaders = await headers(); return requestHeaders.get("x-forwarded-for")?.split(",")[0]?.trim() ?? requestHeaders.get("x-real-ip") ?? null; }
async function audit(action: string, entityType: string, entityId: string, metadata?: Record<string, unknown>) { const actor = await currentUser(); await logAudit({ userId: actor?.id, action, entityType, entityId, metadata, ipAddress: await ipAddress() }); }
async function loadOwnedReport(id: string, actorId: string): Promise<any | null> { const document = await firestoreAdmin.collection(collectionNames.savedReports).doc(id).get(); const data: any = document.exists ? { id: document.id, ...(document.data() ?? {}) } : null; return data && data.workspaceId === reportingWorkspaceId && (data.ownerId === actorId || data.sharedUserIds?.includes(actorId)) ? data : null; }

export async function saveReportAction(formData: FormData) {
  const actor = await requireReportingPermission("reports.custom.create"); const path = "/reports/saved";
  try {
    const area = reportAreaSchema.parse(value(formData, "area")); if (!hasPermission(actor, reportPermission(area)) && !hasPermission(actor, "reports.manage")) throw new Error("You cannot save a report for this reporting area.");
    const filtersJson = value(formData, "filtersJson") || "{}"; const parsedFilters = JSON.parse(filtersJson); if (!parsedFilters || typeof parsedFilters !== "object") throw new Error("Filters must be a JSON object.");
    const input = savedReportSchema.parse({ name: value(formData, "name"), description: value(formData, "description"), reportType: value(formData, "reportType") || area, area, filtersJson: JSON.stringify(parsedFilters), grouping: value(formData, "grouping"), sorting: value(formData, "sorting"), columns: value(formData, "columns").split(",").map((item) => item.trim()).filter(Boolean), chartType: value(formData, "chartType") || "TABLE" });
    const now = new Date(); const id = reportId(); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).create({ id, workspaceId: reportingWorkspaceId, ownerId: actor.id, sharedUserIds: [], sharedRoleIds: [], clientVisible: false, favourite: false, archivedAt: null, createdAt: now, updatedAt: now, ...input }); await audit("reports.saved.create", "SavedReport", id, { area }); revalidatePath(path); redirect(path);
  } catch (error: any) { rethrowRedirect(error); fail(path, error?.message ?? "Unable to save report."); }
}

export async function duplicateReportAction(formData: FormData) {
  const actor = await requireReportingPermission("reports.custom.create"); const sourceId = value(formData, "reportId"); const source = await loadOwnedReport(sourceId, actor.id); if (!source) fail("/reports/saved", "Report not found."); const id = reportId(); const now = new Date(); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).create({ ...source, id, name: `${source.name} copy`, ownerId: actor.id, sharedUserIds: [], sharedRoleIds: [], favourite: false, archivedAt: null, createdAt: now, updatedAt: now }); await audit("reports.saved.duplicate", "SavedReport", id, { sourceId }); revalidatePath("/reports"); redirect(`/reports/saved?report=${id}`);
}

export async function toggleReportFavouriteAction(formData: FormData) { const actor = await requireReportingPermission("reports.view"); const id = value(formData, "reportId"); const report = await loadOwnedReport(id, actor.id); if (!report) fail("/reports", "Report not found."); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).update({ favourite: !report.favourite, updatedAt: new Date() }); revalidatePath("/reports"); redirect("/reports"); }
export async function archiveReportAction(formData: FormData) { const actor = await requireReportingPermission("reports.custom.create"); const id = value(formData, "reportId"); const report = await loadOwnedReport(id, actor.id); if (!report) fail("/reports/saved", "Report not found."); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).update({ archivedAt: new Date(), updatedAt: new Date() }); revalidatePath("/reports"); redirect("/reports"); }
export async function restoreReportAction(formData: FormData) { const actor = await requireReportingPermission("reports.custom.create"); const id = value(formData, "reportId"); const report = await loadOwnedReport(id, actor.id); if (!report) fail("/reports/saved", "Report not found."); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).update({ archivedAt: null, updatedAt: new Date() }); revalidatePath("/reports"); redirect("/reports/saved"); }

export async function shareReportAction(formData: FormData) {
  const actor = await requireReportingPermission("reports.share"); const id = value(formData, "reportId"); const report = await loadOwnedReport(id, actor.id); if (!report || report.ownerId !== actor.id) fail("/reports/saved", "Only the report owner can share this report."); const sharedUserIds = value(formData, "sharedUserIds").split(",").map((item) => item.trim()).filter(Boolean).slice(0, 50); const userSnapshot = await firestoreAdmin.collection(collectionNames.users).where("workspaceId", "==", reportingWorkspaceId).where("status", "==", "ACTIVE").limit(1000).get(); const allowed = new Set(userSnapshot.docs.map((doc) => doc.id)); if (sharedUserIds.some((id) => !allowed.has(id))) fail("/reports/saved", "One or more shared users are outside this workspace."); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).update({ sharedUserIds, updatedAt: new Date() }); await audit("reports.saved.share", "SavedReport", id, { recipientCount: sharedUserIds.length }); revalidatePath("/reports"); redirect("/reports");
}

export async function createReportScheduleAction(formData: FormData) {
  const actor = await requireReportingPermission("reports.schedule"); const path = "/reports/schedules";
  try {
    const recipients = value(formData, "recipients").split(",").map((item) => item.trim().toLowerCase()).filter(Boolean); const report = await loadOwnedReport(value(formData, "reportId"), actor.id); if (!report) throw new Error("Report not found or not shared with you."); const area = reportAreaSchema.parse(report.area); if (!hasPermission(actor, reportPermission(area)) && !hasPermission(actor, "reports.manage")) throw new Error("You cannot schedule this report area."); const input = reportScheduleSchema.parse({ reportId: value(formData, "reportId"), frequency: value(formData, "frequency"), timezone: value(formData, "timezone") || env.DEFAULT_TIMEZONE, deliveryTime: value(formData, "deliveryTime") || "08:00", format: value(formData, "format") || "CSV", recipients, active: checked(formData, "active"), dateRangeBehaviour: value(formData, "dateRangeBehaviour") || "PREVIOUS_PERIOD" }); if (input.recipients.length > env.REPORTING_SCHEDULE_MAX_RECIPIENTS) throw new Error("Too many recipients."); const users = await firestoreAdmin.collection(collectionNames.users).where("workspaceId", "==", reportingWorkspaceId).where("status", "==", "ACTIVE").limit(1000).get(); const allowedEmails = new Set(users.docs.map((doc) => String(doc.data().email ?? "").toLowerCase())); if (input.recipients.some((recipient) => !allowedEmails.has(recipient))) throw new Error("Recipients must be active SourceHub users in this workspace."); const id = reportId(); const now = new Date(); await firestoreAdmin.collection(collectionNames.reportSchedules).doc(id).create({ id, workspaceId: reportingWorkspaceId, ownerId: actor.id, area, ...input, lastRunAt: null, nextRunAt: now, lastResult: null, failureCount: 0, createdAt: now, updatedAt: now }); await audit("reports.schedule.create", "ReportSchedule", id, { reportId: input.reportId, area }); revalidatePath(path); redirect(path);
  } catch (error: any) { rethrowRedirect(error); fail(path, error?.message ?? "Unable to schedule report."); }
}

export async function toggleReportScheduleAction(formData: FormData) { const actor = await requireReportingPermission("reports.schedule"); const id = value(formData, "scheduleId"); const document = await firestoreAdmin.collection(collectionNames.reportSchedules).doc(id).get(); if (!document.exists || document.data()?.workspaceId !== reportingWorkspaceId || document.data()?.ownerId !== actor.id) fail("/reports/schedules", "Schedule not found."); await document.ref.update({ active: !document.data()?.active, updatedAt: new Date() }); revalidatePath("/reports/schedules"); redirect("/reports/schedules"); }

export async function createReportExportAction(formData: FormData) { const actor = await requireReportingPermission("reports.export"); const area = reportAreaSchema.parse(value(formData, "area")); if (!hasPermission(actor, reportPermission(area)) && !hasPermission(actor, "reports.manage")) fail("/reports", "You cannot export this reporting area."); const format = ["CSV", "PDF", "MARKDOWN"].includes(value(formData, "format")) ? value(formData, "format") : "CSV"; const id = reportId(); const now = new Date(); const idempotencyKey = `${actor.id}:${area}:${value(formData, "preset") || "this-month"}:${format}:${now.toISOString().slice(0, 13)}`; const existing = await firestoreAdmin.collection(collectionNames.reportExports).where("workspaceId", "==", reportingWorkspaceId).where("idempotencyKey", "==", idempotencyKey).limit(1).get(); if (!existing.empty) redirect(`/reports?export=${existing.docs[0].id}`); await firestoreAdmin.collection(collectionNames.reportExports).doc(id).create({ id, workspaceId: reportingWorkspaceId, requestedBy: actor.id, area, format, filters: { preset: value(formData, "preset") || "this-month", clientId: value(formData, "clientId") }, status: "QUEUED", rowLimit: env.REPORTING_EXPORT_MAX_ROWS, idempotencyKey, storagePath: null, expiresAt: new Date(Date.now() + env.REPORTING_EXPORT_RETENTION_DAYS * 86400000), createdAt: now, updatedAt: now }); await audit("reports.export.create", "ReportExport", id, { area, format }); revalidatePath("/reports"); redirect(`/reports?export=${id}`); }

export async function createCustomReportAction(formData: FormData) { const actor = await requireReportingPermission("reports.custom.create"); const path = "/reports/builder"; try { const input = customReportSchema.parse({ dataset: value(formData, "dataset"), metric: value(formData, "metric"), dimension: value(formData, "dimension"), chartType: value(formData, "chartType") || "TABLE", filtersJson: value(formData, "filtersJson") || "{}" }); if (!controlledDatasetFields(input.dataset).includes(input.dimension) && input.dimension) throw new Error("That dimension is not approved for this dataset."); if (!controlledDatasetMetrics(input.dataset).includes(input.metric)) throw new Error("That metric is not approved for this dataset."); const id = reportId(); const now = new Date(); await firestoreAdmin.collection(collectionNames.savedReports).doc(id).create({ id, workspaceId: reportingWorkspaceId, ownerId: actor.id, name: `${input.dataset} ${input.metric} report`, description: "Controlled report builder configuration", reportType: "CUSTOM", area: input.dataset === "finance" ? "finance" : input.dataset === "knowledge" ? "knowledge" : input.dataset === "security" ? "security" : "executive", filtersJson: input.filtersJson, grouping: input.dimension, sorting: "value_desc", columns: [input.dimension, input.metric], chartType: input.chartType, dataset: input.dataset, metric: input.metric, sharedUserIds: [], sharedRoleIds: [], clientVisible: false, favourite: false, archivedAt: null, createdAt: now, updatedAt: now }); await audit("reports.custom.create", "SavedReport", id, { dataset: input.dataset, metric: input.metric }); revalidatePath("/reports"); redirect(`/reports/saved?report=${id}`); } catch (error: any) { rethrowRedirect(error); fail(path, error?.message ?? "Unable to create custom report."); } }

export async function saveDashboardPreferenceAction(formData: FormData) { const actor = await requireReportingPermission("reports.view"); const area = reportAreaSchema.parse(value(formData, "area")); const id = `${reportingWorkspaceId}:${actor.id}:${area}`; await firestoreAdmin.collection(collectionNames.dashboardPreferences).doc(id).set({ id, workspaceId: reportingWorkspaceId, userId: actor.id, area, filters: JSON.parse(value(formData, "filtersJson") || "{}"), updatedAt: new Date() }, { merge: true }); revalidatePath(`/reports/${area}`); redirect(`/reports/${area}`); }
