import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { formatMinorUnits } from "@/lib/money";
import { quoteStatusLabels, financeStatusTone } from "@/lib/finance-utils";
import { acceptQuoteAction, convertQuoteToInvoiceAction, decideQuoteAction, submitQuoteApprovalAction } from "@/lib/actions/finance";
import { Badge, Button, Card, CardContent, PageHeader } from "@/components/ui";
export const dynamic = "force-dynamic";
export default async function QuoteDetailPage({ params }: { params: Promise<{ id: string }> }) { const actor = await requirePermission("quotes.view"); const { id } = await params; const quote: any = await prisma.quote.findUnique({ where: { id } }); if (!quote || quote.workspaceId !== env.DEFAULT_WORKSPACE_ID) notFound(); return <div className="space-y-6"><PageHeader eyebrow="Quote" title={quote.quoteNumber} description={quote.clientNameSnapshot} actions={<Link href="/finance/quotes" className="text-sm text-sourcehub-primary">Back to quotes</Link>} /><div className="flex flex-wrap items-center gap-3"><Badge tone={financeStatusTone(quote.status)}>{quoteStatusLabels[quote.status] ?? quote.status}</Badge>{quote.status === "DRAFT" && actor.permissions.includes("quotes.update") ? <form action={submitQuoteApprovalAction}><input type="hidden" name="id" value={id} /><Button type="submit">Submit for approval</Button></form> : null}{quote.status === "PENDING_APPROVAL" && actor.permissions.includes("quotes.approve") ? <><form action={decideQuoteAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="decision" value="approve" /><Button type="submit">Approve</Button></form><form action={decideQuoteAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="decision" value="decline" /><Button type="submit" variant="outline">Decline</Button></form></> : null}{["APPROVED", "SENT", "VIEWED"].includes(quote.status) && actor.permissions.includes("quotes.update") ? <form action={acceptQuoteAction}><input type="hidden" name="id" value={id} /><Button type="submit" variant="outline">Record acceptance</Button></form> : null}{["APPROVED", "ACCEPTED"].includes(quote.status) && actor.permissions.includes("invoices.create") ? <form action={convertQuoteToInvoiceAction}><input type="hidden" name="quoteId" value={id} /><Button type="submit">Convert to invoice</Button></form> : null}</div><Card><CardContent><div className="grid gap-4 md:grid-cols-3"><div><p className="text-xs uppercase text-slate-500">Quote date</p><p className="font-medium">{new Date(quote.quoteDate).toLocaleDateString("en-ZA")}</p></div><div><p className="text-xs uppercase text-slate-500">Valid until</p><p className="font-medium">{new Date(quote.expiryDate).toLocaleDateString("en-ZA")}</p></div><div><p className="text-xs uppercase text-slate-500">Total</p><p className="text-xl font-semibold">{formatMinorUnits(Number(quote.totalMinorUnits), quote.currency)}</p></div></div><div className="mt-6 divide-y border-y">{quote.lines.map((line: any) => <div key={line.sortOrder} className="flex justify-between gap-4 py-3 text-sm"><span>{line.description} <span className="text-slate-500">x {line.quantity}</span></span><span className="font-medium">{formatMinorUnits(Number(line.lineTotalMinorUnits), quote.currency)}</span></div>)}</div></CardContent></Card></div>; }
