import Link from "next/link";

import { requirePermission } from "@/lib/auth";
import { recordPilotDecisionAction, updatePilotChecklistAction, updatePilotStatusAction } from "@/lib/actions/pilot";
import { getPilotDashboard } from "@/lib/pilot";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, PageHeader, Select, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow, Textarea } from "@/components/ui";

export const dynamic = "force-dynamic";

export default async function PilotDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await requirePermission("pilots.view");
  const { id } = await params;
  const detail = await getPilotDashboard(id, actor);
  const pilot = detail.pilot as Record<string, any>;
  const canManage = actor.permissions.includes("pilots.manage");
  const canUat = actor.permissions.includes("pilots.uat.manage");
  return <div className="space-y-6"><PageHeader eyebrow="Pilot programme" title={String(pilot.name)} description={String(pilot.description)} actions={<Link href={`/administration/pilots/${id}/uat`}><Button variant="outline">Open UAT workspace</Button></Link>} />
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>{String(pilot.synthetic ? "Synthetic pilot data" : "Internal pilot record")}:</strong> commercial mode is disabled and this record does not approve production deployment.</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["Status", String(pilot.status).replaceAll("_", " ")], ["Checklist", `${detail.checklist.filter((item: any) => item.status === "COMPLETE").length}/${detail.checklist.length}`], ["UAT passed", detail.uat.passed], ["UAT not run", detail.uat.notRun], ["Feedback", detail.feedback.length], ["Health checks", detail.health.length || "No data yet"]].map(([label, value]) => <Card key={String(label)}><CardContent><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></CardContent></Card>)}</div>
    <Card><CardContent><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Recommended next action</p><p className="mt-2 text-sm font-semibold">{detail.recommendedNextAction}</p><p className="mt-1 text-xs text-slate-500">Automated readiness is evidence only; it does not approve a pilot.</p></CardContent></Card>
    {canManage ? <Card><CardHeader><CardTitle>Controlled status change</CardTitle><CardDescription>Approved, active, completed, and cancelled changes require the explicit confirmation value.</CardDescription></CardHeader><CardContent><form action={updatePilotStatusAction} className="flex flex-wrap gap-3"><input type="hidden" name="pilotId" value={id} /><Select name="status" defaultValue={pilot.status}>{["DRAFT", "PREPARING", "READY_FOR_REVIEW", "APPROVED", "ACTIVE", "PAUSED", "COMPLETED", "CANCELLED"].map((status) => <option key={status}>{status}</option>)}</Select><Input name="confirmation" placeholder="Type CONFIRM_PILOT_CHANGE for high-risk changes" /><Button type="submit">Save status</Button></form></CardContent></Card> : null}
    <Card><CardHeader><CardTitle>Readiness checklist</CardTitle><CardDescription>Pending is the default. Evidence must be supplied by an authorised reviewer.</CardDescription></CardHeader><CardContent className="space-y-3">{detail.checklist.map((item: any) => <form action={updatePilotChecklistAction} key={item.id} className="grid gap-3 rounded-xl border border-sourcehub-border p-3 md:grid-cols-[1.5fr_160px_1fr_auto]"><input type="hidden" name="checklistId" value={item.id} /><input type="hidden" name="pilotId" value={id} /><div><p className="text-sm font-semibold">{item.title}</p><Input name="evidence" defaultValue={item.evidence ?? ""} placeholder="Evidence reference" className="mt-2" /></div><Select name="status" defaultValue={item.status} disabled={!canManage}>{["PENDING", "IN_PROGRESS", "COMPLETE", "BLOCKED"].map((status) => <option key={status}>{status}</option>)}</Select><Input name="notes" defaultValue={item.notes ?? ""} placeholder="Notes" disabled={!canManage} /><Button type="submit" size="sm" disabled={!canManage}>Update</Button></form>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Success criteria and limitations</CardTitle></CardHeader><CardContent className="grid gap-6 md:grid-cols-2"><div><h3 className="font-semibold">Criteria</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{(pilot.successCriteria ?? []).map((item: string) => <li key={item}>{item}</li>)}</ul></div><div><h3 className="font-semibold">Known limitations</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{(pilot.knownLimitations ?? []).map((item: string) => <li key={item}>{item}</li>)}</ul></div></CardContent></Card>
    <div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Feedback by type</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-2 text-sm">{Object.entries(detail.feedbackByType).map(([key, value]) => <div key={key} className="rounded-xl border border-sourcehub-border p-3"><p className="text-xs text-slate-500">{key.replaceAll("_", " ")}</p><p className="mt-1 text-xl font-semibold">{value || "No data yet"}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Open defects by priority</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-2 text-sm">{Object.entries(detail.defectsByPriority).map(([key, value]) => <div key={key} className="rounded-xl border border-sourcehub-border p-3"><p className="text-xs text-slate-500">{key}</p><p className="mt-1 text-xl font-semibold">{value || "No data yet"}</p></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Go / no-go decision record</CardTitle><CardDescription>Automated checks do not approve a pilot. Record human evidence and conditions.</CardDescription></CardHeader><CardContent><form action={recordPilotDecisionAction} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="pilotId" value={id} /><Select name="outcome"><option>NOT_READY</option><option>READY_FOR_INTERNAL_DEMONSTRATION</option><option>READY_FOR_CONTROLLED_INTERNAL_PILOT</option><option>CONDITIONALLY_READY</option><option>READY_FOR_EXPANDED_PILOT</option><option>READY_FOR_STAGED_PRODUCTION</option><option>PILOT_PAUSED</option><option>ROLLBACK_REQUIRED</option></Select><Textarea name="decisionMakers" required placeholder="Decision makers, one per line" /><Textarea name="evidenceReviewed" placeholder="Evidence reviewed, one per line" /><Textarea name="criticalDefects" placeholder="Critical defect IDs, one per line" /><Textarea name="acceptedRisks" placeholder="Accepted risks, one per line" /><Textarea name="outstandingActions" placeholder="Outstanding actions, one per line" /><Textarea name="conditions" placeholder="Conditions, one per line" /><Textarea name="approvalEvidence" placeholder="Approval evidence reference" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="rollbackReady" /> Rollback readiness reviewed</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="monitoringReady" /> Monitoring readiness reviewed</label><div className="md:col-span-2"><Button type="submit" disabled={!canManage}>Record decision</Button></div></form></CardContent></Card>
  </div>;
}
