import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, CalendarClock, Laptop, Mail, Network, Phone, ShieldAlert, UserRound } from "lucide-react";

import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { employeeDisplayName, employeeStatusLabels, employeeTypeLabels, maskIdentityReference } from "@/lib/employees";
import { formatDate, formatDateTime } from "@/lib/utils";
import { buttonClassName } from "@/lib/button";
import { AiContextLink } from "@/components/ai-context-link";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Input, PageHeader, Select, StatCard, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow, Textarea } from "@/components/ui";
import { changeEmployeeStatusAction, createContractAction, createEmergencyContactAction, createEmployeeNoteAction, createQualificationAction, createTrainingAction, startOffboardingAction, startOnboardingAction, updateEmployeeAction, uploadEmployeeDocumentAction } from "@/lib/actions/employees";

export default async function EmployeeDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await requirePermission("employees.view");
  const { id } = await params;
  const employee = await prisma.employee.findUnique({ where: { id } });
  if (!employee || employee.workspaceId !== env.DEFAULT_WORKSPACE_ID) notFound();
  const [department, team, manager, departments, teams, managers, contracts, contacts, qualifications, training, documents, notes, statuses, onboarding, offboarding, assets, endpoints, tickets] = await Promise.all([
    employee.departmentId ? prisma.department.findUnique({ where: { id: employee.departmentId } }) : null,
    employee.teamId ? prisma.team.findUnique({ where: { id: employee.teamId } }) : null,
    employee.managerId ? prisma.employee.findUnique({ where: { id: employee.managerId } }) : null,
    prisma.department.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, active: true }, orderBy: { name: "asc" } }),
    prisma.team.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, active: true }, orderBy: { name: "asc" } }),
    prisma.employee.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, status: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }], take: 200 }),
    actor.permissions.includes("employee_contracts.view") ? prisma.employeeContract.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { startDate: "desc" } }) : [],
    actor.permissions.includes("employee_emergency_contacts.view") ? prisma.employeeEmergencyContact.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: [{ primary: "desc" }, { fullName: "asc" }] }) : [],
    actor.permissions.includes("employee_qualifications.manage") ? prisma.employeeQualification.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { expiryDate: "asc" } }) : [],
    actor.permissions.includes("employee_training.manage") ? prisma.employeeTraining.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { dueDate: "asc" } }) : [],
    actor.permissions.includes("employee_documents.view") ? prisma.employeeDocument.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id, archivedAt: null }, orderBy: { uploadedAt: "desc" } }) : [],
    actor.permissions.includes("employee_notes.view") ? prisma.employeeNote.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { createdAt: "desc" } }) : [],
    actor.permissions.includes("employee_audit.view") ? prisma.employeeStatusHistory.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { effectiveDate: "desc" } }) : [],
    prisma.onboardingWorkflow.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { createdAt: "desc" }, take: 1 }),
    prisma.offboardingWorkflow.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, employeeId: id }, orderBy: { createdAt: "desc" }, take: 1 }),
    employee.userId ? prisma.asset.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, assignedUserId: employee.userId }, take: 50 }) : [],
    employee.userId ? prisma.endpoint.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, assignedUserId: employee.userId }, take: 50 }) : [],
    employee.userId ? prisma.ticket.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, requesterId: employee.userId }, orderBy: { createdAt: "desc" }, take: 10 }) : [],
  ]);
  const sensitive = actor.permissions.includes("employees.sensitive_view");
  const fullIdentity = actor.permissions.includes("employees.identity_view");
  const displayName = employeeDisplayName(employee);
  const dateValue = (value: any) => value ? new Date(value).toISOString().slice(0, 10) : "";
  const managerOptions = managers.filter((item: any) => item.id !== employee.id);

  return <div className="space-y-6">
    <PageHeader eyebrow="Employee Management" title={displayName} description={`${employee.employeeNumber} · ${employee.workEmail}`} actions={<div className="flex flex-wrap gap-2"><AiContextLink module="employees" type="employee" id={employee.id} enabled={actor.permissions.includes("ai.use") && actor.permissions.includes("ai.employees.use")} /><Link href="/employees" className={buttonClassName({ variant: "ghost" })}><ArrowLeft className="h-4 w-4" /> Directory</Link>{actor.permissions.includes("employees.update") ? <a href="#edit" className={buttonClassName({ variant: "secondary" })}>Edit employee</a> : null}</div>} />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Employment status" value={<Badge tone={employee.status === "ACTIVE" ? "success" : employee.status === "SUSPENDED" ? "danger" : "warning"}>{employeeStatusLabels[employee.status as keyof typeof employeeStatusLabels] || employee.status}</Badge>} hint={employeeTypeLabels[employee.employmentType as keyof typeof employeeTypeLabels] || employee.employmentType} icon={<UserRound className="h-5 w-5" />} /><StatCard label="Department" value={department?.name || "Unassigned"} hint={team?.name || "No team"} icon={<BriefcaseBusiness className="h-5 w-5" />} /><StatCard label="Assigned assets" value={assets.length} hint={`${endpoints.length} endpoints`} icon={<Laptop className="h-5 w-5" />} /><StatCard label="Open tickets" value={tickets.filter((ticket: any) => !["RESOLVED", "CLOSED"].includes(ticket.status)).length} hint="Requested by this employee" icon={<ShieldAlert className="h-5 w-5" />} /></div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
      <div className="space-y-6">
        <Card><CardHeader><CardTitle>Overview</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Info label="Job title" value={employee.jobTitle || "Unassigned"} /><Info label="Manager" value={manager ? employeeDisplayName(manager) : "Unassigned"} /><Info label="Work location" value={employee.workLocation || "Not recorded"} /><Info label="Start date" value={formatDate(employee.startDate)} /><Info label="Work email" value={employee.workEmail} /><Info label="Mobile" value={employee.mobileNumber || "Not recorded"} /><Info label="Identity reference" value={fullIdentity ? employee.identityReference || "Not recorded" : maskIdentityReference(employee.identityReference) || "Restricted"} /><Info label="Account state" value={employee.accountState || "Not linked"} /><Info label="Last updated" value={formatDateTime(employee.updatedAt)} /></CardContent></Card>
        <Card id="edit"><CardHeader><CardTitle>Edit employee</CardTitle></CardHeader><CardContent><form action={updateEmployeeAction} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Employee number" name="employeeNumber" defaultValue={employee.employeeNumber} required /><Field label="First name" name="firstName" defaultValue={employee.firstName} required /><Field label="Middle names" name="middleNames" defaultValue={employee.middleNames || ""} /><Field label="Last name" name="lastName" defaultValue={employee.lastName} required /><Field label="Preferred name" name="preferredName" defaultValue={employee.preferredName || ""} /><Field label="Work email" name="workEmail" type="email" defaultValue={employee.workEmail} required /><Field label="Personal email" name="personalEmail" type="email" defaultValue={sensitive ? employee.personalEmail || "" : ""} /><Field label="Mobile number" name="mobileNumber" defaultValue={employee.mobileNumber || ""} /><Field label="Identity/passport reference" name="identityReference" type="password" defaultValue={sensitive ? employee.identityReference || "" : ""} /><Field label="Job title" name="jobTitle" defaultValue={employee.jobTitle || ""} /><SelectField label="Department" name="departmentId" defaultValue={employee.departmentId || ""} options={departments.map((item: any) => [item.id, item.name])} /><SelectField label="Team" name="teamId" defaultValue={employee.teamId || ""} options={teams.map((item: any) => [item.id, item.name])} /><SelectField label="Manager" name="managerId" defaultValue={employee.managerId || ""} options={managerOptions.map((item: any) => [item.id, employeeDisplayName(item)])} /><SelectField label="Status" name="status" defaultValue={employee.status} options={Object.entries(employeeStatusLabels).map(([key, value]) => [key, value])} /><SelectField label="Employment type" name="employmentType" defaultValue={employee.employmentType} options={Object.entries(employeeTypeLabels).map(([key, value]) => [key, value])} /><Field label="Work location" name="workLocation" defaultValue={employee.workLocation || ""} /><Field label="Start date" name="startDate" type="date" defaultValue={dateValue(employee.startDate)} /><Field label="Contract end date" name="contractEndDate" type="date" defaultValue={dateValue(employee.contractEndDate)} /><Field label="Notice period (days)" name="noticePeriodDays" type="number" defaultValue={String(employee.noticePeriodDays || 0)} /><div className="md:col-span-2 lg:col-span-3"><label className="space-y-2 text-sm font-medium text-sourcehub-text">Internal notes<Textarea name="internalNotes" defaultValue={sensitive ? employee.internalNotes || "" : ""} disabled={!sensitive} /></label></div><div className="md:col-span-2 lg:col-span-3 flex justify-end"><Button type="submit">Save employee</Button></div></form></CardContent></Card>
        <Card><CardHeader><CardTitle>Employment lifecycle</CardTitle></CardHeader><CardContent className="space-y-4"><form action={changeEmployeeStatusAction} className="grid gap-3 md:grid-cols-[1fr_1fr_1.5fr_auto]"><input type="hidden" name="employeeId" value={employee.id} /><Select name="status" defaultValue={employee.status}>{Object.entries(employeeStatusLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</Select><Input name="effectiveDate" type="date" /><Input name="reason" placeholder="Reason for sensitive transitions" /><Button type="submit" variant="secondary">Change status</Button></form><div className="flex flex-wrap gap-2">{actor.permissions.includes("onboarding.manage") && employee.status === "PREBOARDING" ? <form action={startOnboardingAction}><input type="hidden" name="employeeId" value={employee.id} /><Button type="submit" variant="secondary">Start onboarding</Button></form> : null}{actor.permissions.includes("offboarding.manage") && ["ACTIVE", "ON_LEAVE", "SUSPENDED"].includes(employee.status) ? <form action={startOffboardingAction} className="flex gap-2"><input type="hidden" name="employeeId" value={employee.id} /><Input name="reason" placeholder="Offboarding reason" required /><Button type="submit" variant="danger">Start offboarding</Button></form> : null}</div>{statuses.length ? <div className="border-t border-sourcehub-border pt-4"><p className="mb-2 text-sm font-semibold">Status history</p>{statuses.map((entry: any) => <p key={entry.id} className="text-sm text-slate-600">{formatDate(entry.effectiveDate)} · {entry.fromStatus || "Created"} → {entry.toStatus}{entry.reason ? ` · ${entry.reason}` : ""}</p>)}</div> : null}</CardContent></Card>
        <Card><CardHeader><CardTitle>Assets, endpoints, and tickets</CardTitle></CardHeader><CardContent className="grid gap-6 md:grid-cols-3"><List title="Assets" icon={<Laptop className="h-4 w-4" />} items={assets.map((item: any) => `${item.assetTag || item.name} · ${item.status}`)} /><List title="Endpoints" icon={<Network className="h-4 w-4" />} items={endpoints.map((item: any) => `${item.hostname || item.name || item.id} · ${item.healthState || "Unknown"}`)} /><List title="Service desk" icon={<ShieldAlert className="h-4 w-4" />} items={tickets.map((item: any) => `${item.reference || item.id} · ${item.status}`)} /></CardContent></Card>
      </div>
      <div className="space-y-6">
        {actor.permissions.includes("employee_emergency_contacts.view") ? <Card><CardHeader><CardTitle>Emergency contacts</CardTitle></CardHeader><CardContent className="space-y-4">{contacts.map((contact: any) => <div key={contact.id} className="rounded-2xl border border-sourcehub-border p-3"><div className="flex items-center justify-between"><p className="font-semibold">{contact.fullName}</p>{contact.primary ? <Badge tone="success">Primary</Badge> : null}</div><p className="text-sm text-slate-600">{contact.relationship} · {contact.primaryPhone}</p><p className="text-xs text-slate-500">{contact.email || "No email recorded"}</p></div>)}{actor.permissions.includes("employee_emergency_contacts.manage") ? <form action={createEmergencyContactAction} className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Full name" name="fullName" required /><Field label="Relationship" name="relationship" required /><Field label="Primary phone" name="primaryPhone" required /><Field label="Email" name="email" type="email" /><Button type="submit" variant="secondary">Add contact</Button></form> : null}</CardContent></Card> : null}
        {actor.permissions.includes("employee_contracts.view") ? <Card><CardHeader><CardTitle>Contracts</CardTitle></CardHeader><CardContent className="space-y-3">{contracts.map((contract: any) => <div key={contract.id} className="rounded-2xl border border-sourcehub-border p-3"><div className="flex justify-between gap-3"><p className="font-semibold">{contract.contractReference}</p><Badge tone={contract.status === "ACTIVE" ? "success" : "warning"}>{contract.status}</Badge></div><p className="mt-1 text-sm text-slate-600">{contract.contractType} · {formatDate(contract.startDate)} to {formatDate(contract.endDate)}</p>{actor.permissions.includes("employees.compensation_view") && contract.compensationSummary ? <p className="mt-1 text-xs text-slate-500">Compensation: {contract.compensationSummary}</p> : null}</div>)}{actor.permissions.includes("employee_contracts.manage") ? <form action={createContractAction} className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Contract reference" name="contractReference" required /><Field label="Contract type" name="contractType" defaultValue="Employment" required /><Field label="Start date" name="startDate" type="date" required /><Field label="End date" name="endDate" type="date" /><Select name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="PENDING_SIGNATURE">Pending signature</option><option value="ACTIVE">Active</option></Select><Button type="submit" variant="secondary">Add contract</Button></form> : null}</CardContent></Card> : null}
        {actor.permissions.includes("employee_qualifications.manage") ? <Card><CardHeader><CardTitle>Qualifications</CardTitle></CardHeader><CardContent className="space-y-3">{qualifications.map((item: any) => <div key={item.id} className="rounded-2xl border border-sourcehub-border p-3"><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-600">{item.institution || "Institution not recorded"} · {item.verificationStatus}</p><p className="text-xs text-slate-500">Expires {formatDate(item.expiryDate)}</p></div>)}<form action={createQualificationAction} className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Qualification name" name="name" required /><Field label="Institution" name="institution" /><Field label="Expiry date" name="expiryDate" type="date" /><Select name="verificationStatus"><option value="UNVERIFIED">Unverified</option><option value="PENDING_VERIFICATION">Pending verification</option><option value="VERIFIED">Verified</option></Select><Button type="submit" variant="secondary">Add qualification</Button></form></CardContent></Card> : null}
        {actor.permissions.includes("employee_training.manage") ? <Card><CardHeader><CardTitle>Training</CardTitle></CardHeader><CardContent className="space-y-3">{training.map((item: any) => <div key={item.id} className="rounded-2xl border border-sourcehub-border p-3"><p className="font-semibold">{item.name}</p><p className="text-sm text-slate-600">{item.completionStatus} · Due {formatDate(item.dueDate)}</p></div>)}<form action={createTrainingAction} className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Training name" name="name" required /><Field label="Provider" name="provider" /><Field label="Due date" name="dueDate" type="date" /><Select name="completionStatus"><option value="ASSIGNED">Assigned</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></Select><Button type="submit" variant="secondary">Add training</Button></form></CardContent></Card> : null}
        {actor.permissions.includes("employee_documents.view") ? <Card><CardHeader><CardTitle>Secure documents</CardTitle></CardHeader><CardContent className="space-y-3">{documents.map((document: any) => <div key={document.id} className="rounded-2xl border border-sourcehub-border p-3"><div className="flex justify-between gap-3"><p className="font-semibold">{document.title}</p><Badge tone="outline">{document.confidentiality}</Badge></div><p className="mt-1 text-xs text-slate-500">{document.documentType} · Uploaded {formatDate(document.uploadedAt)}{document.expiryDate ? ` · Expires ${formatDate(document.expiryDate)}` : ""}</p></div>)}{actor.permissions.includes("employee_documents.manage") ? <form action={uploadEmployeeDocumentAction} encType="multipart/form-data" className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Field label="Title" name="title" required /><Select name="documentType"><option value="CONTRACT">Employment contract</option><option value="IDENTITY">Identity document</option><option value="QUALIFICATION">Qualification certificate</option><option value="TRAINING">Training certificate</option><option value="OTHER">Other</option></Select><Select name="confidentiality"><option value="STANDARD_HR">Standard HR</option><option value="RESTRICTED_HR">Restricted HR</option><option value="MANAGER_RESTRICTED">Manager restricted</option><option value="EMPLOYEE_VISIBLE">Employee visible</option><option value="HIGHLY_CONFIDENTIAL">Highly confidential</option></Select><input name="file" type="file" required className="block w-full rounded-xl border border-sourcehub-border p-2 text-sm" /><Button type="submit" variant="secondary">Upload securely</Button><p className="text-xs text-slate-500">Files are stored outside public uploads and require permission checks for access.</p></form> : null}</CardContent></Card> : null}
        {actor.permissions.includes("employee_notes.view") ? <Card><CardHeader><CardTitle>Notes</CardTitle></CardHeader><CardContent className="space-y-3">{notes.filter((note: any) => note.visibility !== "RESTRICTED" || actor.permissions.includes("employee_notes.manage")).map((note: any) => <div key={note.id} className="rounded-2xl border border-sourcehub-border p-3"><div className="flex justify-between"><Badge tone="outline">{note.category}</Badge><span className="text-xs text-slate-500">{formatDateTime(note.createdAt)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{note.body}</p></div>)}{actor.permissions.includes("employee_notes.manage") ? <form action={createEmployeeNoteAction} className="space-y-3 border-t border-sourcehub-border pt-4"><input type="hidden" name="employeeId" value={employee.id} /><Select name="category"><option value="GENERAL">General</option><option value="HR">HR</option><option value="ONBOARDING">Onboarding</option><option value="OFFBOARDING">Offboarding</option><option value="COMPLIANCE">Compliance</option><option value="RESTRICTED">Restricted</option></Select><Select name="visibility"><option value="HR">HR</option><option value="MANAGER">Manager</option><option value="RESTRICTED">Restricted</option><option value="EMPLOYEE">Employee visible</option></Select><Textarea name="body" placeholder="Add a controlled internal note" required /><Button type="submit" variant="secondary">Add note</Button></form> : null}</CardContent></Card> : null}
      </div>
    </div>
    <Card><CardHeader><CardTitle>Workflow status</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><WorkflowCard title="Onboarding" workflow={onboarding[0]} href="/employees/onboarding" /><WorkflowCard title="Offboarding" workflow={offboarding[0]} href="/employees/offboarding" /></CardContent></Card>
  </div>;
}

function Info({ label, value }: { label: string; value: any }) { return <div><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-sourcehub-text">{value}</p></div>; }
function Field({ label, name, type = "text", required, ...props }: { label: string; name: string; type?: string; required?: boolean; [key: string]: any }) { return <label className="space-y-2 text-sm font-medium text-sourcehub-text">{label}{required ? " *" : ""}<Input name={name} type={type} required={required} {...props} /></label>; }
function SelectField({ label, name, options, defaultValue }: { label: string; name: string; options: string[][]; defaultValue?: string }) { return <label className="space-y-2 text-sm font-medium text-sourcehub-text">{label}<Select name={name} defaultValue={defaultValue}><option value="">Not assigned</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</Select></label>; }
function List({ title, icon, items }: { title: string; icon: React.ReactNode; items: string[] }) { return <div><p className="flex items-center gap-2 text-sm font-semibold">{icon}{title}</p>{items.length ? <div className="mt-3 space-y-2">{items.map((item) => <p key={item} className="rounded-xl bg-slate-50 p-2 text-xs text-slate-600">{item}</p>)}</div> : <p className="mt-3 text-sm text-slate-500">None linked</p>}</div>; }
function WorkflowCard({ title, workflow, href }: { title: string; workflow: any; href: string }) { return <div className="rounded-2xl border border-sourcehub-border p-4"><div className="flex items-center justify-between"><p className="font-semibold">{title}</p>{workflow ? <Badge tone="warning">{workflow.status}</Badge> : <Badge tone="outline">Not started</Badge>}</div>{workflow ? <><p className="mt-2 text-sm text-slate-600">Started {formatDate(workflow.startedAt)} · {workflow.reason || "Tasks in progress"}</p><Link href={href} className="mt-3 inline-block text-sm font-semibold text-sourcehub-primary">Open workflow</Link></> : <Link href={href} className="mt-3 inline-block text-sm font-semibold text-sourcehub-primary">View workflows</Link>}</div>; }
