import Link from "next/link";
import { ArrowLeft, Ban, ClipboardCheck, FileWarning, Link2, RefreshCw, ShieldAlert } from "lucide-react";

import { requirePermission } from "@/lib/auth";
import { linkEndpointAssetAction, requestEndpointAuditAction, revokeEndpointAction } from "@/lib/actions/network";
import { buttonClassName } from "@/lib/button";
import { prisma } from "@/lib/db";
import { env } from "@/lib/env";
import { hasPermission } from "@/lib/permissions";
import { endpointComplianceLabels, endpointHealthLabels } from "@/lib/network";
import { Badge, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, PageHeader, Select, Table, TableBody, TableCell, TableHead, TableHeadCell, TableRow, Textarea } from "@/components/ui";
import { formatDateTime } from "@/lib/utils";

const tone: Record<string, "success" | "warning" | "danger" | "info"> = { HEALTHY: "success", AT_RISK: "warning", CRITICAL: "danger", OFFLINE: "danger", UNKNOWN: "info", COMPLIANT: "success", NON_COMPLIANT: "danger" };

export default async function EndpointDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const actor = await requirePermission("endpoints.view");
  const endpoint = await prisma.endpoint.findUnique({ where: { id } });
  if (!endpoint || endpoint.workspaceId !== env.DEFAULT_WORKSPACE_ID) return <div className="rounded-3xl border border-sourcehub-border bg-white p-8">Endpoint not found.</div>;
  const [client, site, environment, asset, snapshot, audits, changes, alerts, tickets, users, assets] = await Promise.all([
    prisma.client.findUnique({ where: { id: endpoint.clientId } }), prisma.clientSite.findUnique({ where: { id: endpoint.siteId } }), endpoint.networkEnvironmentId ? prisma.networkEnvironment.findUnique({ where: { id: endpoint.networkEnvironmentId } }) : null, endpoint.assetId ? prisma.asset.findUnique({ where: { id: endpoint.assetId } }) : null,
    prisma.endpointSnapshot.findUnique({ where: { id: endpoint.id } }), prisma.endpointAudit.findMany({ where: { endpointId: endpoint.id }, orderBy: [{ auditTimestamp: "desc" }], take: 10 }), prisma.endpointChange.findMany({ where: { endpointId: endpoint.id }, orderBy: [{ detectedAt: "desc" }], take: 30 }), prisma.networkAlert.findMany({ where: { endpointId: endpoint.id }, orderBy: [{ lastDetectedAt: "desc" }], take: 30 }), prisma.ticket.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, endpointId: endpoint.id }, orderBy: [{ updatedAt: "desc" }], take: 20 }), prisma.user.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, status: "ACTIVE" }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }] }), prisma.asset.findMany({ where: { workspaceId: env.DEFAULT_WORKSPACE_ID, clientId: endpoint.clientId, siteId: endpoint.siteId }, orderBy: [{ name: "asc" }], take: 100 }),
  ]);
  const audit = snapshot?.audit as Record<string, any> | undefined;
  return <div className="space-y-8">
    <PageHeader eyebrow="Endpoint Inventory" title={endpoint.computerName ?? "Unnamed endpoint"} description={`${client?.name ?? "Unknown client"} · ${site?.name ?? "Unknown site"}${environment ? ` · ${environment.name}` : ""}`} actions={<Link href="/network/endpoints" className={buttonClassName({ variant: "ghost" })}><ArrowLeft className="mr-2 h-4 w-4" />All endpoints</Link>} />
    <div className="flex flex-wrap gap-3"><Badge tone={tone[endpoint.healthState] ?? "info"}>{endpointHealthLabels[endpoint.healthState as keyof typeof endpointHealthLabels] ?? endpoint.healthState}</Badge><Badge tone={tone[endpoint.complianceState] ?? "info"}>{endpointComplianceLabels[endpoint.complianceState as keyof typeof endpointComplianceLabels] ?? endpoint.complianceState}</Badge><Badge tone={endpoint.checkInState === "ONLINE" ? "success" : endpoint.checkInState === "OFFLINE" ? "danger" : "warning"}>{endpoint.checkInState}</Badge>{endpoint.matchState === "AMBIGUOUS" ? <Badge tone="warning">Asset match needs review</Badge> : null}</div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Asset</p><p className="mt-2 font-semibold">{asset?.assetTag ?? "Unlinked"}</p><p className="text-xs text-slate-500">{asset?.name ?? "Link an authoritative asset record"}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Operating system</p><p className="mt-2 font-semibold">{endpoint.operatingSystem ?? "Unknown"}</p><p className="text-xs text-slate-500">{endpoint.windowsVersion ?? "Version not reported"} · build {endpoint.buildNumber ?? "unknown"}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Last check-in</p><p className="mt-2 font-semibold">{formatDateTime(endpoint.lastCheckIn)}</p><p className="text-xs text-slate-500">Audit {endpoint.lastAuditVersion ?? "not received"}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Open alerts</p><p className="mt-2 text-2xl font-bold">{endpoint.activeAlertCount ?? alerts.filter((item) => !["RESOLVED", "CLOSED"].includes(item.status)).length}</p><p className="text-xs text-slate-500">{tickets.length} linked tickets</p></CardContent></Card></div>

    <Card><CardHeader><CardTitle>Authorised actions</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><form action={requestEndpointAuditAction}><input type="hidden" name="endpointId" value={endpoint.id} /><button className={buttonClassName({ variant: "secondary" })}><RefreshCw className="mr-2 h-4 w-4" />Request new audit</button></form>{asset ? <Link href={`/tickets/new?assetId=${asset.id}`} className={buttonClassName({ variant: "outline" })}><FileWarning className="mr-2 h-4 w-4" />Create ticket</Link> : null}{hasPermission(actor, "endpoints.revoke") && !endpoint.revokedAt ? <form action={revokeEndpointAction}><input type="hidden" name="endpointId" value={endpoint.id} /><button className={buttonClassName({ variant: "danger" })}><Ban className="mr-2 h-4 w-4" />Revoke endpoint</button></form> : null}<a href="/scripts/SourceHub-WindowsAudit.ps1" download className={buttonClassName({ variant: "ghost" })}><ClipboardCheck className="mr-2 h-4 w-4" />Download audit script</a></CardContent></Card>

    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Overview</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm md:grid-cols-2"><div><p className="text-slate-500">Manufacturer</p><p className="font-medium">{endpoint.manufacturer ?? "Not reported"}</p></div><div><p className="text-slate-500">Model</p><p className="font-medium">{endpoint.model ?? "Not reported"}</p></div><div><p className="text-slate-500">Serial number</p><p className="font-medium">{endpoint.serialNumber ?? "Not reported"}</p></div><div><p className="text-slate-500">Logged-in user</p><p className="font-medium">{endpoint.loggedInUser ?? "Not reported"}</p></div><div><p className="text-slate-500">Responsible technician</p><p className="font-medium">{users.find((user) => user.id === endpoint.responsibleTechnicianId) ? `${users.find((user) => user.id === endpoint.responsibleTechnicianId)?.firstName} ${users.find((user) => user.id === endpoint.responsibleTechnicianId)?.lastName}` : "Unassigned"}</p></div><div><p className="text-slate-500">Device identity</p><p className="font-mono text-xs font-medium">{endpoint.deviceIdentifier ?? "Protected or unavailable"}</p></div><div><p className="text-slate-500">Antivirus</p><p className={endpoint.antivirusEnabled === false ? "font-medium text-red-700" : "font-medium"}>{endpoint.antivirusProduct ?? "Unknown"} · {endpoint.antivirusEnabled === true ? "Enabled" : endpoint.antivirusEnabled === false ? "Disabled" : "Unknown"}</p></div><div><p className="text-slate-500">Firewall / encryption</p><p className="font-medium">{endpoint.firewallEnabled === true ? "Firewall on" : endpoint.firewallEnabled === false ? "Firewall off" : "Firewall unknown"} · {endpoint.bitLockerEnabled === true ? "BitLocker on" : endpoint.bitLockerEnabled === false ? "BitLocker off" : "BitLocker unknown"}</p></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Hardware and network snapshot</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-slate-500">CPU</p><p className="font-medium">{audit?.hardware?.cpuModel ?? "Not reported"}</p></div><div><p className="text-slate-500">Memory</p><p className="font-medium">{audit?.hardware?.totalRamBytes ? `${Math.round(Number(audit.hardware.totalRamBytes) / 1073741824)} GB` : "Not reported"}</p></div><div><p className="text-slate-500">Network adapters</p>{audit?.network?.adapters?.length ? <ul className="space-y-2">{audit.network.adapters.slice(0, 6).map((adapter: any) => <li key={adapter.name} className="rounded-xl border border-sourcehub-border p-3"><p className="font-medium">{adapter.name}</p><p className="text-xs text-slate-500">{adapter.ipAddresses?.join(", ") || "No IP"} · {adapter.macAddress || "No MAC"}</p></li>)}</ul> : <p className="font-medium">No network snapshot yet</p>}</div></CardContent></Card></div>

    <Card><CardHeader><CardTitle><Link2 className="mr-2 inline h-5 w-5" />Asset assignment</CardTitle></CardHeader><CardContent><form action={linkEndpointAssetAction} className="flex flex-col gap-3 md:flex-row md:items-end"><input type="hidden" name="endpointId" value={endpoint.id} /><div className="flex-1"><label className="text-sm font-medium">Authoritative Phase 5 asset</label><Select name="assetId" defaultValue={endpoint.assetId ?? ""}><option value="">Choose an asset</option>{assets.map((item) => <option key={item.id} value={item.id}>{item.assetTag} · {item.name}</option>)}</Select></div><button className={buttonClassName({ variant: "secondary" })}>Link asset</button></form><p className="mt-3 text-xs text-slate-500">Asset identity, client, and site are validated server-side. Network-specific observations remain on the endpoint record.</p></CardContent></Card>

    <Card><CardHeader><CardTitle>Security posture</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border p-4"><p className="text-xs text-slate-500">Antivirus</p><p className="mt-1 font-semibold">{endpoint.antivirusEnabled === true ? "Enabled" : endpoint.antivirusEnabled === false ? "Disabled" : "Unknown"}</p></div><div className="rounded-2xl border p-4"><p className="text-xs text-slate-500">Firewall</p><p className="mt-1 font-semibold">{endpoint.firewallEnabled === true ? "Enabled" : endpoint.firewallEnabled === false ? "Disabled" : "Unknown"}</p></div><div className="rounded-2xl border p-4"><p className="text-xs text-slate-500">BitLocker</p><p className="mt-1 font-semibold">{endpoint.bitLockerEnabled === true ? "Enabled" : endpoint.bitLockerEnabled === false ? "Disabled" : "Unknown"}</p></div><div className="rounded-2xl border p-4"><p className="text-xs text-slate-500">Secure Boot / TPM</p><p className="mt-1 font-semibold">{endpoint.secureBootEnabled === true ? "Secure Boot on" : "Secure Boot unknown"} · {endpoint.tpmReady === true ? "TPM ready" : "TPM unknown"}</p></div></CardContent></Card>

    <Card><CardHeader><CardTitle>Alerts</CardTitle></CardHeader><CardContent className="p-0">{alerts.length === 0 ? <div className="p-6"><EmptyState title="No endpoint alerts" description="Alerts are created from trusted audit conditions and deduplicated by endpoint and condition." /></div> : <Table><TableHead><TableRow><TableHeadCell>Alert</TableHeadCell><TableHeadCell>Status</TableHeadCell><TableHeadCell>Occurrences</TableHeadCell><TableHeadCell>Last detected</TableHeadCell></TableRow></TableHead><TableBody>{alerts.map((alert) => <TableRow key={alert.id}><TableCell><Link href="/network/alerts" className="font-semibold text-sourcehub-primary hover:text-sourcehub-secondary">{String(alert.type).replace(/_/g, " ")}</Link><p className="text-xs text-slate-500">{alert.description}</p></TableCell><TableCell><Badge tone={alert.status === "RESOLVED" || alert.status === "CLOSED" ? "success" : "danger"}>{alert.status}</Badge></TableCell><TableCell>{alert.occurrenceCount ?? 1}</TableCell><TableCell>{formatDateTime(alert.lastDetectedAt)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>

    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Change history</CardTitle></CardHeader><CardContent className="p-0">{changes.length === 0 ? <div className="p-6 text-sm text-slate-500">No changes detected yet.</div> : <Table><TableHead><TableRow><TableHeadCell>Change</TableHeadCell><TableHeadCell>Severity</TableHeadCell><TableHeadCell>Detected</TableHeadCell></TableRow></TableHead><TableBody>{changes.map((change) => <TableRow key={change.id}><TableCell>{String(change.changeType).replace(/_/g, " ")}</TableCell><TableCell><Badge tone={tone[change.severity] ?? "info"}>{change.severity}</Badge></TableCell><TableCell>{formatDateTime(change.detectedAt)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card><Card><CardHeader><CardTitle>Linked tickets</CardTitle></CardHeader><CardContent className="p-0">{tickets.length === 0 ? <div className="p-6"><EmptyState title="No linked tickets" description="Tickets created from endpoint alerts will appear here." /></div> : <Table><TableHead><TableRow><TableHeadCell>Subject</TableHeadCell><TableHeadCell>Status</TableHeadCell><TableHeadCell>Updated</TableHeadCell></TableRow></TableHead><TableBody>{tickets.map((ticket) => <TableRow key={ticket.id}><TableCell><Link href={`/tickets/${ticket.id}`} className="font-semibold text-sourcehub-primary hover:text-sourcehub-secondary">{ticket.subject}</Link></TableCell><TableCell>{ticket.status}</TableCell><TableCell>{formatDateTime(ticket.updatedAt)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></div>

    {hasPermission(actor, "endpoint_raw_audits.view") ? <Card><CardHeader><CardTitle>Raw audit metadata</CardTitle></CardHeader><CardContent className="p-0">{audits.length === 0 ? <div className="p-6 text-sm text-slate-500">No audit history received.</div> : <Table><TableHead><TableRow><TableHeadCell>Audit ID</TableHeadCell><TableHeadCell>Script / schema</TableHeadCell><TableHeadCell>Timestamp</TableHeadCell><TableHeadCell>Payload hash</TableHeadCell></TableRow></TableHead><TableBody>{audits.map((item) => <TableRow key={item.id}><TableCell className="font-mono text-xs">{item.id}</TableCell><TableCell>{item.scriptVersion} / {item.schemaVersion}</TableCell><TableCell>{formatDateTime(item.auditTimestamp)}</TableCell><TableCell className="font-mono text-xs">{item.payloadHash ?? "Protected"}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card> : <Card><CardContent className="p-5 text-sm text-slate-500"><ShieldAlert className="mr-2 inline h-4 w-4" />Raw audit payloads are restricted by permission.</CardContent></Card>}
  </div>;
}
