import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { listAiConversations, loadAiConversation } from "@/lib/ai";
import { aiContextTypeSchema, aiModuleSchema } from "@/lib/validators-ai";
import { archiveAiConversationAction, confirmAiActionAction, deleteAiConversationAction, sendAiMessageAction, startAiConversationAction, submitAiFeedbackAction } from "@/lib/actions/ai";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, PageHeader, Textarea } from "@/components/ui";

export default async function AiPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const actor = await requirePermission("ai.use");
  const query = await searchParams;
  const selectedId = String(query.conversation ?? "");
  const contextModule = aiModuleSchema.safeParse(String(query.contextModule ?? "")).success ? String(query.contextModule) : "";
  const contextType = aiContextTypeSchema.safeParse(String(query.contextType ?? "")).success ? String(query.contextType) : "";
  const contextId = String(query.contextId ?? "");
  const conversations = await listAiConversations(actor);
  const selected: any = selectedId ? await loadAiConversation(actor, selectedId).catch(() => null) : null;
  const activeContext: any = selected?.conversation ?? { contextModule, contextType, contextRecordId: contextId };
  const suggestions = ["Show me the overdue tickets.", "Find the printer troubleshooting guide.", "Explain the current service-desk KPI definitions.", "Summarise projects currently at risk."];

  return <div className="space-y-6">
    <PageHeader eyebrow="Secure assistant" title="SourceHub AI" description="Ask questions about authorised SourceHub data. Sources are checked before retrieval, sensitive fields are redacted, and drafts never send or mutate records silently." actions={<Badge tone="info">{process.env.NODE_ENV === "production" ? "Provider configured" : "Development adapter"}</Badge>} />
    {query.error ? <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{String(query.error)}</div> : null}
    <div className="grid gap-6 xl:grid-cols-[280px_1fr]">
      <Card><CardHeader className="flex items-center justify-between gap-3"><CardTitle>Conversations</CardTitle><form action={startAiConversationAction}><Button type="submit" size="sm">New</Button></form></CardHeader><CardContent className="space-y-2">{conversations.length ? conversations.map((conversation: any) => <Link key={conversation.id} href={`/ai?conversation=${conversation.id}`} className={`block rounded-xl border p-3 text-sm ${conversation.id === selectedId ? "border-sourcehub-primary bg-sourcehub-primary/5" : "border-sourcehub-border hover:border-sourcehub-primary"}`}><p className="font-medium">{conversation.title}</p><p className="mt-1 text-xs text-slate-500">{conversation.contextModule ?? "General"}</p></Link>) : <p className="text-sm text-slate-500">No conversations yet.</p>}</CardContent></Card>
      <div className="space-y-6">
        <Card><CardHeader><CardTitle>Authorised context</CardTitle><p className="mt-1 text-sm text-slate-600">{activeContext.contextType && activeContext.contextRecordId ? `${activeContext.contextType} ${activeContext.contextRecordId}` : "No record selected. Ask a workspace-level question."}</p></CardHeader><CardContent><div className="flex flex-wrap gap-2">{suggestions.map((suggestion) => <form key={suggestion} action={sendAiMessageAction}><input type="hidden" name="conversationId" value={selectedId} /><input type="hidden" name="prompt" value={suggestion} /><input type="hidden" name="contextModule" value={String(activeContext.contextModule ?? contextModule)} /><input type="hidden" name="contextType" value={String(activeContext.contextType ?? contextType)} /><input type="hidden" name="contextId" value={String(activeContext.contextRecordId ?? contextId)} /><Button type="submit" size="sm" variant="outline">{suggestion}</Button></form>)}</div></CardContent></Card>
        {selected ? <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>{selected.conversation.title}</CardTitle><p className="mt-1 text-xs text-slate-500">Provider: {selected.conversation.provider} · Model: {selected.conversation.modelIdentifier}</p></div><div className="flex gap-2"><form action={archiveAiConversationAction}><input type="hidden" name="conversationId" value={selectedId} /><Button type="submit" size="sm" variant="outline">Archive</Button></form><form action={deleteAiConversationAction}><input type="hidden" name="conversationId" value={selectedId} /><Button type="submit" size="sm" variant="danger">Delete</Button></form></div></div></CardHeader><CardContent className="space-y-5">{selected.messages.length ? selected.messages.map((message: any) => <div key={message.id} className={`rounded-2xl p-4 ${message.role === "USER" ? "ml-8 bg-sourcehub-muted" : "mr-8 border border-sourcehub-border bg-white"}`}><div className="flex items-center justify-between gap-3"><Badge tone={message.role === "USER" ? "outline" : "info"}>{message.role === "USER" ? "You" : "SourceHub AI"}</Badge>{message.suspicious ? <Badge tone="warning">Suspicious source withheld</Badge> : null}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{message.content}</p>{message.sourceRefs?.length ? <div className="mt-4 border-t border-sourcehub-border pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Sources used</p><div className="mt-2 flex flex-wrap gap-2">{message.sourceRefs.map((source: any) => <Link key={`${source.type}:${source.id}`} href={source.href} className="rounded-lg border border-sourcehub-border px-2 py-1 text-xs text-sourcehub-primary hover:border-sourcehub-primary">{source.title}</Link>)}</div></div> : null}{message.role === "ASSISTANT" ? <div className="mt-4 flex flex-wrap items-center gap-2"><form action={submitAiFeedbackAction}><input type="hidden" name="messageId" value={message.id} /><input type="hidden" name="rating" value="HELPFUL" /><Button type="submit" size="sm" variant="ghost">Helpful</Button></form><form action={submitAiFeedbackAction}><input type="hidden" name="messageId" value={message.id} /><input type="hidden" name="rating" value="NOT_HELPFUL" /><Button type="submit" size="sm" variant="ghost">Not helpful</Button></form></div> : null}</div>) : <EmptyState title="Start the conversation" description="Ask about authorised tickets, clients, assets, projects, knowledge, reports or KPIs." />}</CardContent></Card> : <Card><CardContent><EmptyState title="Choose or start a conversation" description="The assistant never receives unrestricted Firestore access. Select a conversation or start a new one." action={<form action={startAiConversationAction}><Button type="submit">Start conversation</Button></form>} /></CardContent></Card>}
        {selected?.proposals?.length ? <Card><CardHeader><CardTitle>Proposed actions</CardTitle><p className="mt-1 text-sm text-slate-600">Review each draft before confirming. No reply is sent and no authoritative record is changed by confirmation.</p></CardHeader><CardContent className="space-y-3">{selected.proposals.map((proposal: any) => <div key={proposal.id} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{proposal.title}</p><Badge tone={proposal.status === "PROPOSED" ? "warning" : "success"}>{proposal.status}</Badge></div><pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap text-xs text-slate-700">{JSON.stringify(proposal.payload, null, 2)}</pre>{proposal.status === "PROPOSED" ? <form action={confirmAiActionAction} className="mt-3"><input type="hidden" name="proposalId" value={proposal.id} /><Button type="submit" size="sm">Confirm draft preparation</Button></form> : null}</div>)}</CardContent></Card> : null}
        <Card><CardContent><form action={sendAiMessageAction} className="space-y-3"><input type="hidden" name="conversationId" value={selectedId} /><input type="hidden" name="contextModule" value={String(activeContext.contextModule ?? contextModule)} /><input type="hidden" name="contextType" value={String(activeContext.contextType ?? contextType)} /><input type="hidden" name="contextId" value={String(activeContext.contextRecordId ?? contextId)} /><Textarea name="prompt" required maxLength={24000} placeholder="Ask SourceHub AI about your authorised workspace data..." /><div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Responses are server-orchestrated, source-linked, redacted, rate-limited and audited.</p><Button type="submit">Ask SourceHub AI</Button></div></form></CardContent></Card>
      </div>
    </div>
  </div>;
}
